/* eslint-disable quote-props */
/* eslint-disable quotes */

const data = {
  "initialValue": {
    "partname": "Cable FFC-190620.excel",
    "partnumber": "T005",
    "FFCQty": 2,
    "FFCPin": 20,
    "FFCPitch": 2,
    "FFCCableLength": 85.5,
    "FFCBendTImes": 2,
    "FFCPrint": 1,
    "FFCFlush": true,
    "FFCGoldPlating": 1,
    "FFCStopLine": 2,
    "FFCAlFoil": null,
    "FFCAlFoilLength": 85.5,
    "FFCAlFoilQty": 1,
    "FFCReinforcingPlate": null,
    "FFCReinforcingPlateLength": 10,
    "FFCReinforcingPlateQty": 3,
    "FFCLabel": null,
    "FFCLabelQty": 1,
    "FFCConductiveCloth": null,
    "FFCConductiveClothLength": 85.5,
    "FFCConductiveClothQty": 1,
    "FFCAdhesive1": null,
    "FFCAdhesive1Length": 15,
    "FFCAdhesive1width": 10,
    "FFCAdhesive1Qty": 1,
    "FFCAdhesive2": null,
    "FFCAdhesive2Length": 10,
    "FFCAdhesive2width": 20,
    "FFCAdhesive2Qty": 1,
    "FFCRemarks": null
  },
  "Price": {
    "cableFFC": {
      "partname": "Cable FFC-190620.excel",
      "partnumber": "T005",
      "FFCQty": 2,
      "FFCPin": 20,
      "FFCPitch": 2,
      "FFCCableLength": 85.5,
      "FFCBendTImes": 2,
      "FFCPrint": 1,
      "FFCFlush": true,
      "FFCGoldPlating": 1,
      "FFCStopLine": 2,
      "FFCAlFoil": null,
      "FFCAlFoilLength": 85.5,
      "FFCAlFoilQty": 1,
      "FFCReinforcingPlate": null,
      "FFCReinforcingPlateLength": 10,
      "FFCReinforcingPlateQty": 3,
      "FFCLabel": null,
      "FFCLabelQty": 1,
      "FFCConductiveCloth": null,
      "FFCConductiveClothLength": 85.5,
      "FFCConductiveClothQty": 1,
      "FFCAdhesive1": null,
      "FFCAdhesive1Length": 15,
      "FFCAdhesive1width": 10,
      "FFCAdhesive1Qty": 1,
      "FFCAdhesive2": null,
      "FFCAdhesive2Length": 10,
      "FFCAdhesive2width": 20,
      "FFCAdhesive2Qty": 1,
      "FFCRemarks": null
    }
  },
  "Images": []
};

export default data;
