
CREATE TABLE IF NOT EXISTS wiprocurement.product_profitcenter_to_stage
(
  product TEXT NOT NULL,
  customer TEXT NOT NULL,
  profitcenter TEXT NOT NULL,
  stage VARCHAR(5),
  stagename VARCHAR(5)
);

--Insert Data
INSERT INTO wiprocurement.product_profitcenter_to_stage (product, customer, profitcenter, stage, stagename) VALUES
('NB','Annie','PCL100','C0','RFI'),
('NB','Annie','PCL100','C1','RFQ'),
('NB','Annie','PCL100','C2','LAB'),
('NB','Annie','PCL100','C3','DB'),
('NB','Annie','PCL100','C4','ENG'),
('NB','Annie','PCL100','C5','PD'),
('NB','Annie','PCL100','C6','MP'),
('NB','Melody','PCL120','C0','RFI'),
('NB','Melody','PCL120','C1','RFQ'),
('NB','Melody','PCL120','C2','LAB'),
('NB','Melody','PCL120','C3','DB'),
('NB','Melody','PCL120','C4','ENG'),
('NB','Melody','PCL120','C5','PD'),
('NB','Melody','PCL120','C6','MP'),
('NB','Astro','PCL200','C0','RFI'),
('NB','Astro','PCL200','C1','RFQ'),
('NB','Astro','PCL200','C2','LAB'),
('NB','Astro','PCL200','C3','DB'),
('NB','Astro','PCL200','C4','SI'),
('NB','Astro','PCL200','C5','PV'),
('NB','Astro','PCL200','C6','MV'),
('DT','Astro','PCL200','C0','RFI'),
('DT','Astro','PCL200','C1','RFQ'),
('DT','Astro','PCL200','C2','LAB'),
('DT','Astro','PCL200','C3','DB'),
('DT','Astro','PCL200','C4','SI'),
('DT','Astro','PCL200','C5','PV'),
('DT','Astro','PCL200','C6','MV'),
('NB','Lily','PCL300','C0','RFI'),
('NB','Lily','PCL300','C1','RFQ'),
('NB','Lily','PCL300','C2','SDV'),
('NB','Lily','PCL300','C3','FVT'),
('NB','Lily','PCL300','C4','SIT'),
('NB','Lily','PCL300','C5','SVT'),
('NB','Lily','PCL300','C6','SOVP'),
('NB','Rosa','PCL500','C0','RFI'),
('NB','Rosa','PCL500','C1','RFQ'),
('NB','Rosa','PCL500','C2','EVT'),
('NB','Rosa','PCL500','C3','DVT1'),
('NB','Rosa','PCL500','C4','DVT2'),
('NB','Rosa','PCL500','C5','PB'),
('NB','Rosa','PCL500','C6','MP'),
('DT','Rosa','PCL500','C0','RFI'),
('DT','Rosa','PCL500','C1','RFQ'),
('DT','Rosa','PCL500','C2','EVT'),
('DT','Rosa','PCL500','C3','DVT1'),
('DT','Rosa','PCL500','C4','DVT2'),
('DT','Rosa','PCL500','C5','PB'),
('DT','Rosa','PCL500','C0','MP')
