CREATE TABLE IF NOT EXISTS wiprocurement.PS_EE_PRCRMNT_VW_A
(
  EMPLID VARCHAR(22),
  NAME VARCHAR(100),
  NAME_A VARCHAR(100),
  EMAIL_ADDRESS_A VARCHAR(100),
  DEPTID VARCHAR(20),
  SUPERVISOR_ID VARCHAR(22),
  LOCATION VARCHAR(20),
  PHONE_A VARCHAR(30),
  PRIMARY KEY (EMPLID)
 )