CREATE TABLE IF NOT EXISTS wiprocurement.matdoc (
  ZCRTDAT               date,
  ZCRTTIM               varchar(9),
  MKPFCFLG              varchar(1),
  MSEGCFLG              varchar(1),
  MBLNR                 varchar(10),
  MJAHR                 numeric,
  VGART                 varchar(2),
  BLART                 varchar(2),
  BLAUM                 varchar(2),
  BLDAT                 date,
  BUDAT                 date,
  CPUDT                 date,
  CPUTM                 time,
  AEDAT                 date,
  USNAM                 varchar(12),
  XBLNR                 varchar(16),
  BKTXT                 varchar(25),
  XABLN                 varchar(10),
  AWSYS                 varchar(10),
  TCODE2                varchar(20),
  SPE_BUDAT_UHR         time,
  SPE_BUDAT_ZONE        varchar(6),
  LE_VBELN              varchar(10),
  primary key(MBLNR, MJAHR)
);

CREATE TABLE IF NOT EXISTS wiprocurement.matdoc_ln (
  MBLNR                 varchar(10),
  MJAHR                 numeric,
  ZEILE                 numeric,
  LINE_ID               numeric,
  PARENT_ID             numeric,
  BWART                 varchar(3),
  XAUTO                 varchar(1),
  MATNR                 varchar(18),
  WERKS                 varchar(4),
  LGORT                 varchar(4),
  CHARG                 varchar(10),
  INSMK                 varchar(1),
  SOBKZ                 varchar(1),
  LIFNR                 varchar(10),
  KUNNR                 varchar(10),
  KDAUF                 varchar(10),
  KDPOS                 numeric,
  KDEIN                 numeric,
  SHKZG                 varchar(1),
  WAERS                 text,
  DMBTR                 decimal(13,3),
  BUALT                 decimal(13,3),
  MENGE                 decimal(13,3),
  MEINS                 text,
  ERFMG                 decimal(13,3),
  ERFME                 text,
  BPMNG                 decimal(13,3),
  BPRME                 text,
  EBELN                 varchar(10),
  EBELP                 numeric,
  LFBJA                 numeric,
  LFBNR                 varchar(10),
  LFPOS                 numeric,
  SJAHR                 numeric,
  SMBLN                 varchar(10),
  SMBLP                 numeric,
  ELIKZ                 varchar(1),
  SGTXT                 varchar(50),
  WEMPF                 varchar(12),
  ABLAD                 varchar(25),
  KOKRS                 varchar(4),
  KOSTL                 varchar(10),
  AUFNR                 varchar(12),
  GJAHR                 numeric,
  BUKRS                 varchar(4),
  RSNUM                 numeric,
  RSPOS                 numeric,
  UMMAT                 varchar(18),
  UMWRK                 varchar(4),
  UMLGO                 varchar(4),
  KZBEW                 varchar(1),
  KZVBR                 varchar(1),
  KZZUG                 varchar(1),
  GRUND                 numeric,
  EVERS                 varchar(2),
  PRCTR                 varchar(10),
  AUFPS                 numeric,
  SAKTO                 varchar(10),
  PPRCTR                varchar(10),
  QINSPST               varchar(1),
  EMATN                 varchar(18),
  MAT_KDAUF             varchar(10),
  MAT_KDPOS             numeric,
  LLIEF                 varchar(10),
  ZUSTD_T156M           varchar(1),
  VGART_MKPF            varchar(2),
  BUDAT_MKPF            date,
  CPUDT_MKPF            date,
  CPUTM_MKPF            time,
  USNAM_MKPF            varchar(12),
  XBLNR_MKPF            varchar(16),
  TCODE2_MKPF           varchar(20),
  VBELN_IM              varchar(10),
  VBELP_IM              numeric,
  PRUEFLOS              numeric,
  ZMSEG_TLGORT          varchar(4),
  primary key(MBLNR, MJAHR, ZEILE)
);
CREATE INDEX idx_matdocln_cpudt_mkpf ON wiprocurement.matdoc_ln(cpudt_mkpf);
CREATE INDEX IDX_matdoc_ln_ebeln ON wiprocurement.matdoc_ln(ebeln);
CREATE INDEX IDX_matdoc_ln_ebelp ON wiprocurement.matdoc_ln(ebelp);
CREATE INDEX IDX_matdoc_ln_werks ON wiprocurement.matdoc_ln(werks);