CREATE TABLE IF NOT EXISTS wiprocurement.mara (
  ZCRTDAT               date,
  ZCRTTIM               varchar(9),
  DATACFLG              varchar(1),
  MARCCFLG              varchar(1),
  MVKECFLG              varchar(1),
  MATNR                 varchar(18) PRIMARY KEY,
  MAKTX                 varchar(40),
  MTART                 varchar(4),
  MATKL                 varchar(9),
  ZZCATE                varchar(10),
  ZZMOD                 varchar(10),
  ZZGFTO                varchar(60),
  ZZCPJN                varchar(30),
  ZZCGRP                varchar(30),
  SPART                 varchar(2),
  LVORM                 varchar(1),
  ZZGLDE                varchar(60),
  NORMT                 varchar(18),
  ZZCMDN                varchar(40),
  ZZLPNO                varchar(35),
  ZZMNCO                varchar(3),
  ZZMJCO                varchar(3),
  ZZPDID                varchar(18),
  MEINS                 text,
  ZZAGIT                varchar(100),
  ZZEQPN                varchar(18),
  ZZCBDN                varchar(50),
  ZZPDCA                varchar(60),
  ZZGLISE               varchar(5),
  ZZSERI                varchar(3),
  ZZAPNO                varchar(18),
  ZZSPRD                varchar(1),
  MPROF                 varchar(4),
  ZZCONFIG1             varchar(6),
  ZZCONFIG2             varchar(10),
  ZZCOLOR1              varchar(10),
  ZZCOLOR2              varchar(2),
  ZZATYPE               varchar(20),
  ZZAREGION             varchar(6),
  ZZPACKTYPE            varchar(6),
  ZZREVI                varchar(20),
  ZZCRIS                varchar(6),
  ZZEEME                varchar(40),
  ZZCONTYP1             varchar(40),
  ZZCONTYP2             varchar(40),
  ZZUNIQUE              varchar(1),
  DISST                 varchar(3)
);
CREATE INDEX index_MARA_MATNR ON wiprocurement.mara(MATNR);
CREATE INDEX index_MARA_ZZCONTYP ON wiprocurement.mara(ZZCONTYP1, ZZCONTYP2);

CREATE TABLE IF NOT EXISTS wiprocurement.marc (
  DATACFLG              varchar(1),
  MDMACFLG              varchar(1),
  MARDCFLG              varchar(1),
  MATNR                 varchar(18),
  WERKS                 varchar(4),
  RGEKZ                 varchar(1),
  ZZCIFK                varchar(1),
  BESKZ                 varchar(1),
  SOBSL                 varchar(2),
  STRGR                 varchar(2),
  ZZBSAR                varchar(2),
  DZEIT                 decimal(3),
  PLIFZ                 decimal(3),
  DISPO                 varchar(3),
  EKGRP                 varchar(3),
  PRCTR                 varchar(10),
  MTVFP                 varchar(2),
  ZZACSN                varchar(25),
  LVORM                 varchar(1),
  ZZRMA                 varchar(1),
  ZZCTOG                varchar(3),
  ZZREVL                varchar(10),
  ZZMFG                 varchar(15),
  ZZFCC                 varchar(18),
  ZZLIFS                varchar(2),
  ZZCKD                 varchar(1),
  ZZALC                 varchar(12),
  ZZPPID                varchar(1),
  ZZTECO                varchar(100),
  ZZORCO                varchar(35),
  NCOST                 varchar(1),
  ZZHTC                 varchar(20),
  SCHGT                 varchar(1),
  ZZMTFK                varchar(1),
  LGFSB                 varchar(4),
  MMSTA                 varchar(2),
  ZZBDFLG               varchar(2),
  ZZCTBA                varchar(1),
  ZZDISP                varchar(1),
  ZZSERMODE             varchar(2),
  LGPRO                 varchar(4),
  ZZCCNO                varchar(9),
  DISLS                 varchar(2),
  BSTMI                 decimal(13,3), -- QUAN
  BSTMA                 decimal(13,3), -- QUAN
  AUSSS                 decimal(5,2),
  WEBAZ                 decimal(3),
  EISBE                 text, -- QUAN
  SHFLG                 varchar(1),
  SHZET                 numeric,
  VRMOD                 varchar(1),
  VINT1                 numeric,
  VINT2                 numeric,
  STDPD                 varchar(18),
  KAUSF                 decimal(5,2),
  AHDIS                 varchar(1),
  PRIMARY KEY(MATNR, WERKS)
);
CREATE INDEX idx_marc_zzbsar ON wiprocurement.marc(zzbsar);
CREATE INDEX idx_MARC_MATNR ON wiprocurement.marc(MATNR);
CREATE INDEX IDX_marc_werks ON wiprocurement.marc(werks);


CREATE TABLE IF NOT EXISTS wiprocurement.mdma (
  DATACFLG              varchar(1),
  MATNR                 varchar(18),
  BERID                 varchar(10),
  WERKS                 varchar(4),
  DISMM                 varchar(2),
  DISPO                 varchar(3),
  DISGR                 varchar(4),
  SOBSL                 varchar(2),
  PLIFZ                 decimal(3),
  LOEKZ                 varchar(1),
  PRIMARY KEY(MATNR, BERID)
);

CREATE TABLE IF NOT EXISTS wiprocurement.mard (
  DATACFLG              varchar(1),
  MATNR                 varchar(18),
  WERKS                 varchar(4),
  LGORT                 varchar(4),
  DISKZ                 varchar(1),
  LGPBE                 varchar(10),
  ZZKPCO                varchar(3),
  ZZNET                 varchar(1),
  ZZLSTPSTDT            date,
  LVORM                 varchar(1),
  PRIMARY KEY(MATNR, WERKS, LGORT)
);

CREATE TABLE IF NOT EXISTS wiprocurement.mvke (
  DATACFLG              varchar(1),
  MATNR                 varchar(18),
  VKORG                 varchar(4),
  VTWEG                 varchar(2),
  LVORM                 varchar(1),
  PRIMARY KEY(MATNR, VKORG, VTWEG)
);