CREATE TABLE IF NOT EXISTS wiprocurement.mrp_bw (
  PLANT                text,
  ZDSDAT               text,
  MAT_PLANT            text,
  ZBKDATE              text,
  ZMRP_FOH             text,
  ZMRP_TREQ            text,
  ZMRP_NREQ            text,
  MRP13                text,
  MRP15                text,
  ZMRP_OPPO            text,
  MRP01                text,
  MRP02                text,
  MRP03                text,
  MRP04                text,
  MRP05                text,
  MRP06                text,
  MRP07                text,
  MRP08                text,
  MRP09                text,
  MRP10                text,
  MRP11                text,
  MRP12                text,
  ZWUSE_P              text,
  BASE_UOM             text,
  PRIMARY KEY(PLANT, ZDSDAT, MAT_PLANT)
);