CREATE TABLE IF NOT EXISTS wiprocurement.All_PMPRJTBL_FOR_DASHBOARD
(
  ProjectName          VARCHAR(100),
  ACRPRJNAME           VARCHAR(100),
  Superseded           VARCHAR(1),
  CUSNICKNAME          VARCHAR(100),
  ProfitCenter         VARCHAR(100),
  PROJECTLEADER        VARCHAR(100),
  PrjCreationDate      timestamp without time zone,
  PrjLastUpdate        timestamp without time zone,
  Sequence             VARCHAR(5),
  Creator              VARCHAR(100),
  PrjSchCreationDate   timestamp without time zone,
  BusinessType         VARCHAR(10),
  ProjectStatus        VARCHAR(10),
  WarrantyYear         integer,
  C0DueDate            timestamp with time zone,
  C1DueDate            timestamp with time zone,
  C2DueDate            timestamp with time zone,
  C3DueDate            timestamp with time zone,
  C4DueDate            timestamp with time zone,
  C5DueDate            timestamp with time zone,
  C6DueDate            timestamp with time zone,
  ProjectionC0DueDate  timestamp with time zone,
  ProjectionC1DueDate  timestamp with time zone,
  ProjectionC2DueDate  timestamp with time zone,
  ProjectionC3DueDate  timestamp with time zone,
  ProjectionC4DueDate  timestamp with time zone,
  ProjectionC5DueDate  timestamp with time zone,
  ProjectionC6DueDate  timestamp with time zone,
  ActualC0DueDate      timestamp with time zone,
  ActualC1DueDate      timestamp with time zone,
  ActualC2DueDate      timestamp with time zone,
  ActualC3DueDate      timestamp with time zone,
  ActualC4DueDate      timestamp with time zone,
  ActualC5DueDate      timestamp with time zone,
  ActualC6DueDate      timestamp with time zone,
  RFQCODE              VARCHAR(16),
  GROUPPROJECTCODE     VARCHAR(16),
  CUSTOMERTYPE         VARCHAR(16),
  PROJECTNAMESIMPLE    VARCHAR(10),
  isRFQ                VARCHAR(1),
  ProductType          VARCHAR(100),
  BUDGETPM             VARCHAR(100),
  CLASSIFICATION       VARCHAR(1),
  PlantCode            VARCHAR(1000),
  PRIMARY KEY (ProjectName)
);

CREATE TABLE IF NOT EXISTS wiprocurement.pdmparts
(
  PartNumber      Varchar(18),
  Revision        Varchar(3),
  Sequence        Varchar(5),
  LifeCycleState  Varchar(12),
  Blocked         Varchar(1),
  serno           integer,
  PRIMARY KEY (PartNumber)
);