CREATE TABLE IF NOT EXISTS wiprocurement.ekko (
  ZCRTDAT              date,
  ZCRTTIM              varchar(9),
  DATACFLG             varchar(1),
  EKPACFLG             varchar(1),
  EKPOCFLG             varchar(1),
  EBELN                varchar(10),
  MANDT                text,
  BUKRS                varchar(4),
  BSTYP                varchar(1),
  BSART                varchar(4),
  BSAKZ                varchar(1),
  LOEKZ                varchar(1),
  STATU                varchar(1),
  AEDAT                date,
  ERNAM                varchar(12),
  PINCR                numeric,
  LPONR                numeric,
  LIFNR                varchar(10),
  SPRAS                text,
  ZTERM                varchar(4),
  ZBD1T                decimal(3),
  ZBD2T                decimal(3),
  ZBD3T                decimal(3),
  ZBD1P                decimal(5,3),
  ZBD2P                decimal(5,3),
  EKORG                varchar(4),
  EKGRP                varchar(3),
  WAERS                text,
  WKURS                decimal(9,5),
  KUFIX                varchar(1),
  BEDAT                date,
  KDATB                date,
  KDATE                date,
  IHREZ                varchar(12),
  LLIEF                varchar(10),
  KUNNR                varchar(10),
  ZZSUPWERKS           varchar(4),
  INCO1                varchar(3),
  INCO2                varchar(28),
  KTWRT                decimal(15,2),
  KNUMV                varchar(10),
  KALSM                varchar(6),
  UNSEZ                varchar(12),
  ABSGR                numeric,
  ZZCSVD               varchar(10),
  ZZCSVN               varchar(35),
  ZZRENC               varchar(3),
  ZZREND               varchar(40),
  ZZHUBID              varchar(20),
  ZZKUNRE              varchar(10),
  ZZVSBED              varchar(2),
  ZZINCO1              varchar(3),
  ZZINCO2              varchar(28),
  ZZZTERM              varchar(4),
  ZZTERDC              varchar(50),
  ZZFORD               varchar(10),
  ZZSHIY               varchar(2),
  ZZLGORT              varchar(4),
  ZPRLK                varchar(1),
  PRIMARY KEY(EBELN, MANDT)
);
CREATE INDEX IDX_ekko_ebeln ON wiprocurement.ekko(ebeln);


CREATE TABLE IF NOT EXISTS wiprocurement.ekpa (
  DATACFLG             varchar(1),
  EBELN                varchar(10),
  EBELP                numeric,
  EKORG                varchar(4),
  LTSNR                varchar(6),
  WERKS                varchar(4),
  PARVW                varchar(2),
  PARZA                numeric,
  LIFN2                varchar(10),
  PRIMARY KEY(EBELN, EBELP, EKORG)
);

CREATE TABLE IF NOT EXISTS wiprocurement.ekpo (
  DATACFLG             varchar(1),
  EKETCFLG             varchar(1),
  EKESCFLG             varchar(1),
  EBELN                varchar(10),
  EBELP                numeric,
  LOEKZ                varchar(1),
  STATU                varchar(1),
  AEDAT                date,
  TXZ01                varchar(40),
  MATNR                varchar(18),
  EMATN                varchar(18),
  BUKRS                varchar(4),
  ZZRECWERKS           varchar(4),
  LGORT                varchar(4),
  MATKL                varchar(9),
  INFNR                varchar(10),
  KTMNG                text,
  MENGE                text,
  MEINS                text,
  BPRME                text,
  BPUMZ                decimal(5),
  BPUMN                decimal(5),
  UMREZ                decimal(5),
  UMREN                decimal(5),
  NETPR                decimal(13,3),
  PEINH                decimal(13,3),
  WEBAZ                decimal(3),
  MWSKZ                varchar(2),
  INSMK                varchar(1),
  SPINF                varchar(1),
  ELIKZ                varchar(1),
  PSTYP                varchar(1),
  KNTTP                varchar(1),
  WEPOS                varchar(1),
  REPOS                varchar(1),
  WEBRE                varchar(1),
  LMEIN                text,
  EVERS                varchar(2),
  PRDAT                date,
  BSTYP                varchar(1),
  PLIFZ                decimal(3),
  NTGEW                decimal(13,3),
  GEWEI                text,
  SOBKZ                varchar(1),
  SSQSS                varchar(8),
  BSTAE                varchar(4),
  KO_PRCTR             varchar(10),
  INCO1                varchar(3),
  INCO2                varchar(28),
  BANFN                varchar(10),
  BNFPO                numeric,
  MTART                varchar(4),
  RETPO                varchar(1),
  LFRET                varchar(4),
  MPROF                varchar(4),
  MFRPN                varchar(40),
  MFRNR                varchar(10),
  BERID                varchar(10),
  ZZREFB               varchar(50),
  ZZETD                date,
  ZZMRO_MAT            varchar(18),
  ZZMRO_QTY            decimal(13,3),
  ZZMRO_UNIT           text,
  ZZREPRI              decimal(13,3),
  ZZWAERS              text,
  ZZCASH               varchar(100),
  ZMEPRF               varchar(2),
  ZZTERM               varchar(4),
  ZREGION              varchar(10),
  LPRIO                numeric,
  ZZRMANO              varchar(30),
  ZZPOSEX              varchar(6),
  ZZRTVAG              varchar(2),
  PRIMARY KEY(EBELN, EBELP)
);
CREATE INDEX idx_ekpo_infnr ON wiprocurement.ekpo (infnr);
CREATE INDEX IDX_ekpo_ebeln ON wiprocurement.ekpo(ebeln);
CREATE INDEX IDX_ekpo_ebelp ON wiprocurement.ekpo(ebelp);
CREATE INDEX IDX_ekpo_mfrnr ON wiprocurement.ekpo(mfrnr);

CREATE TABLE IF NOT EXISTS wiprocurement.eket (
  DATACFLG             varchar(1),
  EBELN                varchar(10),
  EBELP                numeric,
  ETENR                numeric,
  EINDT                date,
  LPEIN                varchar(1),
  MENGE                decimal(13,3),
  WEMNG                decimal(13,3),
  WAMNG                decimal(13,3),
  PRIMARY KEY(EBELN, EBELP, ETENR)
);

CREATE TABLE IF NOT EXISTS wiprocurement.ekes (
  DATACFLG             varchar(1),
  EBELN                varchar(10),
  EBELP                numeric,
  ETENS                numeric,
  EBTYP                varchar(2),
  EINDT                date,
  MENGE                decimal(13,3),
  DABMG                decimal(13,3),
  XBLNR                varchar(35),
  VBELN                varchar(10),
  VBELP                numeric,
  ZIMPORT_TYPE         varchar(10),
  ZXDOCK_FLAG          varchar(1),
  ZTRAN_METHOD         varchar(2),
  PRIMARY KEY(EBELN, EBELP, ETENS)
);