CREATE TABLE IF NOT EXISTS wiprocurement.lfa1 (
  TIMESTAMP             timestamp,
  ZMODE                 text,
  MANDT                 text, --client ex:888
  LIFNR                 varchar(10),
  TELF1                 varchar(30),
  REMARK                varchar(50),
  TELFX                 varchar(31),
  STCEG                 varchar(20),
  KTOKK                 varchar(4),
  LOEVM                 varchar(1),
  LAND1                 varchar(3),
  ORT01                 varchar(35),
  NAME1                 varchar(40),
  NAME2                 varchar(40),
  NAME3                 varchar(40),
  NAME4                 varchar(40),
  POST_CODE1            varchar(10),
  HOUSE_NUM1            varchar(10),
  STREET                varchar(60),
  STR_SUPPL1            varchar(40),
  STR_SUPPL2            varchar(40),
  STR_SUPPL3            varchar(40),
  ERDAT                 date,
  ERNAM                 varchar(12),
  KUNNR                 varchar(10),
  SPERR                 varchar(1),
  SPERM                 varchar(1),
  UPDAT                 date,
  UPTIM                 time,
  NODEL                 varchar(1),
  SORT1                 varchar(20),
  SORT2                 varchar(20),
  VBUND                 varchar(6),
  SMTP_ADDR             varchar(241),
  ADRNR                 varchar(10),
  primary key(MANDT, LIFNR)
);
CREATE INDEX IDX_lfa1_lifnr ON wiprocurement.lfa1(lifnr);
