module.exports = {
  "importFile": "F201908160184_ASIC+Conn.xlsx",
  "importDate": "20191210 03:59",
  "unit": "USD",
  "spaDataForSheet": [
    {
      "key": "071.02043.0003",
      "data": [
      {
          "wistronPN": "071.02043.0003",
          "spaPartNumber": "071.02043.0003",
          "spaDescription": "IC MULT/DEMU CBTL02043ABQ,115 DHVQFN 20P",
          "spaManufacturer": "NXP",
          "spaVendor": "WPI",
          "spaVendorPN": "CBTL02043ABQ,115",
          "spaSupplyType": "W",
          "spaCurrency": "USD",
          "spaLastPrice": 0.185,
          "spaOriginalCurrency": "USD",
          "spaOriginalPrice": 0.185,
          "spaValidFrom": "20191001",
          "spaMrp": "522,772",
          "spaCmp": "Y",
          "spaObs": "N",
          "spaExp": "N",
          "spec01": "MUX/DEMUX",
          "spec02": "2",
          "spec03": "4",
          "spec04": "PCIE-8.0G",
          "spec05": "PASSIVE",
          "spec06": "CS:<8.25",
          "spec07": "2.5*4.5",
          "spec08": "DHVQFN",
          "spec09": "20",
          "spec10": "NA",
          "spec11": "NA",
          "spec12": "NA",
          "spec13": "NA",
          "spec14": "NA",
          "spec15": "NA",
          "spec16": "-40~85",
          "spec17": "INDUSTRY",
          "spec18": 'ededede',
          "spec19": 'ededd',
          "spec20": "wedwed",
          "spec21": "weweded",
          "spec22": "ererttr",
          "spec23": 'wedwed',
          "spec24": "reterert",
          "spec25": "erterterte",
          "spec26": 'rtrtrtrrtr',
          "spec27": 'errettrrt',
          "spec28": 'erf34f34',
          "spec29": '34r34r',
          "spec30": '34r34r43r'
        }
    ]
  },
    {
      "key": "071.33212.0003",
      "data": [
        {
          "wistronPN": "071.33212.0003",
          "spaPartNumber": "071.33212.0003",
          "spaDescription": "IC PCIE SW PI3PCIE3212ZBE+DAX QFN 20P AU",
          "spaManufacturer": "DIODES",
          "spaVendor": "WTMEC",
          "spaVendorPN": "PI3PCIE3212ZBE+DAX",
          "spaSupplyType": "W",
          "spaCurrency": "USD",
          "spaLastPrice": 0.186,
          "spaOriginalCurrency": "USD",
          "spaOriginalPrice": 0.186,
          "spaValidFrom": "20191001",
          "spaMrp": "267,288",
          "spaCmp": "Y",
          "spaObs": "N",
          "spaExp": "N",
          "spec01": "MUX/DEMUX",
          "spec02": "2",
          "spec03": "4",
          "spec04": "PCIE-8.0G;SATA-6.0G",
          "spec05": "PASSIVE",
          "spec06": "NA",
          "spec07": "2.5*4.5",
          "spec08": "TQFN",
          "spec09": "20",
          "spec10": "MagnaChip",
          "spec11": "180",
          "spec12": "Greatek",
          "spec13": "NA",
          "spec14": "CBTL02043A",
          "spec15": "NA",
          "spec16": "-40~85",
          "spec17": "INDUSTRY",
          "spec18": 'ededede',
          "spec19": 'ededd',
          "spec20": "wedwed",
          "spec21": "weweded",
          "spec22": "ererttr",
          "spec23": 'wedwed',
          "spec24": "reterert",
          "spec25": "erterterte",
          "spec26": 'rtrtrtrrtr',
          "spec27": 'errettrrt',
          "spec28": 'erf34f34',
          "spec29": '34r34r',
          "spec30": '34r34r43r'
        },
        {
          "wistronPN": "071.33212.0003",
          "spaPartNumber": "071.33212.0003",
          "spaDescription": "IC PCIE SW PI3PCIE3212ZBE+DAX QFN 20P AU",
          "spaManufacturer": "DIODES",
          "spaVendor": "TECHMOSA",
          "spaVendorPN": "PI3PCIE3212ZBE+DAX",
          "spaSupplyType": "W",
          "spaCurrency": "USD",
          "spaLastPrice": 0.2,
          "spaOriginalCurrency": "USD",
          "spaOriginalPrice": 0.2,
          "spaValidFrom": "20180701",
          "spaMrp": "267,288",
          "spaCmp": "Y",
          "spaObs": "N",
          "spaExp": "Y",
          "spec01": "MUX/DEMUX",
          "spec02": "2",
          "spec03": "4",
          "spec04": "PCIE-8.0G;SATA-6.0G",
          "spec05": "PASSIVE",
          "spec06": "NA",
          "spec07": "2.5*4.5",
          "spec08": "TQFN",
          "spec09": "20",
          "spec10": "MagnaChip",
          "spec11": "180",
          "spec12": "Greatek",
          "spec13": "NA",
          "spec14": "CBTL02043A",
          "spec15": "NA",
          "spec16": "-40~85",
          "spec17": "INDUSTRY",
          "spec18": 'ededede',
          "spec19": 'ededd',
          "spec20": "wedwed",
          "spec21": "weweded",
          "spec22": "ererttr",
          "spec23": 'wedwed',
          "spec24": "reterert",
          "spec25": "erterterte",
          "spec26": 'rtrtrtrrtr',
          "spec27": 'errettrrt',
          "spec28": 'erf34f34',
          "spec29": '34r34r',
          "spec30": '34r34r43r'
      },
      {
          "wistronPN": "071.33212.0003",
          "spaPartNumber": "071.33212.0003",
          "spaDescription": "IC PCIE SW PI3PCIE3212ZBE+DAX QFN 20P AU",
          "spaManufacturer": "PERICOM",
          "spaVendor": "TECHMOSA",
          "spaVendorPN": "PI3PCIE3212ZBE+DAX",
          "spaSupplyType": "W",
          "spaCurrency": "USD",
          "spaLastPrice": 0.215,
          "spaOriginalCurrency": "USD",
          "spaOriginalPrice": 0.215,
          "spaValidFrom": "20180101",
          "spaMrp": "267,288",
          "spaCmp": "Y",
          "spaObs": "N",
          "spaExp": "Y",
          "spec01": "MUX/DEMUX",
          "spec02": "2",
          "spec03": "4",
          "spec04": "PCIE-8.0G;SATA-6.0G",
          "spec05": "PASSIVE",
          "spec06": "NA",
          "spec07": "2.5*4.5",
          "spec08": "TQFN",
          "spec09": "20",
          "spec10": "MagnaChip",
          "spec11": "180",
          "spec12": "Greatek",
          "spec13": "NA",
          "spec14": "CBTL02043A",
          "spec15": "NA",
          "spec16": "-40~85",
          "spec17": "INDUSTRY",
          "spec18": 'ededede',
          "spec19": 'ededd',
          "spec20": "wedwed",
          "spec21": "weweded",
          "spec22": "ererttr",
          "spec23": 'wedwed',
          "spec24": "reterert",
          "spec25": "erterterte",
          "spec26": 'rtrtrtrrtr',
          "spec27": 'errettrrt',
          "spec28": 'erf34f34',
          "spec29": '34r34r',
          "spec30": '34r34r43r'
        }
      ]
    }
  ],
  "opportunityPN": [
    {
      "no": 1,
      "purGroup": "S73",
      "oemODM": "ODM",
      "wistronPN": "071.02043.0003",
      "description": "IC MULT/DEMU CBTL02043ABQ,115 DHVQFN 20P",
      "vendorName": "WPI",
      "manufacturer": "NXP",
      "vendorPN": "CBTL02043ABQ,115",
      "currency": "USD",
      "price": 0.186,
      "validFrom": "2019Q4Price",
      "typeI": "ASIC",
      "typeII": "PCIE",
      "originalPrice": 0.186,
      "originalCurrency": "USD",
      "exchangeRate": 1,
      "cmp": "Y",
      "supplyType": "A",
      "mrp": "601,495",
      "spaPartNumber": 'wewqewerwe',
      "spaDescription": 'qweqweqweqwe',
      "spaVendor": 'qweqweqweqwe',
      "spaManufacturer": 'qweqweqwe',
      "spaVendorPN": 'qweqwe',
      "spaSupplyType": 'qweqwe',
      "spaMrp": 123123,
      "spaCurrency": 'usd',
      "spaLastPrice": 123123,
      "spaOriginalCurrency": 'sadad',
      "spaOriginalPrice": 123213,
      "spaValidFrom": 'asdasd',
      "spaCmp": 'Y',
      "spaObs": 'N',
      "spaExp": 'Y',
      "altPartNumber": 'asdasd',
      "altDescription": 'asdasd',
      "altVendor": 'asdasd',
      "altManufacturer": 'erferf',
      "altVendorPN": 'ergerg',
      "altSupplyType": 'ergeg',
      "altMrp": 345354,
      "altCurrency": 'erf',
      "altLastPrice": 345345,
      "altOriginalCurrency": 'wer',
      "altOriginalPrice": 423434,
      "altValidFrom": 'sdfsdf',
      "altCmp": 'Y',
      "altObs": 'N',
      "altExp": 'N',
      "suggCmp": 'N',
      "suggObs": 'N',
      "suggExp": 'Y',
      "suggPartNumber": 'qweqwe',
      "suggDescription": 'qweqweqwe',
      "suggLastPrice": 234234,
      "opportunity": "NA",
      "opportunityPercent": "NA",
      "suggInAltGroup": 'werwerwer',
      "suggFrom": null
    },
    {
      "no": 2,
      "purGroup": "S73",
      "oemODM": "ODM",
      "wistronPN": "071.33212.0003",
      "description": "IC PCIE SW PI3PCIE3212ZBE+DAX QFN 20P AU",
      "vendorName": "WTMEC",
      "manufacturer": "DIODES",
      "vendorPN": "PI3PCIE3212ZBE+DAX",
      "currency": "USD",
      "price": 0.187,
      "validFrom": "2019Q4Price",
      "typeI": "ASIC",
      "typeII": "PCIE",
      "originalPrice": 0.187,
      "originalCurrency": "USD",
      "exchangeRate": 1,
      "cmp": "Y",
      "supplyType": "W",
      "mrp": "267,288",
      "spaPartNumber": null,
      "spaDescription": null,
      "spaVendor": null,
      "spaManufacturer": null,
      "spaVendorPN": null,
      "spaSupplyType": null,
      "spaMrp": null,
      "spaCurrency": null,
      "spaLastPrice": null,
      "spaOriginalCurrency": null,
      "spaOriginalPrice": null,
      "spaValidFrom": null,
      "spaCmp": null,
      "spaObs": null,
      "spaExp": null,
      "altPartNumber": null,
      "altDescription": null,
      "altVendor": null,
      "altManufacturer": null,
      "altVendorPN": null,
      "altSupplyType": null,
      "altMrp": null,
      "altCurrency": null,
      "altLastPrice": null,
      "altOriginalCurrency": null,
      "altOriginalPrice": null,
      "altValidFrom": null,
      "altCmp": null,
      "altObs": null,
      "altExp": null,
      "suggCmp": null,
      "suggObs": null,
      "suggExp": null,
      "suggPartNumber": null,
      "suggDescription": null,
      "suggLastPrice": null,
      "opportunity": "NA",
      "opportunityPercent": "NA",
      "suggInAltGroup": null,
      "suggFrom": null
    }
  ],
  "summaryByType": {
    "ODM": {
      "type1Cost": {
        "ASIC": {
          "subItems": [
            {
              "type1": "ASIC",
              "type2": "PCIE",
              "lastPrice": 0.373,
              "suggestionCost": 0,
              "opportunity": 0.373,
              "opportunityPercent": "1%"
            }
          ],
          "subTotalCost": {
            "lastPrice": 0.111,
            "suggestionCost": 0,
            "opportunity": 0.111,
            "opportunityPercent": "1212%"
          }
        },
        "BBB": {
          "subItems": [
            {
              "type1": "BBB",
              "type2": "SMD",
              "lastPrice": 0.23,
              "suggestionCost": 0,
              "opportunity": 0.433,
              "opportunityPercent": "1%"
            },
            {
              "type1": "BBB",
              "type2": "DIP",
              "lastPrice": 0.776,
              "suggestionCost": 0,
              "opportunity": 0.111,
              "opportunityPercent": "1%"
            }
          ],
          "subTotalCost": {
            "lastPrice": 0.746,
            "suggestionCost": 0,
            "opportunity": 0.746,
            "opportunityPercent": "2%"
          }
        },
      },
      "type1TotalCost": {
        "lastPrice": 0.373,
        "suggestionCost": 0,
        "opportunity": 0.373,
        "opportunityPercent": "1%"
      }
    },
    "OEM": {
    },
  },
  "summaryByVendor": {
    "ODM": {
      "type1Cost": {
        "ASIC": {
          "subItems": [
            {
              "manufacturer": "DIODES",
              "vendorName": "WTMEC",
              "lastPrice": 0.187,
              "suggestionCost": 0,
              "opportunity": 0.187,
              "opportunityPercent": "1%"
            },
            {
              "manufacturer": "NXP",
              "vendorName": "WPI",
              "lastPrice": 0.186,
              "suggestionCost": 0,
              "opportunity": 0.186,
              "opportunityPercent": "1%"
            }
          ],
          "subTotalCost": {

            "lastPrice": 0.334,
            "suggestionCost": 0,
            "opportunity": 0.555,
            "opportunityPercent": "222%"
          }
        }
      
      },
      "type1TotalCost": {
        "lastPrice": 0.373,
        "suggestionCost": 0,
        "opportunity": 0.373,
        "opportunityPercent": "1%"
      }
    },
    "OEM": {}
  },
  "exchangeRate": [],
  "exchangeRateDefault": [
    {
        
      "exchange_rate": null,
      "RMB": 0.143,
    },
    {
        
      "exchange_rate": null,
      "NTD": 0.033,
    },
    {
        
      "exchange_rate": null,
      "JPY": 0.009,
    }
  ],

}