export const DEFAULT_ME_LENGTH = 4;
export const DEFAULT_FUNCTION_TEAM_LENGTH = 2;
export const MAX_ME_LENGTH = 10;
export const MAX_FUNCTION_TEAM_LENGTH = 10;

export default {
  DEFAULT_ME_LENGTH,
  DEFAULT_FUNCTION_TEAM_LENGTH,
  MAX_ME_LENGTH,
  MAX_FUNCTION_TEAM_LENGTH,
};
