# 外觀印刷-(幾道) 下拉選單
values:
  - rubberPrintingAmount: 0
  - rubberPrintingAmount: 1
  - rubberPrintingAmount: 2
  - rubberPrintingAmount: 3
  - rubberPrintingAmount: 4
  - rubberPrintingAmount: 5
  - rubberPrintingAmount: 6
  - rubberPrintingAmount: 7
