ALTER TABLE wiprocurement.plant_list
ADD COLUMN IF NOT EXISTS plant_desc character varying,
ADD COLUMN IF NOT EXISTS purchase_org character varying;

INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F021','WPH','PWPH') on conflict (plant) DO UPDATE SET plant_desc='WPH', purchase_org='PWPH';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F022','WPH CSD','P022') on conflict (plant) DO UPDATE SET plant_desc='WPH CSD', purchase_org='P022';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F024','WPH Service W/H','PCSD') on conflict (plant) DO UPDATE SET plant_desc='WPH Service W/H', purchase_org='PCSD';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F032','WTX CSD','P032') on conflict (plant) DO UPDATE SET plant_desc='WTX CSD', purchase_org='P032';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F034','WTX Service W/H','P032') on conflict (plant) DO UPDATE SET plant_desc='WTX Service W/H', purchase_org='P032';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F035','WTX Service TPM','P032') on conflict (plant) DO UPDATE SET plant_desc='WTX Service TPM', purchase_org='P032';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F040','WSCQ SBU plant',null) on conflict (plant) DO UPDATE SET plant_desc='WSCQ SBU plant', purchase_org=null;
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F050','WBR SBU plant',null) on conflict (plant) DO UPDATE SET plant_desc='WBR SBU plant', purchase_org=null;
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F070','WSMX SBU plant',null) on conflict (plant) DO UPDATE SET plant_desc='WSMX SBU plant', purchase_org=null;
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F080','WSCO SBU Plant',null) on conflict (plant) DO UPDATE SET plant_desc='WSCO SBU Plant', purchase_org=null;
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F091','WSCZ SBU plant','P091') on conflict (plant) DO UPDATE SET plant_desc='WSCZ SBU plant', purchase_org='P091';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F094',null,null) on conflict (plant) DO UPDATE SET plant_desc=null, purchase_org=null;
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F0B1','WPH','PWPH') on conflict (plant) DO UPDATE SET plant_desc='WPH', purchase_org='PWPH';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F100','WJP CSD','P100') on conflict (plant) DO UPDATE SET plant_desc='WJP CSD', purchase_org='P100';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F104','WJP Service W/H','P100') on conflict (plant) DO UPDATE SET plant_desc='WJP Service W/H', purchase_org='P100';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F109','Hub','PWJP') on conflict (plant) DO UPDATE SET plant_desc='Hub', purchase_org='PWJP';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F110','WTZS','PWTH') on conflict (plant) DO UPDATE SET plant_desc='WTZS', purchase_org='PWTH';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F111','Astro SV China Plant',null) on conflict (plant) DO UPDATE SET plant_desc='Astro SV China Plant', purchase_org=null;
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F120','AIIH Hub','PIIH') on conflict (plant) DO UPDATE SET plant_desc='AIIH Hub', purchase_org='PIIH';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F12B','AIIH Hub-A','PIIB') on conflict (plant) DO UPDATE SET plant_desc='AIIH Hub-A', purchase_org='PIIB';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F130','WZS Plant 3B','PWZS') on conflict (plant) DO UPDATE SET plant_desc='WZS Plant 3B', purchase_org='PWZS';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F131','WZS Plant 3A','PWZS') on conflict (plant) DO UPDATE SET plant_desc='WZS Plant 3A', purchase_org='PWZS';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F132','WZS-6 (TV)','PWZS') on conflict (plant) DO UPDATE SET plant_desc='WZS-6 (TV)', purchase_org='PWZS';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F133','WZS SBU Plant','P133') on conflict (plant) DO UPDATE SET plant_desc='WZS SBU Plant', purchase_org='P133';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F135','WZS-3','PWZS') on conflict (plant) DO UPDATE SET plant_desc='WZS-3', purchase_org='PWZS';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F136','WZS Plant 1B','PWZS') on conflict (plant) DO UPDATE SET plant_desc='WZS Plant 1B', purchase_org='PWZS';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F137','WZS Plant 1A','PWZS') on conflict (plant) DO UPDATE SET plant_desc='WZS Plant 1A', purchase_org='PWZS';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F138','WZS-6 (MNT)','PWZS') on conflict (plant) DO UPDATE SET plant_desc='WZS-6 (MNT)', purchase_org='PWZS';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F139','WZS-8','PWZA') on conflict (plant) DO UPDATE SET plant_desc='WZS-8', purchase_org='PWZA';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F13H','WZS Hub plant','PWZH') on conflict (plant) DO UPDATE SET plant_desc='WZS Hub plant', purchase_org='PWZH';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F140','WMX non-MFG','PWMX') on conflict (plant) DO UPDATE SET plant_desc='WMX non-MFG', purchase_org='PWMX';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F145','WMX DBG DPBU TV','PWMM') on conflict (plant) DO UPDATE SET plant_desc='WMX DBG DPBU TV', purchase_org='PWMM';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F190','ATZS Plant 1','PTZS') on conflict (plant) DO UPDATE SET plant_desc='ATZS Plant 1', purchase_org='PTZS';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F191','ATZS Plant 5 - LCD TV','PTZS') on conflict (plant) DO UPDATE SET plant_desc='ATZS Plant 5 - LCD TV', purchase_org='PTZS';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F192','ATZS Plant 6','PATZ') on conflict (plant) DO UPDATE SET plant_desc='ATZS Plant 6', purchase_org='PATZ';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F193','ATZS CSD','P193') on conflict (plant) DO UPDATE SET plant_desc='ATZS CSD', purchase_org='P193';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F195','ATZS Plant 6 - LCM','PATZ') on conflict (plant) DO UPDATE SET plant_desc='ATZS Plant 6 - LCM', purchase_org='PATZ';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F199','Astro SV China Hub.','PTZH') on conflict (plant) DO UPDATE SET plant_desc='Astro SV China Hub.', purchase_org='PTZH';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F230','WKS Lily NB','PWKS') on conflict (plant) DO UPDATE SET plant_desc='WKS Lily NB', purchase_org='PWKS';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F232','WKS-5','PWKS') on conflict (plant) DO UPDATE SET plant_desc='WKS-5', purchase_org='PWKS';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F261','WTZ 2A&2C','PWTZ') on conflict (plant) DO UPDATE SET plant_desc='WTZ 2A&2C', purchase_org='PWTZ';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F262','WTZ 2D','PWTZ') on conflict (plant) DO UPDATE SET plant_desc='WTZ 2D', purchase_org='PWTZ';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F265','WTZ TP','PWTZ') on conflict (plant) DO UPDATE SET plant_desc='WTZ TP', purchase_org='PWTZ';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F266','F266','PWTZ') on conflict (plant) DO UPDATE SET plant_desc='F266', purchase_org='PWTZ';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F271','WSE CSD','P271') on conflict (plant) DO UPDATE SET plant_desc='WSE CSD', purchase_org='P271';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F274','WSE Service W/H','P271') on conflict (plant) DO UPDATE SET plant_desc='WSE Service W/H', purchase_org='P271';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F290','WVS HUB Plant','PWVS') on conflict (plant) DO UPDATE SET plant_desc='WVS HUB Plant', purchase_org='PWVS';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F291','WVS ATZS Plant','PWVS') on conflict (plant) DO UPDATE SET plant_desc='WVS ATZS Plant', purchase_org='PWVS';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F292','WVS SJ Plant','PWSJ') on conflict (plant) DO UPDATE SET plant_desc='WVS SJ Plant', purchase_org='PWSJ';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F293','WVS CSD Plant','P293') on conflict (plant) DO UPDATE SET plant_desc='WVS CSD Plant', purchase_org='P293';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F310','WKS Astro NB','PWKS') on conflict (plant) DO UPDATE SET plant_desc='WKS Astro NB', purchase_org='PWKS';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F311','WKS-2','PWKS') on conflict (plant) DO UPDATE SET plant_desc='WKS-2', purchase_org='PWKS';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F330','WKS Annie NB','PWKS') on conflict (plant) DO UPDATE SET plant_desc='WKS Annie NB', purchase_org='PWKS';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F331','WKS Rosa NB','PWKS') on conflict (plant) DO UPDATE SET plant_desc='WKS Rosa NB', purchase_org='PWKS';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F332','WKS 5A','PWKS') on conflict (plant) DO UPDATE SET plant_desc='WKS 5A', purchase_org='PWKS';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F335','WKS 5B','PWKS') on conflict (plant) DO UPDATE SET plant_desc='WKS 5B', purchase_org='PWKS';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F336','WKS Rama','PWKS') on conflict (plant) DO UPDATE SET plant_desc='WKS Rama', purchase_org='PWKS';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F337','WKS-3','PWKA') on conflict (plant) DO UPDATE SET plant_desc='WKS-3', purchase_org='PWKA';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F338','WKS-3','PWKP') on conflict (plant) DO UPDATE SET plant_desc='WKS-3', purchase_org='PWKP';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F33A','WKS-3','PWKP') on conflict (plant) DO UPDATE SET plant_desc='WKS-3', purchase_org='PWKP';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F350','WSKS CSD','P350') on conflict (plant) DO UPDATE SET plant_desc='WSKS CSD', purchase_org='P350';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F354','WSKS Service W/H','PCSD') on conflict (plant) DO UPDATE SET plant_desc='WSKS Service W/H', purchase_org='PCSD';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F360','WHK CSD',null) on conflict (plant) DO UPDATE SET plant_desc='WHK CSD', purchase_org=null;
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F370','WSS CSD','P370') on conflict (plant) DO UPDATE SET plant_desc='WSS CSD', purchase_org='P370';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F374','WSS Service W/H',null) on conflict (plant) DO UPDATE SET plant_desc='WSS Service W/H', purchase_org=null;
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F520','WCZ Hub','PWCH') on conflict (plant) DO UPDATE SET plant_desc='WCZ Hub', purchase_org='PWCH';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F521','WCZ Server plant','PWCZ') on conflict (plant) DO UPDATE SET plant_desc='WCZ Server plant', purchase_org='PWCZ';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F522','WCZ DABU MFG Plant','PWCZ') on conflict (plant) DO UPDATE SET plant_desc='WCZ DABU MFG Plant', purchase_org='PWCZ';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F523','WCZ CSD Plant','P523') on conflict (plant) DO UPDATE SET plant_desc='WCZ CSD Plant', purchase_org='P523';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F524','WCZ Service Plant',null) on conflict (plant) DO UPDATE SET plant_desc='WCZ Service Plant', purchase_org=null;
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F525','WCZ DPBU MFG Plant','PWCZ') on conflict (plant) DO UPDATE SET plant_desc='WCZ DPBU MFG Plant', purchase_org='PWCZ';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F550','US Hub','PWIT') on conflict (plant) DO UPDATE SET plant_desc='US Hub', purchase_org='PWIT';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F551','WMX Plant I','PWMX') on conflict (plant) DO UPDATE SET plant_desc='WMX Plant I', purchase_org='PWMX';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F552','WMX Plant II','PWMX') on conflict (plant) DO UPDATE SET plant_desc='WMX Plant II', purchase_org='PWMX';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F555','WMX Plant II','PWMX') on conflict (plant) DO UPDATE SET plant_desc='WMX Plant II', purchase_org='PWMX';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F556','Rosa CTO','PWMX') on conflict (plant) DO UPDATE SET plant_desc='Rosa CTO', purchase_org='PWMX';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F559','WMX EMS Plant','PWMX') on conflict (plant) DO UPDATE SET plant_desc='WMX EMS Plant', purchase_org='PWMX';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F560','WSG CSD Plant','P560') on conflict (plant) DO UPDATE SET plant_desc='WSG CSD Plant', purchase_org='P560';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F564','WSG Service W/H Plant',null) on conflict (plant) DO UPDATE SET plant_desc='WSG Service W/H Plant', purchase_org=null;
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F590','WIN BANGALORE','P590') on conflict (plant) DO UPDATE SET plant_desc='WIN BANGALORE', purchase_org='P590';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F591','CSD','P590') on conflict (plant) DO UPDATE SET plant_desc='CSD', purchase_org='P590';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F592','CSD','P590') on conflict (plant) DO UPDATE SET plant_desc='CSD', purchase_org='P590';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F593','CSD','P590') on conflict (plant) DO UPDATE SET plant_desc='CSD', purchase_org='P590';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F594','CSD','P590') on conflict (plant) DO UPDATE SET plant_desc='CSD', purchase_org='P590';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F596','WMI','PWMI') on conflict (plant) DO UPDATE SET plant_desc='WMI', purchase_org='PWMI';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F598','ICT Service Management','PWIN') on conflict (plant) DO UPDATE SET plant_desc='ICT Service Management', purchase_org='PWIN';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F599','CSD','P590') on conflict (plant) DO UPDATE SET plant_desc='CSD', purchase_org='P590';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F59A','India Hub Plant','PWIA') on conflict (plant) DO UPDATE SET plant_desc='India Hub Plant', purchase_org='PWIA';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F600','WHQ Hub','PWHQ') on conflict (plant) DO UPDATE SET plant_desc='WHQ Hub', purchase_org='PWHQ';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F601','WIH','PWIH') on conflict (plant) DO UPDATE SET plant_desc='WIH', purchase_org='PWIH';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F602','WIH-2','PWIH') on conflict (plant) DO UPDATE SET plant_desc='WIH-2', purchase_org='PWIH';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F603','WIH CSD','P603') on conflict (plant) DO UPDATE SET plant_desc='WIH CSD', purchase_org='P603';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F604','WIH Service W/H','PCSD') on conflict (plant) DO UPDATE SET plant_desc='WIH Service W/H', purchase_org='PCSD';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F605','WMX Plant II','PWMX') on conflict (plant) DO UPDATE SET plant_desc='WMX Plant II', purchase_org='PWMX';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F606','WMX Plant I','PWMX') on conflict (plant) DO UPDATE SET plant_desc='WMX Plant I', purchase_org='PWMX';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F607','WMX CSD','PCSD') on conflict (plant) DO UPDATE SET plant_desc='WMX CSD', purchase_org='PCSD';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F609','WIH MNT','PWIH') on conflict (plant) DO UPDATE SET plant_desc='WIH MNT', purchase_org='PWIH';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F60A','WHQ Hub(Allie)','PWHA') on conflict (plant) DO UPDATE SET plant_desc='WHQ Hub(Allie)', purchase_org='PWHA';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F610','WHU Hub','PWHU') on conflict (plant) DO UPDATE SET plant_desc='WHU Hub', purchase_org='PWHU';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F6D0','WMT Hub Plant','PMHQ') on conflict (plant) DO UPDATE SET plant_desc='WMT Hub Plant', purchase_org='PMHQ';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F6D1','WMT','PMTW') on conflict (plant) DO UPDATE SET plant_desc='WMT', purchase_org='PMTW';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F6F0','BTA','PMSG') on conflict (plant) DO UPDATE SET plant_desc='BTA', purchase_org='PMSG';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F711','WCQ-1','PWCQ') on conflict (plant) DO UPDATE SET plant_desc='WCQ-1', purchase_org='PWCQ';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F712','WCQ-1','PWCQ') on conflict (plant) DO UPDATE SET plant_desc='WCQ-1', purchase_org='PWCQ';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F715','WCQ-1','PWCQ') on conflict (plant) DO UPDATE SET plant_desc='WCQ-1', purchase_org='PWCQ';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F721','WCD','PWCD') on conflict (plant) DO UPDATE SET plant_desc='WCD', purchase_org='PWCD';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F722','WCD','PWCD') on conflict (plant) DO UPDATE SET plant_desc='WCD', purchase_org='PWCD';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F725','WCD-DOA','PWCD') on conflict (plant) DO UPDATE SET plant_desc='WCD-DOA', purchase_org='PWCD';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F741','WOK','PWOK') on conflict (plant) DO UPDATE SET plant_desc='WOK', purchase_org='PWOK';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F781','WQD TV','PWQD') on conflict (plant) DO UPDATE SET plant_desc='WQD TV', purchase_org='PWQD';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F7A1','Medical Tech(CQ)','PMCQ') on conflict (plant) DO UPDATE SET plant_desc='Medical Tech(CQ)', purchase_org='PMCQ';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F820','WCKS SBU plant','P820') on conflict (plant) DO UPDATE SET plant_desc='WCKS SBU plant', purchase_org='P820';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F830','WCCN SBU plant','P830') on conflict (plant) DO UPDATE SET plant_desc='WCCN SBU plant', purchase_org='P830';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F840','WCLX SBU plant','P840') on conflict (plant) DO UPDATE SET plant_desc='WCLX SBU plant', purchase_org='P840';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F900','WYHQ','PYHQ') on conflict (plant) DO UPDATE SET plant_desc='WYHQ', purchase_org='PYHQ';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F910','WYUDE','PYU1') on conflict (plant) DO UPDATE SET plant_desc='WYUDE', purchase_org='PYU1';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F912','WYUDE at MX','PYMX') on conflict (plant) DO UPDATE SET plant_desc='WYUDE at MX', purchase_org='PYMX';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F930','WYJP','PYJP') on conflict (plant) DO UPDATE SET plant_desc='WYJP', purchase_org='PYJP';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F940','WYKR','PYKR') on conflict (plant) DO UPDATE SET plant_desc='WYKR', purchase_org='PYKR';
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F999','Non-Valued Plant',null) on conflict (plant) DO UPDATE SET plant_desc='Non-Valued Plant', purchase_org=null;
INSERT INTO wiprocurement.plant_list (plant,plant_desc,purchase_org) values ('F9C1','WYTN','PYTN') on conflict (plant) DO UPDATE SET plant_desc='WYTN', purchase_org='PYTN';
