--delete from formula.parameter_value where parameter_id in (select id from formula.turning_material tm);
SET search_path TO formula, public, wiprocurement;
drop table if exists turning_nylok;
drop table if exists turning_nylok_color;
drop table if exists turning_nylok_diameter;
drop table if exists turning_nylok_length;
drop table if exists turning_plating;
drop table if exists turning_screw_diameter;
drop table if exists turning_heat_treatment;
drop table if exists turning_material;

CREATE TABLE IF NOT EXISTS turning_material (
	id uuid NOT NULL DEFAULT uuid_generate_v1(),
	part_category_2_id uuid not null,
	material_name varchar(200) not null,
    density numeric not null,
	remark varchar(400) NULL,
	create_time timestamptz NOT null default now(),
	disable_time timestamptz null,
	CONSTRAINT turning_material_pk PRIMARY KEY (id),
	CONSTRAINT turning_material_fk FOREIGN KEY (part_category_2_id) REFERENCES part_category_2(id),
	CONSTRAINT turning_material_un UNIQUE (part_category_2_id, material_name)
);

CREATE TABLE IF NOT EXISTS turning_heat_treatment (
	id uuid NOT NULL DEFAULT uuid_generate_v1(),
	turning_material_id uuid not null,
    remark varchar(400) NULL,
	create_time timestamptz NOT null default now(),
	disable_time timestamptz null,
	CONSTRAINT turning_heat_treatment_pk PRIMARY KEY (id),
    CONSTRAINT turning_heat_treatment_fk FOREIGN KEY (turning_material_id) REFERENCES turning_material(id),
	CONSTRAINT turning_heat_treatment_un UNIQUE (turning_material_id)
);

CREATE TABLE IF NOT EXISTS turning_screw_diameter (
	id uuid NOT NULL DEFAULT uuid_generate_v1(),
	outter_diameter numeric not null,
	inner_diameter numeric not null,
	remark varchar(400) NULL,
	create_time timestamptz NOT null default now(),
	disable_time timestamptz null,
	CONSTRAINT turning_screw_diameter_pk PRIMARY KEY (id),
	CONSTRAINT turning_screw_diameter_un UNIQUE (outter_diameter)
);

CREATE TABLE IF NOT EXISTS turning_plating (
	id uuid NOT NULL DEFAULT uuid_generate_v1(),
	plating_name varchar(200) not null,
	remark varchar(400) NULL,
	create_time timestamptz NOT null default now(),
	disable_time timestamptz null,
	CONSTRAINT turning_plating_pk PRIMARY KEY (id),
	CONSTRAINT turning_plating_un UNIQUE (plating_name)
);

CREATE TABLE IF NOT EXISTS turning_nylok_color (
	id uuid NOT NULL DEFAULT uuid_generate_v1(),
	color_name varchar(200) not null,
	remark varchar(400) NULL,
	create_time timestamptz NOT null default now(),
	disable_time timestamptz null,
	CONSTRAINT turning_nylok_color_pk PRIMARY KEY (id),
	CONSTRAINT turning_nylok_color_un UNIQUE (color_name)
);

CREATE TABLE IF NOT EXISTS turning_nylok_diameter (
	id uuid NOT NULL DEFAULT uuid_generate_v1(),
	diameter_begin numeric not null,
	diameter_end numeric not null,
	remark varchar(400) NULL,
	create_time timestamptz NOT null default now(),
	disable_time timestamptz null,
	CONSTRAINT turning_nylok_diameter_pk PRIMARY KEY (id),
	CONSTRAINT turning_nylok_diameter_un UNIQUE (diameter_begin, diameter_end)
);

CREATE TABLE IF NOT EXISTS turning_nylok_length (
	id uuid NOT NULL DEFAULT uuid_generate_v1(),
	length_begin numeric not null,
	length_end numeric not null,
	remark varchar(400) NULL,
	create_time timestamptz NOT null default now(),
	disable_time timestamptz null,
	CONSTRAINT turning_nylok_length_pk PRIMARY KEY (id),
	CONSTRAINT turning_nylok_length_un UNIQUE (length_begin, length_end)
);

CREATE TABLE IF NOT EXISTS turning_nylok (
	id uuid NOT NULL DEFAULT uuid_generate_v1(),
	material_id uuid not null,
	color_id uuid not null,
	diameter_id uuid not null,
	length_id uuid not null,
	remark varchar(400) NULL,
	create_time timestamptz NOT null default now(),
	disable_time timestamptz null,
	CONSTRAINT turning_nylok_pk PRIMARY KEY (id),
	CONSTRAINT turning_nylok_un UNIQUE (material_id, color_id, diameter_id, length_id),
	CONSTRAINT turning_nylok_fk FOREIGN KEY (material_id) REFERENCES turning_material(id),
	CONSTRAINT turning_nylok_fk1 FOREIGN KEY (color_id) REFERENCES turning_nylok_color(id),
	CONSTRAINT turning_nylok_fk2 FOREIGN KEY (diameter_id) REFERENCES turning_nylok_diameter(id),
	CONSTRAINT turning_nylok_fk3 FOREIGN KEY (length_id) REFERENCES turning_nylok_length(id)
);


delete from formula.parameter_value as pv where activate_date_id in (select id from formula.schedule_date as sd where sd.formula_type_id = (select id from formula.formula_type as ft where ft."name" = 'me_others_screw'));
delete from formula.common_parameter as cp where cp.formula_type_id = (select id from formula.formula_type as ft where ft."name" = 'me_others_screw');
delete from formula.schedule_date as sd where sd.formula_type_id = (select id from formula.formula_type as ft where ft."name" = 'me_others_screw');

--formula_type
INSERT INTO formula.formula_type("name", remark, create_time) VALUES('me_others_screw', null, now()) on conflict do nothing;

--schedule_date
INSERT INTO formula.schedule_date("name", formula_type_id, activate_date, create_time) VALUES('me_others_screw_init', (select id from formula.formula_type where name='me_others_screw'), '1970-01-01', now());

--turning material
INSERT INTO formula.turning_material (part_category_2_id, material_name, density) VALUES((select id from formula.part_category_2 where category_name = 'Screw'), '低碳鋼18A', 7.85 );
INSERT INTO formula.turning_material (part_category_2_id, material_name, density) VALUES((select id from formula.part_category_2 where category_name = 'Screw'), 'SUS410', 7.93 );
INSERT INTO formula.turning_material (part_category_2_id, material_name, density) VALUES((select id from formula.part_category_2 where category_name = 'Screw'), '快削鋼', 7.85 );

--INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((select id from formula.turning_material where material_name = '低碳鋼18A'), (SELECT max(id) FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'material' )) )), 2.14, 'number', 'turning_material', now());
--INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((select id from formula.turning_material where material_name = 'SUS410'), (SELECT max(id) FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'material' )) )), 4.41, 'number', 'turning_material', now());
--INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((select id from formula.turning_material where material_name = '快削鋼'), (SELECT max(id) FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'material' )) )), 2.14, 'number', 'turning_material', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table)
select tm.id, schedule.id, 2.14, 'number', 'turning_material' from formula.turning_material tm, 
(SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'material' )) )) as schedule
where tm.material_name = '低碳鋼18A'
order by tm.id;
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table)
select tm.id, schedule.id, 4.41, 'number', 'turning_material' from formula.turning_material tm, 
(SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'material' )) )) as schedule
where tm.material_name = 'SUS410'
order by tm.id;
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table)
select tm.id, schedule.id, 2.14, 'number', 'turning_material' from formula.turning_material tm, 
(SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'material' )) )) as schedule
where tm.material_name = '快削鋼'
order by tm.id;

--turning heat treatment
INSERT INTO formula.turning_heat_treatment (turning_material_id) VALUES((select id from formula.turning_material where material_name = '低碳鋼18A'));
INSERT INTO formula.turning_heat_treatment (turning_material_id) VALUES((select id from formula.turning_material where material_name = '快削鋼'));
INSERT INTO formula.turning_heat_treatment (turning_material_id) VALUES((select id from formula.turning_material where material_name = 'SUS410'));

INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.turning_heat_treatment WHERE turning_material_id = (select id from formula.turning_material where material_name = '低碳鋼18A')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 0.74, 'number', 'turning_heat_treatment', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.turning_heat_treatment WHERE turning_material_id = (select id from formula.turning_material where material_name = 'SUS410')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 2.65, 'number', 'turning_heat_treatment', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.turning_heat_treatment WHERE turning_material_id = (select id from formula.turning_material where material_name = '快削鋼')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 0.74, 'number', 'turning_heat_treatment', now());

--turning plating
INSERT INTO formula.turning_plating(plating_name) VALUES('鍍黑鋅');
INSERT INTO formula.turning_plating(plating_name) VALUES('鍍白鎳');
INSERT INTO formula.turning_plating(plating_name) VALUES('鍍黑镍');
INSERT INTO formula.turning_plating(plating_name) VALUES('鋅鎳合金');
INSERT INTO formula.turning_plating(plating_name) VALUES('削光鋅鎳合金');
INSERT INTO formula.turning_plating(plating_name) VALUES('電泳ED');
INSERT INTO formula.turning_plating(plating_name) VALUES('PVD');

INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.turning_plating WHERE plating_name = '鍍黑鋅'), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 2.6471, 'number', 'turning_plating', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.turning_plating WHERE plating_name = '鍍白鎳'), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 3.6765, 'number', 'turning_plating', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.turning_plating WHERE plating_name = '鍍黑镍'), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 4.4118, 'number', 'turning_plating', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.turning_plating WHERE plating_name = '鋅鎳合金'), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 5.8824, 'number', 'turning_plating', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.turning_plating WHERE plating_name = '削光鋅鎳合金'), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 8.0882, 'number', 'turning_plating', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.turning_plating WHERE plating_name = '電泳ED'), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 0.0324, 'number', 'turning_plating', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.turning_plating WHERE plating_name = 'PVD'), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 0.0368, 'number', 'turning_plating', now());

--turning screw diameter
INSERT INTO formula.turning_screw_diameter (outter_diameter, inner_diameter) VALUES(1.6, 1.25);
INSERT INTO formula.turning_screw_diameter (outter_diameter, inner_diameter) VALUES(2, 1.6);
INSERT INTO formula.turning_screw_diameter (outter_diameter, inner_diameter) VALUES(2.5, 2.05);
INSERT INTO formula.turning_screw_diameter (outter_diameter, inner_diameter) VALUES(3, 2.5);


--turning parameter
INSERT INTO formula.common_parameter (formula_type_id, part_type, sub_type, label, unit, label_name, system_remark) VALUES ((SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )), 'me_others_screw_management_and_profit', '', 'management_and_profit', '%', '管銷&利潤乘數', '管銷利潤_管銷&利潤乘數');
INSERT INTO formula.common_parameter (formula_type_id, part_type, sub_type, label, unit, label_name, system_remark) VALUES ((SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )), 'me_others_screw_management_and_profit', '', 'nut_management_and_profit', '%', 'NUT 管銷&利潤乘數', '管銷利潤_NUT 管銷&利潤乘數');
INSERT INTO formula.common_parameter (formula_type_id, part_type, sub_type, label, unit, label_name, system_remark) VALUES ((SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )), 'me_others_screw_management_and_profit', '', 'standoff_management_and_profit', '%', 'Standoff 管銷&利潤乘數', '管銷利潤_Standoff 管銷&利潤乘數');
INSERT INTO formula.common_parameter (formula_type_id, part_type, sub_type, label, unit, label_name, system_remark) VALUES ((SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )), 'me_others_screw_molding', '', 'lathe_unit_price', 'USD', '成型加工費用(車修)', '成型費_成型加工費用(車修)');
INSERT INTO formula.common_parameter (formula_type_id, part_type, sub_type, label, unit, label_name, system_remark) VALUES ((SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )), 'me_others_screw_molding', '', 'lathe_capacity', '', '成型費(車修) 一班產能', '成型費_成型費(車修) 一班產能');
INSERT INTO formula.common_parameter (formula_type_id, part_type, sub_type, label, unit, label_name, system_remark) VALUES ((SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )), 'me_others_screw_molding', '', 'lathe_loss_rate', '%', '成型費(車修) Loss Rate', '成型費_成型費(車修) Loss Rate');
INSERT INTO formula.common_parameter (formula_type_id, part_type, sub_type, label, unit, label_name, system_remark) VALUES ((SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )), 'me_others_screw_molding', '', 'tapping_unit_price', 'USD', '成型加工費用(攻牙)', '成型費_成型加工費用(攻牙)');
INSERT INTO formula.common_parameter (formula_type_id, part_type, sub_type, label, unit, label_name, system_remark) VALUES ((SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )), 'me_others_screw_molding', '', 'tapping_capacity', '', '成型費(攻牙) 一班產能', '成型費_成型費(攻牙) 一班產能');
INSERT INTO formula.common_parameter (formula_type_id, part_type, sub_type, label, unit, label_name, system_remark) VALUES ((SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )), 'me_others_screw_molding', '', 'tapping_loss_rate', '%', '成型費(攻牙) Loss Rate', '成型費_成型費(攻牙) Loss Rate');
INSERT INTO formula.common_parameter (formula_type_id, part_type, sub_type, label, unit, label_name, system_remark) VALUES ((SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )), 'me_others_screw_molding', '', 'thread_rolling_unit_price', 'USD', '成型加工費用(冷鍛打頭_搓牙)', '成型費_成型加工費用(冷鍛打頭_搓牙)');
INSERT INTO formula.common_parameter (formula_type_id, part_type, sub_type, label, unit, label_name, system_remark) VALUES ((SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )), 'me_others_screw_molding', '', 'thread_rolling_capacity', '', '成型費(冷鍛打頭_搓牙) 一班產能', '成型費_成型費(冷鍛打頭_搓牙) 一班產能');
INSERT INTO formula.common_parameter (formula_type_id, part_type, sub_type, label, unit, label_name, system_remark) VALUES ((SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )), 'me_others_screw_molding', '', 'thread_rolling_loss_rate', '%', '成型費(冷鍛打頭_搓牙) Loss Rate', '成型費_成型費(冷鍛打頭_搓牙) Loss Rate');
INSERT INTO formula.common_parameter (formula_type_id, part_type, sub_type, label, unit, label_name, system_remark) VALUES ((SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )), 'me_others_screw_molding', '', 'lathe_circularity_unit_price', 'USD', '成型加工費用(車修真圓度)', '成型費_成型加工費用(車修真圓度)');
INSERT INTO formula.common_parameter (formula_type_id, part_type, sub_type, label, unit, label_name, system_remark) VALUES ((SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )), 'me_others_screw_molding', '', 'lathe_circularity_capacity', '', '成型費(車修真圓度) 一班產能', '成型費_成型費(車修真圓度) 一班產能');
INSERT INTO formula.common_parameter (formula_type_id, part_type, sub_type, label, unit, label_name, system_remark) VALUES ((SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )), 'me_others_screw_molding', '', 'lathe_circularity_loss_rate', '%', '成型費(車修真圓度) Loss Rate', '成型費_成型費(車修真圓度) Loss Rate');
INSERT INTO formula.common_parameter (formula_type_id, part_type, sub_type, label, unit, label_name, system_remark) VALUES ((SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )), 'me_others_screw_second_process', '', 'turning_plating_unit_price', 'USD', '加工費(電鍍) 單位費用', '加工_加工費(電鍍) 單位費用');


INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'me_others_screw_management_and_profit') AND (label='management_and_profit')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 0.1, 'number', 'common_parameter', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'me_others_screw_management_and_profit') AND (label='nut_management_and_profit')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 0.1, 'number', 'common_parameter', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'me_others_screw_management_and_profit') AND (label='standoff_management_and_profit')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 0.1, 'number', 'common_parameter', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'me_others_screw_molding') AND (label='lathe_unit_price')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 37, 'number', 'common_parameter', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'me_others_screw_molding') AND (label='lathe_capacity')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 9000, 'number', 'common_parameter', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'me_others_screw_molding') AND (label='lathe_loss_rate')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 0.03, 'number', 'common_parameter', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'me_others_screw_molding') AND (label='tapping_unit_price')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 37, 'number', 'common_parameter', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'me_others_screw_molding') AND (label='tapping_capacity')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 9000, 'number', 'common_parameter', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'me_others_screw_molding') AND (label='tapping_loss_rate')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 0.03, 'number', 'common_parameter', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'me_others_screw_molding') AND (label='thread_rolling_unit_price')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 37, 'number', 'common_parameter', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'me_others_screw_molding') AND (label='thread_rolling_capacity')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 10000, 'number', 'common_parameter', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'me_others_screw_molding') AND (label='thread_rolling_loss_rate')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 0.03, 'number', 'common_parameter', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'me_others_screw_molding') AND (label='lathe_circularity_unit_price')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 0.3, 'number', 'common_parameter', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'me_others_screw_molding') AND (label='lathe_circularity_capacity')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 1, 'number', 'common_parameter', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'me_others_screw_molding') AND (label='lathe_circularity_loss_rate')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 0.03, 'number', 'common_parameter', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'me_others_screw_second_process') AND (label='turning_plating_unit_price')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')), 2.57, 'number', 'common_parameter', now());


--turning nylok color
INSERT INTO formula.turning_nylok_color (color_name) VALUES('Blue');
INSERT INTO formula.turning_nylok_color (color_name) VALUES('Yellow');
INSERT INTO formula.turning_nylok_color (color_name) VALUES('Coffee');

--turning nylok diameter
INSERT INTO formula.turning_nylok_diameter (diameter_begin, diameter_end) VALUES(0, 2);
INSERT INTO formula.turning_nylok_diameter (diameter_begin, diameter_end) VALUES(2.1, 2.9);
INSERT INTO formula.turning_nylok_diameter (diameter_begin, diameter_end) VALUES(3, -1);

--turning nylok length
INSERT INTO formula.turning_nylok_length (length_begin, length_end, remark) VALUES(-1, -1, 'default empty');
INSERT INTO formula.turning_nylok_length (length_begin, length_end) VALUES(0, 3);
INSERT INTO formula.turning_nylok_length (length_begin, length_end) VALUES(3.1, 9.9);
INSERT INTO formula.turning_nylok_length (length_begin, length_end) VALUES(10, -1);

--turning nylok
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = '低碳鋼18A'), (select id from formula.turning_nylok_color where color_name = 'Blue'),(select id from formula.turning_nylok_diameter where diameter_begin = 0 and diameter_end = 2),(select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = '低碳鋼18A'), (select id from formula.turning_nylok_color where color_name = 'Blue'),(select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9),(select id from formula.turning_nylok_length where length_begin = 0 and length_end = 3));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = '低碳鋼18A'), (select id from formula.turning_nylok_color where color_name = 'Blue'),(select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9),(select id from formula.turning_nylok_length where length_begin = 3.1 and length_end = 9.9));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = '低碳鋼18A'), (select id from formula.turning_nylok_color where color_name = 'Blue'),(select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9),(select id from formula.turning_nylok_length where length_begin = 10 and length_end = -1));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = '低碳鋼18A'), (select id from formula.turning_nylok_color where color_name = 'Blue'),(select id from formula.turning_nylok_diameter where diameter_begin = 3 and diameter_end = -1),(select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = '低碳鋼18A'), (select id from formula.turning_nylok_color where color_name = 'Yellow'),(select id from formula.turning_nylok_diameter where diameter_begin = 0 and diameter_end = 2),(select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = '低碳鋼18A'), (select id from formula.turning_nylok_color where color_name = 'Yellow'),(select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9),(select id from formula.turning_nylok_length where length_begin = 0 and length_end = 3));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = '低碳鋼18A'), (select id from formula.turning_nylok_color where color_name = 'Yellow'),(select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9),(select id from formula.turning_nylok_length where length_begin = 3.1 and length_end = 9.9));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = '低碳鋼18A'), (select id from formula.turning_nylok_color where color_name = 'Yellow'),(select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9),(select id from formula.turning_nylok_length where length_begin = 10 and length_end = -1));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = '低碳鋼18A'), (select id from formula.turning_nylok_color where color_name = 'Yellow'),(select id from formula.turning_nylok_diameter where diameter_begin = 3 and diameter_end = -1),(select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = '低碳鋼18A'), (select id from formula.turning_nylok_color where color_name = 'Coffee'),(select id from formula.turning_nylok_diameter where diameter_begin = 0 and diameter_end = 2),(select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = '低碳鋼18A'), (select id from formula.turning_nylok_color where color_name = 'Coffee'),(select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9),(select id from formula.turning_nylok_length where length_begin = 0 and length_end = 3));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = '低碳鋼18A'), (select id from formula.turning_nylok_color where color_name = 'Coffee'),(select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9),(select id from formula.turning_nylok_length where length_begin = 3.1 and length_end = 9.9));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = '低碳鋼18A'), (select id from formula.turning_nylok_color where color_name = 'Coffee'),(select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9),(select id from formula.turning_nylok_length where length_begin = 10 and length_end = -1));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = '低碳鋼18A'), (select id from formula.turning_nylok_color where color_name = 'Coffee'),(select id from formula.turning_nylok_diameter where diameter_begin = 3 and diameter_end = -1),(select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = 'SUS410'), (select id from formula.turning_nylok_color where color_name = 'Blue'),(select id from formula.turning_nylok_diameter where diameter_begin = 0 and diameter_end = 2),(select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = 'SUS410'), (select id from formula.turning_nylok_color where color_name = 'Blue'),(select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9),(select id from formula.turning_nylok_length where length_begin = 0 and length_end = 3));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = 'SUS410'), (select id from formula.turning_nylok_color where color_name = 'Blue'),(select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9),(select id from formula.turning_nylok_length where length_begin = 3.1 and length_end = 9.9));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = 'SUS410'), (select id from formula.turning_nylok_color where color_name = 'Blue'),(select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9),(select id from formula.turning_nylok_length where length_begin = 10 and length_end = -1));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = 'SUS410'), (select id from formula.turning_nylok_color where color_name = 'Blue'),(select id from formula.turning_nylok_diameter where diameter_begin = 3 and diameter_end = -1),(select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = 'SUS410'), (select id from formula.turning_nylok_color where color_name = 'Yellow'),(select id from formula.turning_nylok_diameter where diameter_begin = 0 and diameter_end = 2),(select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = 'SUS410'), (select id from formula.turning_nylok_color where color_name = 'Yellow'),(select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9),(select id from formula.turning_nylok_length where length_begin = 0 and length_end = 3));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = 'SUS410'), (select id from formula.turning_nylok_color where color_name = 'Yellow'),(select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9),(select id from formula.turning_nylok_length where length_begin = 3.1 and length_end = 9.9));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = 'SUS410'), (select id from formula.turning_nylok_color where color_name = 'Yellow'),(select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9),(select id from formula.turning_nylok_length where length_begin = 10 and length_end = -1));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = 'SUS410'), (select id from formula.turning_nylok_color where color_name = 'Yellow'),(select id from formula.turning_nylok_diameter where diameter_begin = 3 and diameter_end = -1),(select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = 'SUS410'), (select id from formula.turning_nylok_color where color_name = 'Coffee'),(select id from formula.turning_nylok_diameter where diameter_begin = 0 and diameter_end = 2),(select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = 'SUS410'), (select id from formula.turning_nylok_color where color_name = 'Coffee'),(select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9),(select id from formula.turning_nylok_length where length_begin = 0 and length_end = 3));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = 'SUS410'), (select id from formula.turning_nylok_color where color_name = 'Coffee'),(select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9),(select id from formula.turning_nylok_length where length_begin = 3.1 and length_end = 9.9));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = 'SUS410'), (select id from formula.turning_nylok_color where color_name = 'Coffee'),(select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9),(select id from formula.turning_nylok_length where length_begin = 10 and length_end = -1));
INSERT INTO formula.turning_nylok (material_id, color_id, diameter_id, length_id) VALUES((select id from formula.turning_material where material_name = 'SUS410'), (select id from formula.turning_nylok_color where color_name = 'Coffee'),(select id from formula.turning_nylok_diameter where diameter_begin = 3 and diameter_end = -1),(select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1));

INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = '低碳鋼18A') and color_id = (select id from formula.turning_nylok_color where color_name = 'Blue') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 0 and diameter_end = 2) and length_id = (select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1)), 0.0019, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = '低碳鋼18A') and color_id = (select id from formula.turning_nylok_color where color_name = 'Blue') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9) and length_id = (select id from formula.turning_nylok_length where length_begin = 0 and length_end = 3)), 0.0019, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = '低碳鋼18A') and color_id = (select id from formula.turning_nylok_color where color_name = 'Blue') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9) and length_id = (select id from formula.turning_nylok_length where length_begin = 3.1 and length_end = 9.9)), 0.0015, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = '低碳鋼18A') and color_id = (select id from formula.turning_nylok_color where color_name = 'Blue') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9) and length_id = (select id from formula.turning_nylok_length where length_begin = 10 and length_end = -1)), 0.0019, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = '低碳鋼18A') and color_id = (select id from formula.turning_nylok_color where color_name = 'Blue') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 3 and diameter_end = -1) and length_id = (select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1)), 0.0026, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = '低碳鋼18A') and color_id = (select id from formula.turning_nylok_color where color_name = 'Yellow') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 0 and diameter_end = 2) and length_id = (select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1)), 0.0021, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = '低碳鋼18A') and color_id = (select id from formula.turning_nylok_color where color_name = 'Yellow') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9) and length_id = (select id from formula.turning_nylok_length where length_begin = 0 and length_end = 3)), 0.0023, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = '低碳鋼18A') and color_id = (select id from formula.turning_nylok_color where color_name = 'Yellow') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9) and length_id = (select id from formula.turning_nylok_length where length_begin = 3.1 and length_end = 9.9)), 0.0019, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = '低碳鋼18A') and color_id = (select id from formula.turning_nylok_color where color_name = 'Yellow') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9) and length_id = (select id from formula.turning_nylok_length where length_begin = 10 and length_end = -1)), 0.0023, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = '低碳鋼18A') and color_id = (select id from formula.turning_nylok_color where color_name = 'Yellow') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 3 and diameter_end = -1) and length_id = (select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1)), 0.0027, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = '低碳鋼18A') and color_id = (select id from formula.turning_nylok_color where color_name = 'Coffee') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 0 and diameter_end = 2) and length_id = (select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1)), 0.0019, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = '低碳鋼18A') and color_id = (select id from formula.turning_nylok_color where color_name = 'Coffee') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9) and length_id = (select id from formula.turning_nylok_length where length_begin = 0 and length_end = 3)), 0.0019, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = '低碳鋼18A') and color_id = (select id from formula.turning_nylok_color where color_name = 'Coffee') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9) and length_id = (select id from formula.turning_nylok_length where length_begin = 3.1 and length_end = 9.9)), 0.0015, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = '低碳鋼18A') and color_id = (select id from formula.turning_nylok_color where color_name = 'Coffee') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9) and length_id = (select id from formula.turning_nylok_length where length_begin = 10 and length_end = -1)), 0.0019, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = '低碳鋼18A') and color_id = (select id from formula.turning_nylok_color where color_name = 'Coffee') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 3 and diameter_end = -1) and length_id = (select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1)), 0.0026, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = 'SUS410') and color_id = (select id from formula.turning_nylok_color where color_name = 'Blue') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 0 and diameter_end = 2) and length_id = (select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1)), 0.0026, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = 'SUS410') and color_id = (select id from formula.turning_nylok_color where color_name = 'Blue') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9) and length_id = (select id from formula.turning_nylok_length where length_begin = 0 and length_end = 3)), 0.0026, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = 'SUS410') and color_id = (select id from formula.turning_nylok_color where color_name = 'Blue') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9) and length_id = (select id from formula.turning_nylok_length where length_begin = 3.1 and length_end = 9.9)), 0.0021, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = 'SUS410') and color_id = (select id from formula.turning_nylok_color where color_name = 'Blue') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9) and length_id = (select id from formula.turning_nylok_length where length_begin = 10 and length_end = -1)), 0.0026, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = 'SUS410') and color_id = (select id from formula.turning_nylok_color where color_name = 'Blue') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 3 and diameter_end = -1) and length_id = (select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1)), 0.0032, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = 'SUS410') and color_id = (select id from formula.turning_nylok_color where color_name = 'Yellow') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 0 and diameter_end = 2) and length_id = (select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1)), 0.0026, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = 'SUS410') and color_id = (select id from formula.turning_nylok_color where color_name = 'Yellow') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9) and length_id = (select id from formula.turning_nylok_length where length_begin = 0 and length_end = 3)), 0.0032, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = 'SUS410') and color_id = (select id from formula.turning_nylok_color where color_name = 'Yellow') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9) and length_id = (select id from formula.turning_nylok_length where length_begin = 3.1 and length_end = 9.9)), 0.0026, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = 'SUS410') and color_id = (select id from formula.turning_nylok_color where color_name = 'Yellow') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9) and length_id = (select id from formula.turning_nylok_length where length_begin = 10 and length_end = -1)), 0.0032, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = 'SUS410') and color_id = (select id from formula.turning_nylok_color where color_name = 'Yellow') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 3 and diameter_end = -1) and length_id = (select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1)), 0.0032, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = 'SUS410') and color_id = (select id from formula.turning_nylok_color where color_name = 'Coffee') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 0 and diameter_end = 2) and length_id = (select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1)), 0.0032, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = 'SUS410') and color_id = (select id from formula.turning_nylok_color where color_name = 'Coffee') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9) and length_id = (select id from formula.turning_nylok_length where length_begin = 0 and length_end = 3)), 0.0026, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = 'SUS410') and color_id = (select id from formula.turning_nylok_color where color_name = 'Coffee') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9) and length_id = (select id from formula.turning_nylok_length where length_begin = 3.1 and length_end = 9.9)), 0.0026, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = 'SUS410') and color_id = (select id from formula.turning_nylok_color where color_name = 'Coffee') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 2.1 and diameter_end = 2.9) and length_id = (select id from formula.turning_nylok_length where length_begin = 10 and length_end = -1)), 0.0026, 'number', 'turning_nylok', now());
INSERT INTO formula.parameter_value (activate_date_id, parameter_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'me_others_screw' )) ) AND (name = 'me_others_screw_init')),(SELECT id FROM formula.turning_nylok WHERE material_id = (select id from formula.turning_material where material_name = 'SUS410') and color_id = (select id from formula.turning_nylok_color where color_name = 'Coffee') and diameter_id = (select id from formula.turning_nylok_diameter where diameter_begin = 3 and diameter_end = -1) and length_id = (select id from formula.turning_nylok_length where length_begin = -1 and length_end = -1)), 0.0038, 'number', 'turning_nylok', now());
