--將錯誤資料刪除
DELETE FROM wiprocurement.drop_down_item WHERE path like 'HOUSING.HINGE%.' AND layout_name='bom_item' AND field_name IN ('parts_ctgy_1', 'parts_ctgy_2', 'material_spec', 'material');

--補lv2
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE', 'HINGE', 'parts_ctgy_2', 'bom_item');

--增加的lv1
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('PACKING', 'Packing', 'parts_ctgy_1', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ELECTRO-MECHANICAL', 'Electro-Mechanical', 'parts_ctgy_1', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('RACK', 'RACK', 'parts_ctgy_1', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('MEDICAL', 'Medical', 'parts_ctgy_1', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('EMC', 'EMC', 'parts_ctgy_1', 'bom_item');

--增加的lv2
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('CABLE2.DONGLE', 'Dongle', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('CABLE2.EXTERNALCABLE', 'External Cable', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('CABLE2.RFCABLE', 'RF Cable', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('CABLE2.FIPER', 'Fiper', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('CABLE2.FIO', 'FIO', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('CABLE2.SATA', 'SATA', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('CABLE2.FLATCABLE', 'Flat Cable', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('CABLE2.OTHER', 'Other', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('CABLE2.SAS_MINISAS', 'SAS/Mini SAS', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('CABLE2.LANCABLE', 'Lan cable', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('CABLE2.HANDSETCORD', 'Handset cord', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.C_GPU_BKT', 'C_GPU_BKT', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HDD_SSD_BKT', 'HDD_SSD_BKT', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.NIL_PROCESS', 'NIL_process', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.CNC_PROCESS', 'CNC_Process', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.STAND', 'Stand', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.SMALL_PARTS', 'Small_Parts', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.GLASS', 'Glass', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.CHEMICAL', 'Chemical', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.KEYPAD', 'Keypad', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.SLIDE', 'Slide', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.METAL_AND_PLASTIC', 'Metal_and_Plastic', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.NCT', 'NCT', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.MIM', 'MIM', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('PACKING.BAG', 'Bag', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('PACKING.CARTON', 'Carton', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('PACKING.CARTON-UNFOLDED', 'Carton-Unfolded', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('PACKING.BOX', 'BOX', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('PACKING.BOX-UNFOLDED', 'BOX-Unfolded', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('PACKING.LABEL', 'Label', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('PACKING.MANUAL', 'Manual', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('PACKING.EPE', 'EPE', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('PACKING.EPS', 'EPS', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('PACKING.PALLET', 'Pallet', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('PACKING.OTHERS', 'Others', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('PACKING.OTHERS-PAPER', 'Others-Paper', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('PACKING.OTHERS-PLASTIC', 'Others-Plastic', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('PACKING.OTHERS-NON-WOVEN', 'Others-Non-woven', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('PACKING.OTHERS-CLEANCLOTHES', 'Others-Clean Clothes', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ELECTRO-MECHANICAL.MIC', 'Mic', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ELECTRO-MECHANICAL.SPEAKER', 'Speaker', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ELECTRO-MECHANICAL.VIBRATOR', 'Vibrator', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ELECTRO-MECHANICAL.BUZZER', 'Buzzer', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ELECTRO-MECHANICAL.HEADSET', 'Headset', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ELECTRO-MECHANICAL.SOUNDBAR', 'Soundbar', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('THERMAL.PAD', 'Pad', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('THERMAL.GRAPHITESHEET', 'Graphite Sheet', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('THERMAL.CUFOIL', 'Cu Foil', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('THERMAL.COOLER', 'Cooler', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('RACK.RACK', 'RACK', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('MEDICAL.LENS', 'LENS', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('MEDICAL.MOUNT', 'Mount', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('MEDICAL.RADIOTUBE', 'Radiotube', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('MEDICAL.TUBING', 'Tubing', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ME-OTHERS.BONDDETACHADHESIVE', 'Bond & Detach Adhesive', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ME-OTHERS.WATERPROOF_FILM', 'Waterproof_film', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ME-OTHERS.RUBBER', 'Rubber', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ME-OTHERS.MESH', 'Mesh', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ME-OTHERS.METAL_DOME', 'Metal_Dome', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ME-OTHERS.GLUE', 'Glue', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ME-OTHERS.SPRING', 'Spring', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ME-OTHERS.LENS', 'Lens', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ME-OTHERS.BUSBAR', 'Busbar', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ME-OTHERS.HANDSET', 'Handset ', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ME-OTHERS.NAMEPLATE', 'NamePlate', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ME-OTHERS.ACETATE_TAPE_OF_MYLAR_SPONGE_PORON', 'Acetate_Tape_of_Mylar_Sponge_Poron', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ME-OTHERS.NON_WOVEN_OF_MYLAR_SPONGE_PORON', 'Non_Woven_of_Mylar_Sponge_Poron', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('ME-OTHERS.MISCELLANEOUS', 'Miscellaneous', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('EMC.ABSORBER', 'Absorber', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('EMC.EMISPRING', 'EMISpring', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('EMC.GASKET', 'Gasket', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('EMC.AL_CU_FOIL', 'Al_Cu_Foil', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('EMC.SHIELDINGCAN', 'ShieldingCan', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('EMC.MAGNET', 'Magnet', 'parts_ctgy_2', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('EMC.CONDUCTIVETAPE', 'ConductiveTape', 'parts_ctgy_2', 'bom_item');
