SET search_path TO formula, public, wiprocurement;
drop table if exists cableffc_connector_vendor;
drop table if exists cableffc_connector_type;

CREATE TABLE IF NOT EXISTS cableffc_connector_type (
	id uuid NOT NULL DEFAULT uuid_generate_v1(),
	type_name varchar(200) not NULL,
	remark varchar(400) NULL,
	create_time timestamptz NOT null default now(),
	disable_time timestamptz null,
	CONSTRAINT cableffc_connector_type_pk PRIMARY KEY (id),
	CONSTRAINT cableffc_connector_type_un UNIQUE (type_name)
);

CREATE TABLE IF NOT EXISTS cableffc_connector_vendor (
	id uuid NOT NULL DEFAULT uuid_generate_v1(),
	vendor_name varchar(200) NULL,
	vendor_pn varchar(200) not NULL,
	connector_type_id uuid NOT NULL,
	unit_price uuid NOT NULL DEFAULT uuid_generate_v1(),
	process_time uuid NOT NULL DEFAULT uuid_generate_v1(),
	remark varchar(400) NULL,
	create_time timestamptz NOT null default now(),
	disable_time timestamptz null,
	CONSTRAINT cableffc_connector_vendor_pk PRIMARY KEY (id),
	CONSTRAINT cableffc_connector_vendor_fk FOREIGN KEY (connector_type_id) REFERENCES cableffc_connector_type(id),
	CONSTRAINT cableffc_connector_vendor_un UNIQUE (vendor_pn)
);

delete from formula.parameter_value as pv where activate_date_id in (select id from formula.schedule_date as sd where sd.formula_type_id = (select id from formula.formula_type as ft where ft."name" = 'cable_ffc'));
delete from formula.common_parameter as cp where cp.formula_type_id = (select id from formula.formula_type as ft where ft."name" = 'cable_ffc');
delete from formula.schedule_date as sd where sd.formula_type_id = (select id from formula.formula_type as ft where ft."name" = 'cable_ffc');

--formula_type
INSERT INTO formula.formula_type("name", remark, create_time) VALUES('cable_ffc', null, now()) on conflict do nothing;

--schedule_date
INSERT INTO formula.schedule_date("name", formula_type_id, activate_date, create_time) VALUES('cable_ffc_init', (select id from formula.formula_type where name='cable_ffc'), '1970-01-01', now()) on conflict do nothing;

 --ffc common
--ffc common
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_management_and_profit', NULL, 'management_and_profit', '%', '管銷&利潤', '管銷&利潤', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_material', NULL, 'edge_materia_two_side_constant', NULL, 'FFC 邊料兩邊常數', '材料費_FFC邊料兩邊常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_material', NULL, 'edge_materia_area_trans_constant', NULL, 'FFC 面積單位換算', '材料費_FFC面積單位換算', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_material', NULL, 'edge_materia_size_constant', NULL, 'FFC 基本邊料尺寸', '材料費_FFC基本邊料尺寸', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_material', NULL, 'edge_materia_add_size_constant', NULL, 'FFC 沖型單邊所增加之邊料尺寸', '材料費_FFC沖型單邊所增加之邊料尺寸', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_material', NULL, 'material_cost', 'USD', 'FFC 材料單價', '材料費_材料單價', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_material', NULL, 'material_loss_rate', '%', 'FFC 材料費 loss rate', '材料費_lossrate', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_secondary_processing', NULL, 'assembly_cost', 'USD', 'FFC 組裝費', '二次加工費_FFC組裝費', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_secondary_processing', NULL, 'assembly_time_unit_transfer', 'USD', 'FFC 時間單位換算', '二次加工費_時間單位換算', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_secondary_processing', NULL, 'knee_bend_cost', 'USD', 'FFC 折彎單價', '二次加工費_FFC折彎單價', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_secondary_processing', NULL, 'print_cost', 'USD', 'FFC 印刷單價', '二次加工費_FFC印刷單價', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_secondary_processing', NULL, 'punching_cost', 'USD', 'FFC 沖型單價', '二次加工費_FFC沖型單價', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_secondary_processing', NULL, 'golden_finger_rack_plating_cost', 'USD', 'FFC 金手指掛鍍單價', '二次加工費_FFC金手指掛鍍單價', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_secondary_processing', NULL, 'golden_finger_width_ratio', NULL, 'FFC 金手指寬度比例', '二次加工費_FFC金手指寬度比例', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_secondary_processing', NULL, 'golden_finger_length', NULL, 'FFC 金手指長度', '二次加工費_FFC金手指長度', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_secondary_processing', NULL, 'golden_finger_two_side_constant', NULL, 'FFC 金手指兩邊常數', '二次加工費_FFC金手指邊料兩邊常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_secondary_processing', NULL, 'stop_line_cost', 'USD', 'FFC 停止線單價', '二次加工費_停止線單價', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'area_unit_transfer_constant', NULL, '面積單位換算常數', '零件費_面積單位換算常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'al_foil_cost', 'USD', 'Al foil 單價', '零件費_Al_foil單價', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'al_foil_loss_rate', '%', 'Al foil loss rate', '零件費_Al_foillossrate', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'al_foil_l_side_constant', NULL, 'Al foil L 邊料常數', '零件費_Al_foil_L_邊料常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'al_foil_w_side_constant', NULL, 'Al foil W 邊料常數', '零件費_Al_foil_W_邊料常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'al_foil_assembly', 'sec', 'Al foil 所需組裝秒數', '零件費_Al_foil_W_所需組裝秒數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'stiffener_cost', 'USD', '補強板單價', '零件費_補強板單價', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'stiffener_loss_rate', '%', '補強板loss rate', '零件費_補強板lossrate', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'stiffener_l_side_constant', NULL, '補強板 L 邊料常數', '零件費_補強板_L_邊料常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'stiffener_w_side_constant', NULL, '補強板 W 邊料常數', '零件費_補強板_W_邊料常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'stiffener_assembly', 'sec', '補強板 所需組裝秒數', '零件費_補強板_組裝秒數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'label_1_cost', 'USD', 'Label 1 料號標籤單價', '零件費_Label_1_單價', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'label_1_assembly', 'sec', 'Label 1 所需組裝秒數', '零件費_Label_1_組裝秒數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'label_2_cost', 'USD', 'Label 2 白底黑字單價', '零件費_Label_2_單價', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'label_2_assembly', 'sec', 'Label 2 所需組裝秒數', '零件費_Label_2_組裝秒數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'conductive_fabric_cost', 'USD', '導電布單價', '零件費_導電布單價', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'conductive_fabric_loss_rate', '%', '導電布 loss rate', '零件費_導電布lossrate', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'conductive_fabric_l_side_constant', NULL, '導電布 L 邊料常數', '零件費_導電布_L_邊料常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'conductive_fabric_w_side_constant', NULL, '導電布 W 邊料常數', '零件費_導電布_W_邊料常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'conductive_assembly', 'sec', '導電布 所需組裝秒數', '零件費_導電布_組裝秒數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'acetate_cloth_cost', 'USD', '醋酸布單價', '零件費_醋酸布單價', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'acetate_cloth_loss_rate', '%', '醋酸布loss rate', '零件費_醋酸布lossrate', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'acetate_cloth_l_side_constant', NULL, '醋酸布 L 邊料常數', '零件費_醋酸布_L_邊料常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'acetate_cloth_w_side_constant', NULL, '醋酸布 W 邊料常數', '零件費_醋酸布_W_邊料常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'acetate_cloth_assembly', 'sec', '醋酸布 所需組裝秒數', '零件費_醋酸布_組裝秒數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'kapton_cost', 'USD', 'kapton單價', '零件費_kapton單價', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'kapton_loss_rate', NULL, 'kapton loss rate', '零件費_kapto_ lossrate', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'kapton_l_side_constant', NULL, 'kapton L 邊料常數', '零件費_kapton_L_邊料常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'kapton_w_side_constant', NULL, 'kapton W 邊料常數', '零件費_kapton_W_邊料常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'kapton_assembly', 'sec', 'kapton 所需組裝秒數', '零件費_kapton_W_邊料常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'double_sided_tape_cost', 'USD', '雙面膠單價', '零件費_雙面膠單價', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'double_sided_tape_loss_rate', NULL, '雙面膠 loss rate', '零件費_雙面膠lossrate', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'double_sided_tape_l_side_constant', NULL, '雙面膠 L 邊料常數', '零件費_雙面膠_L_邊料常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'double_sided_tape_w_side_constant', NULL, '雙面膠 W 邊料常數', '零件費_雙面膠_W_邊料常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'double_sided_tape_assembly', 'sec', '雙面膠 需組裝秒數', '零件費_雙面膠_組裝秒數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'mylar_cy28_pet_t_0.05_cost', 'USD', 'Mylar(CY28_PET) T=0.05 單價', '零件費_Mylar_CY28_PET_T_0.05單價', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'mylar_cy28_pet_t_0.05_loss_rate', '%', 'Mylar(CY28_PET) T=0.05 loss rate', '零件費_Mylar_CY28_PET_T_0.05 lossrate', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'mylar_cy28_pet_t_0.05_l_side_constant', NULL, 'Mylar(CY28_PET) T=0.05  L 邊料常數', '零件費_Mylar_CY28_PET_T_0.05 _L_邊料常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'mylar_cy28_pet_t_0.05_w_side_constant', NULL, 'Mylar(CY28_PET) T=0.05  W 邊料常數', '零件費_Mylar_CY28_PET_T_0.05 _W_邊料常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'mylar_cy28_pet_t_0.05_assembly', 'sec', 'Mylar(CY28_PET) T=0.05  需組裝秒數', '零件費_Mylar_CY28_PET_T_0.05 _組裝秒數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'mylar_pet_6027d_t_0.1_cost', 'USD', 'Mylar(PET_6027D) T=0.1 單價', '零件費_Mylar_PET_6027D_T_0.1單價', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'mylar_pet_6027d_t_0.1_loss_rate', '%', 'Mylar(PET_6027D) T=0.1 loss rate', '零件費_Mylar_PET_6027D_T_0.1lossrate', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'mylar_pet_6027d_t_0.1_l_side_constant', NULL, 'Mylar(PET_6027D) T=0.1  L 邊料常數', '零件費_Mylar_PET_6027D_T_0.1 _L_邊料常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'mylar_pet_6027d_t_0.1_w_side_constant', NULL, 'Mylar(PET_6027D) T=0.1  W 邊料常數', '零件費_Mylar_PET_6027D_T_0.1_W_邊料常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'mylar_pet_6027d_t_0.1_assembly', 'sec', 'Mylar(PET_6027D) T=0.1  需組裝秒數', '零件費_Mylar_PET_6027D_T_0.1_組裝秒數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'conductive_double_sided_tape_cost', 'USD', '導電雙面膠單價', '零件費_導電雙面膠單價', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'conductive_double_sided_tape_loss_rate', '%', '導電雙面膠loss rate', '零件費_導電雙面膠lossrate', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'conductive_double_sided_tape_l_side_constant', NULL, '導電雙面膠 L 邊料常數', '零件費_導電雙面膠_L_邊料常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'conductive_double_sided_tape_w_side_constant', NULL, '導電雙面膠 W 邊料常數', '零件費_導電雙面膠_W_邊料常數', now(), NULL);
 INSERT INTO formula.common_parameter (id, formula_type_id, part_type, sub_type, label, unit, label_name, system_remark, create_time, remark) VALUES (uuid_generate_v1(), (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )), 'cable_ffc_components', NULL, 'conductive_double_sided_tape_assembly', 'sec', '導電雙面膠 W 需組裝秒數', '零件費_導電雙面膠_W_需組裝秒數', now(), NULL);
 
 --paramater value
  INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_management_and_profit') AND (label='management_and_profit')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0.1, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_material') AND (label='edge_materia_two_side_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 2, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_material') AND (label='edge_materia_area_trans_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 1000000, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_material') AND (label='edge_materia_size_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 2, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_material') AND (label='edge_materia_add_size_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 1.25, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_material') AND (label='material_cost')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 26.6, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_material') AND (label='material_loss_rate')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0.03, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_secondary_processing') AND (label='assembly_cost')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0.045, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_secondary_processing') AND (label='assembly_time_unit_transfer')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 60, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_secondary_processing') AND (label='knee_bend_cost')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0.008, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_secondary_processing') AND (label='print_cost')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0.006, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_secondary_processing') AND (label='punching_cost')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0.016, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_secondary_processing') AND (label='golden_finger_rack_plating_cost')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0.00017, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_secondary_processing') AND (label='golden_finger_width_ratio')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0.6, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_secondary_processing') AND (label='golden_finger_length')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 5, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_secondary_processing') AND (label='golden_finger_two_side_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 2, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_secondary_processing') AND (label='stop_line_cost')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0.008, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='area_unit_transfer_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 1000000, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='al_foil_cost')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 2.97, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='al_foil_loss_rate')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0.01, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='al_foil_l_side_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 6, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='al_foil_w_side_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 6, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='al_foil_assembly')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 12, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='stiffener_cost')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 2.609, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='stiffener_loss_rate')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0.01, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='stiffener_l_side_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 6, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='stiffener_w_side_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 6, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='stiffener_assembly')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 12, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='label_1_cost')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0.0015, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='label_1_assembly')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 5, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='label_2_cost')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0.001, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='label_2_assembly')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 5, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='conductive_fabric_cost')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 19.5, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='conductive_fabric_loss_rate')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='conductive_fabric_l_side_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 6, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='conductive_fabric_w_side_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 6, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='conductive_assembly')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 5, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='acetate_cloth_cost')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 4.044, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='acetate_cloth_loss_rate')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='acetate_cloth_l_side_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 6, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='acetate_cloth_w_side_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 6, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='acetate_cloth_assembly')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 5, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='kapton_cost')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 1.1527, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='kapton_loss_rate')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='kapton_l_side_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 6, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='kapton_w_side_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 6, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='kapton_assembly')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 5, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='double_sided_tape_cost')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 1.875, 'number', 'common_parameter', now()); INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='double_sided_tape_loss_rate')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='double_sided_tape_l_side_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 6, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='double_sided_tape_w_side_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 6, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='double_sided_tape_assembly')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 5, 'number', 'common_parameter', now()); INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='mylar_cy28_pet_t_0.05_cost')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0.5117, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='mylar_cy28_pet_t_0.05_loss_rate')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='mylar_cy28_pet_t_0.05_l_side_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 6, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='mylar_cy28_pet_t_0.05_w_side_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 6, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='mylar_cy28_pet_t_0.05_assembly')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 5, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='mylar_pet_6027d_t_0.1_cost')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0.5764, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='mylar_pet_6027d_t_0.1_loss_rate')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='mylar_pet_6027d_t_0.1_l_side_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 6, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='mylar_pet_6027d_t_0.1_w_side_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 6, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='mylar_pet_6027d_t_0.1_assembly')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 5, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='conductive_double_sided_tape_cost')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 3.6764, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='conductive_double_sided_tape_loss_rate')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='conductive_double_sided_tape_l_side_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 6, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='conductive_double_sided_tape_w_side_constant')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 6, 'number', 'common_parameter', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT id FROM formula.common_parameter WHERE (part_type = 'cable_ffc_components') AND (label='conductive_double_sided_tape_assembly')), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 5, 'number', 'common_parameter', now());

--cableffc_connector_type
INSERT INTO formula.cableffc_connector_type (id, type_name, create_time) VALUES (uuid_generate_v1(), 'HDD Connector', now());
 INSERT INTO formula.cableffc_connector_type (id, type_name, create_time) VALUES (uuid_generate_v1(), 'ODD Connector', now());

 --cableffc_connector_vendor
 INSERT INTO formula.cableffc_connector_vendor (id, vendor_pn, connector_type_id, create_time) VALUES (uuid_generate_v1(), 'HDD CN 062B-101-(7+15)P-802', (SELECT id FROM formula.cableffc_connector_type WHERE (type_name = 'HDD Connector' )), now());
 INSERT INTO formula.cableffc_connector_vendor (id, vendor_pn, connector_type_id, create_time) VALUES (uuid_generate_v1(), 'ODD CN FFC ST12113G41100', (SELECT id FROM formula.cableffc_connector_type WHERE (type_name = 'ODD Connector' )), now());

--cableffc_connector_vendor paramater
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT unit_price FROM formula.cableffc_connector_vendor WHERE (vendor_pn = 'HDD CN 062B-101-(7+15)P-802') AND (connector_type_id = (SELECT id FROM formula.cableffc_connector_type WHERE (type_name = 'HDD Connector' )))), (SELECT id FROM formula.schedule_date WHERE (formula_type_id=(SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0.13614, 'number', 'cableffc_connector_vendor', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT unit_price FROM formula.cableffc_connector_vendor WHERE (vendor_pn = 'ODD CN FFC ST12113G41100') AND (connector_type_id = (SELECT id FROM formula.cableffc_connector_type WHERE (type_name = 'ODD Connector' )))), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 0.11712, 'number', 'cableffc_connector_vendor', now());
INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT process_time FROM formula.cableffc_connector_vendor WHERE (vendor_pn = 'HDD CN 062B-101-(7+15)P-802') AND (connector_type_id = (SELECT id FROM formula.cableffc_connector_type WHERE (type_name = 'HDD Connector' )))), (SELECT id FROM formula.schedule_date WHERE (formula_type_id=(SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 75, 'number', 'cableffc_connector_vendor', now());
 INSERT INTO formula.parameter_value (parameter_id, activate_date_id, value, value_type, source_table, create_time) VALUES ((SELECT process_time FROM formula.cableffc_connector_vendor WHERE (vendor_pn = 'ODD CN FFC ST12113G41100') AND (connector_type_id = (SELECT id FROM formula.cableffc_connector_type WHERE (type_name = 'ODD Connector' )))), (SELECT id FROM formula.schedule_date WHERE (formula_type_id= (SELECT id FROM formula.formula_type WHERE (name= 'cable_ffc' )) ) AND (name = 'cable_ffc_init')), 75, 'number', 'cableffc_connector_vendor', now());
