
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.METAL.C18400', 'C18400', 'material_spec', 'bom_item');
--INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.METAL.CU1100', 'CU1100', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.METAL.CU01', 'CU01', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.ALUMI.AL6061', 'AL6061', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.ALUMI.AL6063', 'AL6063', 'material_spec', 'bom_item');

--DELETE FROM wiprocurement.drop_down_item WHERE path='HOUSING.PLAST' AND item_name = 'Plastic' AND field_name = 'parts_ctgy_2' AND layout_name ='bom_item';
--DELETE FROM wiprocurement.drop_down_item WHERE path='HOUSING.DOUBL' AND item_name = 'Double_Injection' AND field_name = 'parts_ctgy_2' AND layout_name ='bom_item';
--DELETE FROM wiprocurement.drop_down_item WHERE path='HOUSING.RHCM_' AND item_name = 'RHCM_Process' AND field_name = 'parts_ctgy_2' AND layout_name ='bom_item';
--DELETE FROM wiprocurement.drop_down_item WHERE path='HOUSING.IMR' AND item_name = 'IMR' AND field_name = 'parts_ctgy_2' AND layout_name ='bom_item';

--LV3
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.FR_PC', 'FR_PC', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.FR_PC_TRANSLUCENT', 'FR_PC_Translucent', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.FR_PC_DIFFUSION_KUSAN', 'FR_PC_Diffusion_擴散', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.NON_FR_PC', 'Non_FR_PC', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PA_50PERCENT_GF', 'PA_50percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PA1010_55PERCENT_GF', 'PA1010_55percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC', 'PC', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_WITH_25PERCENT_PCR', 'PC_with_25percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_WITH_30PERCENT_PCR', 'PC_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_NONTRANSFER', 'PC_非透明', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_10PERCENT_GF', 'PC_10percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_10PERCENT_GF_WITH_30PERCENT_PCR', 'PC_10percent_GF_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_15PERCENT_CF', 'PC_15percent_CF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_20PERCENT_CF', 'PC_20percent_CF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_20PERCENT_CF_WITH_30PERCENT_PCR', 'PC_20percent_CF_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_20ERCENT_GF', 'PC_20ercent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_21ERCENT_GF', 'PC_21ercent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_25PERCENT_GF', 'PC_25percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_25PERCENT_TALC', 'PC_25percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_25PERCENT_TALC_WITH_30PERCENT_PCR', 'PC_25percent_Talc_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_25PERCENT_TALC_WITH_35PERCENT_PCR', 'PC_25percent_Talc_with_35percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_30PERCENT_GF', 'PC_30percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_31PERCENT_GF', 'PC_31percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_32PERCENT_GF', 'PC_32percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_33PERCENT_GF', 'PC_33percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_35PERCENT_GF_WITH_5PERCENT_TALC', 'PC_35percent_GF_with_5percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_40PERCENT_GF', 'PC_40percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_40PERCENT_GF_WITH_30PERCENT_PCR', 'PC_40percent_GF_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_45PERCENT_GF', 'PC_45percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_50PERCENT_GF', 'PC_50percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_50PERCENT_GF_RECYCLE', 'PC_50percent_GF_Recycle', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_50PERCENT_GF_WITH_20PERCENT_PCR', 'PC_50percent_GF_with_20percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_50PERCENT_GF_WITH_30PERCENT_PCR', 'PC_50percent_GF_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS', 'PC_ABS', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_WITH_30PERCENT_PCR', 'PC_ABS_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_WITH_35PERCENT_PCR', 'PC_ABS_with_35percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_HIGHLIGHT', 'PC_ABS_高光澤高流動', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_12PERCENT_TALC', 'PC_ABS_12percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_15PERCENT_TALC', 'PC_ABS_15percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_15PERCENT_TALC_UVS', 'PC_ABS_15percent_Talc_UVS', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_15PERCENT_TALC_WITH_15PERCENT_PCR', 'PC_ABS_15percent_Talc_with_15percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_15PERCENT_TALC_WITH_30PERCENT_PCR', 'PC_ABS_15percent_Talc_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_23PERCENT_TALC', 'PC_ABS_23percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_25PERCENT_TALC', 'PC_ABS_25percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_25PERCENT_TALC_WITH_30PERCENT_PCR', 'PC_ABS_25percent_Talc_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_25PERCENT_TALC_WITH_35PERCENT_PCR', 'PC_ABS_25percent_Talc_with_35percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_3PERCENT_TALC', 'PC_ABS_3percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_5PERCENT_TALC', 'PC_ABS_5percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_5PERCENT_TALC_UVS', 'PC_ABS_5percent_Talc_UVS', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_5PERCENT_TALC_WITH_35PERCENT_PCR', 'PC_ABS_5percent_Talc_with_35percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_8PERCENT_TALC', 'PC_ABS_8percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_PMMA', 'PC_ABS_PMMA', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_GF_CF', 'PC_GF_CF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_REDLIGHT', 'PC紅外線透過型', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.POM', 'POM', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PPA_55PERCENT_GF', 'PPA_55percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PPA_60PERCENT_GF', 'PPA_60percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PPS_45PERCENT_GF', 'PPS_45percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PPS_50PERCENT_GF', 'PPS_50percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PPS_50PERCENT_GF_MD', 'PPS_50percent_GF_MD', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.TPEE ', 'TPEE ', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.TPU', 'TPU', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.WEARABLE_PC_NIMO', 'Wearable_PC_耐磨', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.FIRE_TPEE', '防火_TPEE', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.HIGHFIRE_PC', '防火高流動_PC', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.NIHO_PC', '耐候_PC', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.KOSAN_PC', '擴散級_PC', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.NON_AUTO_LOCK_SINGLE', 'Non Auto lock 單軸 ', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.NON_AUTO_LOCK_SINGLE_WITH', 'Non Auto lock 單軸 +支架', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.NON_AUTO_LOCK_DOUBLE', 'Non Auto lock 雙軸 ', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.NON_AUTO_LOCK_DOUBLE_WITH', 'Non Auto lock 雙軸 +支架', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.AUTO_LOCK_SINGLE', 'Auto lock 單軸 ', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.AUTO_LOCK_SINGLE_WITH', 'Auto lock 單軸 +支架', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.AUTO_LOCK_DOUBLE', 'Auto lock 雙軸 ', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.AUTO_LOCK_DOUBLE_WITH', 'Auto lock 雙軸 +支架', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.CYRCLE', '包圓式', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.GUODUON', '中空轉軸', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.TAI_CAP_GAP', '鋅合金 CAP 連承架', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.DOCKING', 'Docking', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.RISING_KB', 'Rising KB 雙軸', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.SPECIAL_STRUCTURE', '特殊結構', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_25PERCENT_TALC', 'PC_25percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_25PERCENT_TALC_WITH_30PERCENT_PCR', 'PC_25percent_Talc_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_25PERCENT_TALC_WITH_35PERCENT_PCR', 'PC_25percent_Talc_with_35percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS', 'PC_ABS', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_WITH_30PERCENT_PCR', 'PC_ABS_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_WITH_35PERCENT_PCR', 'PC_ABS_with_35percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_12PERCENT_TALC', 'PC_ABS_12percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_15PERCENT_TALC', 'PC_ABS_15percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_15PERCENT_TALC_WITH_15PERCENT_PCR', 'PC_ABS_15percent_Talc_with_15percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_15PERCENT_TALC_WITH_30PERCENT_PCR', 'PC_ABS_15percent_Talc_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_23PERCENT_TALC', 'PC_ABS_23percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_25PERCENT_TALC', 'PC_ABS_25percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_25PERCENT_TALC_WITH_30PERCENT_PCR', 'PC_ABS_25percent_Talc_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_25PERCENT_TALC_WITH_35PERCENT_PCR', 'PC_ABS_25percent_Talc_with_35percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_3PERCENT_TALC', 'PC_ABS_3percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_5PERCENT_TALC', 'PC_ABS_5percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_5PERCENT_TALC_WITH_35PERCENT_PCR', 'PC_ABS_5percent_Talc_with_35percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_8PERCENT_TALC', 'PC_ABS_8percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC', 'PC', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_WITH_25PERCENT_PCR', 'PC_with_25percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_WITH_30PERCENT_PCR', 'PC_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_NONTRANSFER', 'PC_非透明', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_25PERCENT_TALC', 'PC_25percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_25PERCENT_TALC_WITH_30PERCENT_PCR', 'PC_25percent_Talc_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_25PERCENT_TALC_WITH_35PERCENT_PCR', 'PC_25percent_Talc_with_35percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS', 'PC_ABS', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_WITH_30PERCENT_PCR', 'PC_ABS_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_WITH_35PERCENT_PCR', 'PC_ABS_with_35percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_HIGHLIGHT', 'PC_ABS_高光澤高流動', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_12PERCENT_TALC', 'PC_ABS_12percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_15PERCENT_TALC', 'PC_ABS_15percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_15PERCENT_TALC_UVS', 'PC_ABS_15percent_Talc_UVS', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_15PERCENT_TALC_WITH_15PERCENT_PCR', 'PC_ABS_15percent_Talc_with_15percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_15PERCENT_TALC_WITH_30PERCENT_PCR', 'PC_ABS_15percent_Talc_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_23PERCENT_TALC', 'PC_ABS_23percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_25PERCENT_TALC', 'PC_ABS_25percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_25PERCENT_TALC_WITH_30PERCENT_PCR', 'PC_ABS_25percent_Talc_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_25PERCENT_TALC_WITH_35PERCENT_PCR', 'PC_ABS_25percent_Talc_with_35percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_3PERCENT_TALC', 'PC_ABS_3percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_5PERCENT_TALC', 'PC_ABS_5percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_5PERCENT_TALC_UVS', 'PC_ABS_5percent_Talc_UVS', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_5PERCENT_TALC_WITH_35PERCENT_PCR', 'PC_ABS_5percent_Talc_with_35percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_8PERCENT_TALC', 'PC_ABS_8percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PA_50PERCENT_GF', 'PA_50percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PA1010_55PERCENT_GF', 'PA1010_55percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_10PERCENT_GF', 'PC_10percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_10PERCENT_GF_WITH_30PERCENT_PCR', 'PC_10percent_GF_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_15PERCENT_CF', 'PC_15percent_CF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_20PERCENT_CF', 'PC_20percent_CF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_20PERCENT_CF_WITH_30PERCENT_PCR', 'PC_20percent_CF_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_20ERCENT_GF', 'PC_20ercent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_25PERCENT_GF', 'PC_25percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_30PERCENT_GF', 'PC_30percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_35PERCENT_GF_WITH_5PERCENT_TALC', 'PC_35percent_GF_with_5percent_Talc', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_40PERCENT_GF', 'PC_40percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_40PERCENT_GF_WITH_30PERCENT_PCR', 'PC_40percent_GF_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_45PERCENT_GF', 'PC_45percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_50PERCENT_GF', 'PC_50percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_50PERCENT_GF_RECYCLE', 'PC_50percent_GF_Recycle', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_50PERCENT_GF_WITH_20PERCENT_PCR', 'PC_50percent_GF_with_20percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_50PERCENT_GF_WITH_30PERCENT_PCR', 'PC_50percent_GF_with_30percent_PCR', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_ABS_HIGHLIGHT', 'PC_ABS_高光澤高流動', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_ABS_15PERCENT_TALC_UVS', 'PC_ABS_15percent_Talc_UVS', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_ABS_5PERCENT_TALC_UVS', 'PC_ABS_5percent_Talc_UVS', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_ABS_PMMA', 'PC_ABS_PMMA', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_GF_CF', 'PC_GF_CF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_REDLIGHT', 'PC紅外線透過型', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PPA_55PERCENT_GF', 'PPA_55percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PPA_60PERCENT_GF', 'PPA_60percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PPS_45PERCENT_GF', 'PPS_45percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PPS_50PERCENT_GF', 'PPS_50percent_GF', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PPS_50PERCENT_GF_MD', 'PPS_50percent_GF_MD', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.FIRE_PC', '防火高流動_PC', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.NIHO_PC', '耐候_PC', 'material_spec', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.KOSAN_PC', '擴散級_PC', 'material_spec', 'bom_item');


--LV4
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.FR_PC.SABIC_BPL1000', 'Sabic_BPL1000', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.FR_PC_TRANSLUCENT.SABIC_ML7681', 'Sabic_ML7681', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.FR_PC_DIFFUSION_KUSAN.SABIC_FXD9810', 'Sabic_FXD9810', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.NON_FR_PC.SABIC_121R / 141R /123R-CC', 'Sabic_121R / 141R /123R-CC', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PA_50PERCENT_GF.DUPONT_HTNFR55G50NHLWSF', 'Dupont_HTNFR55G50NHLWSF', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PA1010_55PERCENT_GF.DUPONT_HTN59G55LWSF', 'Dupont_HTN59G55LWSF', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC.SABIC_EXL1414', 'Sabic_EXL1414', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC.TEIJIN_L-1225L', 'Teijin_L-1225L', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC.TEIJIN_L-1225Y', 'Teijin_L-1225Y', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC.TEIJIN_L-1250Y', 'Teijin_L-1250Y', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC.TEIJIN_LN2520A', 'Teijin_LN2520A', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC.TEIJIN_MN-4800', 'Teijin_MN-4800', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_WITH_25PERCENT_PCR.TEIJIN_MN-3709EE', 'Teijin_MN-3709EE', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_WITH_30PERCENT_PCR.SABIC_RCX7243', 'Sabic_RCX7243', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_NONTRANSFER.MEP_FPR3500 ', 'MEP_FPR3500 ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_NONTRANSFER.MEP_FPL3500', 'MEP_FPL3500', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_10PERCENT_GF.SABIC_D151', 'Sabic_D151', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_10PERCENT_GF.TEIJIN_GV-3510R', 'Teijin_GV-3510R', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_10PERCENT_GF_WITH_30PERCENT_PCR.LG_LUPOY ER2102', 'LG_LUPOY ER2102', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_15PERCENT_CF.MEP_CP2015N2', 'MEP_CP2015N2', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_20PERCENT_CF.SABIC_DC0041PQ', 'Sabic_DC0041PQ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_20PERCENT_CF_WITH_30PERCENT_PCR.SABIC_DC0041PR', 'Sabic_DC0041PR', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_20ERCENT_GF.SABIC_D251', 'Sabic_D251', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_21ERCENT_GF.TEIJIN_GV-3520R', 'Teijin_GV-3520R', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_25PERCENT_GF.LG_LUPOY GN2253F', 'LG_LUPOY GN2253F', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_25PERCENT_TALC.SABIC_BM5225Y ', 'Sabic_BM5225Y ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_25PERCENT_TALC.TEIJIN_DN-5325B', 'Teijin_DN-5325B', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_25PERCENT_TALC.TEIJIN_DN-5325S', 'Teijin_DN-5325S', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_25PERCENT_TALC_WITH_30PERCENT_PCR.TEIJIN_DN-5325SEF', 'Teijin_DN-5325SEF', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_25PERCENT_TALC_WITH_35PERCENT_PCR.SABIC_RCM6224 ', 'Sabic_RCM6224 ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_30PERCENT_GF.COVESTRO_GF9016', 'Covestro_GF9016', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_31PERCENT_GF.LG_LUPOY GN2303F', 'LG_LUPOY GN2303F', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_32PERCENT_GF.SABIC_D351  ', 'Sabic_D351  ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_33PERCENT_GF.TEIJIN_GXV-3530UH', 'Teijin_GXV-3530UH', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_35PERCENT_GF_WITH_5PERCENT_TALC.COVESTRO_GF9012MF', 'Covestro_GF9012MF', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_40PERCENT_GF.COVESTRO_GF9018', 'Covestro_GF9018', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_40PERCENT_GF.LG_LUPOY GN2403FT', 'LG_LUPOY GN2403FT', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_40PERCENT_GF.SABIC_D451  ', 'Sabic_D451  ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_40PERCENT_GF.SABIC_D452   ', 'Sabic_D452   ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_40PERCENT_GF.TEIJIN_GN-3540RI', 'Teijin_GN-3540RI', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_40PERCENT_GF_WITH_30PERCENT_PCR.LG_LUPOY ER2403F', 'LG_LUPOY ER2403F', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_45PERCENT_GF.TEIJIN_GXV-3545WI', 'Teijin_GXV-3545WI', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_50PERCENT_GF.COVESTRO_GF9020', 'Covestro_GF9020', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_50PERCENT_GF.LG_LUPOY GN2503F', 'LG_LUPOY GN2503F', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_50PERCENT_GF.SABIC_D551  ', 'Sabic_D551  ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_50PERCENT_GF.TEIJIN_GXV-3550WI', 'Teijin_GXV-3550WI', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_50PERCENT_GF_RECYCLE.COVESTRO_M4004GR', 'Covestro_M4004GR', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_50PERCENT_GF_WITH_20PERCENT_PCR.LG_LUPOY ER2503F', 'LG_LUPOY ER2503F', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_50PERCENT_GF_WITH_30PERCENT_PCR.SABIC_D551RC', 'Sabic_D551RC', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS.COVESTRO_FR3002', 'Covestro_FR3002', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS.COVESTRO_FR3008', 'Covestro_FR3008', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS.COVESTRO_FR3040', 'Covestro_FR3040', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS.LG_LUPOY GN5001RFD', 'LG_LUPOY GN5001RFD', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS.MEP_MB1800', 'MEP_MB1800', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS.SABIC_CX2244ME', 'Sabic_CX2244ME', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS.SABIC_CX7240', 'Sabic_CX7240', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS.SABIC_CY6120', 'Sabic_CY6120', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS.TEIJIN_TN-7000A', 'Teijin_TN-7000A', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS.TEIJIN_TN-7690A', 'Teijin_TN-7690A', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS.LOTTE_NH-1021', 'LOTTE_NH-1021', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS.LOTTE_NH-1015V', 'LOTTE_NH-1015V', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_WITH_30PERCENT_PCR.COVESTRO_FR630GR', 'Covestro_FR630GR', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_WITH_30PERCENT_PCR.LG_LUPOY ER5001RFA', 'LG_LUPOY ER5001RFA', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_WITH_35PERCENT_PCR.SABIC_RCY6214', 'Sabic_RCY6214', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_HIGHLIGHT.TEIJIN_TN 7050', 'Teijin_TN 7050', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_HIGHLIGHT.TEIJIN_TN 7050Y', 'Teijin_TN 7050Y', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_12PERCENT_TALC.LG_LUPOY GN5121RF', 'LG_LUPOY GN5121RF', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_12PERCENT_TALC.MEP_TMB1412', 'MEP_TMB1412', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_15PERCENT_TALC.COVESTRO_FR3021', 'Covestro_FR3021', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_15PERCENT_TALC.LG_LUPOY GN5151RFA', 'LG_LUPOY GN5151RFA', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_15PERCENT_TALC.MEP_TMB1615', 'MEP_TMB1615', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_15PERCENT_TALC.SABIC_C7230P', 'Sabic_C7230P', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_15PERCENT_TALC.TEIJIN_TN-3715B', 'Teijin_TN-3715B', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_15PERCENT_TALC.TEIJIN_TN-3715BW', 'Teijin_TN-3715BW', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_15PERCENT_TALC.TEIJIN_TN-3715BX', 'Teijin_TN-3715BX', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_15PERCENT_TALC.TEIJIN_TN-3740B', 'Teijin_TN-3740B', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_15PERCENT_TALC.LOTTE_NH-1150HH', 'LOTTE_NH-1150HH', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_15PERCENT_TALC_UVS.COVESTRO_FR3021BBS910', 'Covestro_FR3021BBS910', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_15PERCENT_TALC_UVS.TEIJIN_TN-3715BZ', 'Teijin_TN-3715BZ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_15PERCENT_TALC_WITH_15PERCENT_PCR.TEIJIN_TN 3745BEC', 'Teijin_TN 3745BEC', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_15PERCENT_TALC_WITH_30PERCENT_PCR.COVESTRO_FR3021GR', 'Covestro_FR3021GR', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_15PERCENT_TALC_WITH_30PERCENT_PCR.LG_LUPOY ER5151RFL', 'LG_LUPOY ER5151RFL', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_15PERCENT_TALC_WITH_30PERCENT_PCR.SABIC_RCM6123', 'Sabic_RCM6123', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_15PERCENT_TALC_WITH_30PERCENT_PCR.TEIJIN_TN 3745BEF', 'Teijin_TN 3745BEF', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_23PERCENT_TALC.COVESTRO_FR3023', 'Covestro_FR3023', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_25PERCENT_TALC.COVESTRO_FR3025', 'Covestro_FR3025', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_25PERCENT_TALC.LG_LUPOY GN5254FD', 'LG_LUPOY GN5254FD', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_25PERCENT_TALC_WITH_30PERCENT_PCR.LG_LUPOY ER5254F', 'LG_LUPOY ER5254F', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_25PERCENT_TALC_WITH_35PERCENT_PCR.COVESTRO_FR3025R35', 'Covestro_FR3025R35', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_3PERCENT_TALC.MEP_MB1700', 'MEP_MB1700', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_5PERCENT_TALC.COVESTRO_FR3021BBS910', 'Covestro_FR3021BBS910', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_5PERCENT_TALC.TEIJIN_TN-3715BZ', 'Teijin_TN-3715BZ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_5PERCENT_TALC_UVS.TEIJIN_TN-7200B', 'Teijin_TN-7200B', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_5PERCENT_TALC_WITH_35PERCENT_PCR.SABIC_RCM6134', 'Sabic_RCM6134', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_8PERCENT_TALC.SABIC_CM6140', 'Sabic_CM6140', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_ABS_PMMA.LG_LUPOY SG-5009FA', 'LG_LUPOY SG-5009FA', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_GF_CF.MEP_BCB992', 'MEP_BCB992', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PC_REDLIGHT.MEP_7025A OAT223', 'MEP_7025A OAT223', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.POM.MEP_F20-03', 'MEP_F20-03', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.POM.DUPONT_DELRIN 100', 'Dupont_Delrin 100', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PPA_55PERCENT_GF.DUPONT_HTNFE170016', 'Dupont_HTNFE170016', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PPA_60PERCENT_GF.DUPONT_HTNFE170023', 'Dupont_HTNFE170023', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PPS_45PERCENT_GF.TORAY_A305M45B', 'Toray_A305M45B', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PPS_50PERCENT_GF.TORAY_A595H', 'Toray_A595H', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PPS_50PERCENT_GF.LG_EGP2500', 'LG_EGP2500', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.PPS_50PERCENT_GF_MD.TORAY_A695H', 'Toray_A695H', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.TPEE .DUPONT_HYTREL_3046', 'Dupont_Hytrel_3046', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.TPEE .DUPONT_HYTREL_3078', 'Dupont_Hytrel_3078', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.TPEE .DUPONT_HYTREL_4056', 'Dupont_Hytrel_4056', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.TPEE .DUPONT_HYTREL_RS30F7', 'Dupont_Hytrel_RS30F7', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.TPEE .DUPONT_HYTREL_RS40F2', 'Dupont_Hytrel_RS40F2', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.TPU.COVESTRO_UDS70AU', 'Covestro_UDS70AU', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.TPU.COVESTRO_IT85AU', 'Covestro_IT85AU', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.TPU.COVESTRO_8785A', 'Covestro_8785A', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.TPU.COVESTRO_1070AU', 'Covestro_1070AU', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.TPU.COVESTRO_5377A', 'Covestro_5377A', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.TPU.COVESTRO_1065AU', 'Covestro_1065AU', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.TPU.HUNTSMAN_AVALON 85AE', 'Huntsman_AVALON 85AE', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.TPU.HUNTSMAN_AVALON 80AE', 'Huntsman_AVALON 80AE', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.TPU.HUNTSMAN_AVALON 75AE', 'Huntsman_AVALON 75AE', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.TPU.HUNTSMAN_AVALON 65AB ', 'Huntsman_AVALON 65AB ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.WEARABLE_PC_NIMO.SABIC_LNP LUBRILOY D20001', 'Sabic_LNP Lubriloy D20001', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.FIRE_TPEE.DUPONT_HTR8813', 'Dupont_HTR8813', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.FIRE_TPEE.DUPONT_HTR8837', 'Dupont_HTR8837', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.HIGHFIRE_PC.TEIJIN_MN-3600H', 'Teijin_MN-3600H', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.NIHO_PC.TEIJIN_L-1225Z100', 'Teijin_L-1225Z100', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.KOSAN_PC.MEP_EFD8000', 'MEP_EFD8000', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.KOSAN_PC.MEP_EFD3304U', 'MEP_EFD3304U', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.PLAST.KOSAN_PC.TEIJIN_ML-1103', 'Teijin_ML-1103', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.NON_AUTO_LOCK_SINGLE.', '', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.NON_AUTO_LOCK_SINGLE_WITH.', '', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.NON_AUTO_LOCK_DOUBLE.', '', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.NON_AUTO_LOCK_DOUBLE_WITH.', '', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.AUTO_LOCK_SINGLE.', '', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.AUTO_LOCK_SINGLE_WITH.', '', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.AUTO_LOCK_DOUBLE.', '', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.AUTO_LOCK_DOUBLE_WITH.', '', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.CYRCLE.', '', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.GUODUON.', '', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.TAI_CAP_GAP.', '', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.DOCKING.', '', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.RISING_KB.', '', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.HINGE.SPECIAL_STRUCTURE.', '', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_25PERCENT_TALC.SABIC_BM5225Y ', 'Sabic_BM5225Y ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_25PERCENT_TALC.TEIJIN_DN-5325B', 'Teijin_DN-5325B', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_25PERCENT_TALC.TEIJIN_DN-5325S', 'Teijin_DN-5325S', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_25PERCENT_TALC_WITH_30PERCENT_PCR.TEIJIN_DN-5325SEF', 'Teijin_DN-5325SEF', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_25PERCENT_TALC_WITH_35PERCENT_PCR.SABIC_RCM6224 ', 'Sabic_RCM6224 ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS.COVESTRO_FR3002', 'Covestro_FR3002', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS.COVESTRO_FR3008', 'Covestro_FR3008', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS.COVESTRO_FR3040', 'Covestro_FR3040', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS.LG_LUPOY GN5001RFD', 'LG_LUPOY GN5001RFD', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS.MEP_MB1800', 'MEP_MB1800', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS.SABIC_CX2244ME', 'Sabic_CX2244ME', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS.SABIC_CX7240', 'Sabic_CX7240', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS.SABIC_CY6120', 'Sabic_CY6120', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS.TEIJIN_TN-7000A', 'Teijin_TN-7000A', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS.TEIJIN_TN-7690A', 'Teijin_TN-7690A', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS.LOTTE_NH-1021', 'LOTTE_NH-1021', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS.LOTTE_NH-1015V', 'LOTTE_NH-1015V', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_WITH_30PERCENT_PCR.COVESTRO_FR630GR', 'Covestro_FR630GR', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_WITH_30PERCENT_PCR.LG_LUPOY ER5001RFA', 'LG_LUPOY ER5001RFA', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_WITH_35PERCENT_PCR.SABIC_RCY6214', 'Sabic_RCY6214', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_12PERCENT_TALC.LG_LUPOY GN5121RF', 'LG_LUPOY GN5121RF', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_12PERCENT_TALC.MEP_TMB1412', 'MEP_TMB1412', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_15PERCENT_TALC.COVESTRO_FR3021', 'Covestro_FR3021', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_15PERCENT_TALC.LG_LUPOY GN5151RFA', 'LG_LUPOY GN5151RFA', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_15PERCENT_TALC.MEP_TMB1615', 'MEP_TMB1615', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_15PERCENT_TALC.SABIC_C7230P', 'Sabic_C7230P', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_15PERCENT_TALC.TEIJIN_TN-3715B', 'Teijin_TN-3715B', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_15PERCENT_TALC.TEIJIN_TN-3715BW', 'Teijin_TN-3715BW', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_15PERCENT_TALC.TEIJIN_TN-3715BX', 'Teijin_TN-3715BX', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_15PERCENT_TALC.TEIJIN_TN-3740B', 'Teijin_TN-3740B', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_15PERCENT_TALC.LOTTE_NH-1150HH', 'LOTTE_NH-1150HH', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_15PERCENT_TALC_WITH_15PERCENT_PCR.TEIJIN_TN 3745BEC', 'Teijin_TN 3745BEC', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_15PERCENT_TALC_WITH_30PERCENT_PCR.COVESTRO_FR3021GR', 'Covestro_FR3021GR', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_15PERCENT_TALC_WITH_30PERCENT_PCR.LG_LUPOY ER5151RFL', 'LG_LUPOY ER5151RFL', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_15PERCENT_TALC_WITH_30PERCENT_PCR.SABIC_RCM6123', 'Sabic_RCM6123', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_15PERCENT_TALC_WITH_30PERCENT_PCR.TEIJIN_TN 3745BEF', 'Teijin_TN 3745BEF', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_23PERCENT_TALC.COVESTRO_FR3023', 'Covestro_FR3023', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_25PERCENT_TALC.COVESTRO_FR3025', 'Covestro_FR3025', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_25PERCENT_TALC.LG_LUPOY GN5254FD', 'LG_LUPOY GN5254FD', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_25PERCENT_TALC_WITH_30PERCENT_PCR.LG_LUPOY ER5254F', 'LG_LUPOY ER5254F', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_25PERCENT_TALC_WITH_35PERCENT_PCR.COVESTRO_FR3025R35', 'Covestro_FR3025R35', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_3PERCENT_TALC.MEP_MB1700', 'MEP_MB1700', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_5PERCENT_TALC.COVESTRO_FR3020', 'Covestro_FR3020', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_5PERCENT_TALC.LG_LUPOY GN5101RF', 'LG_LUPOY GN5101RF', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_5PERCENT_TALC.SABIC_C7210A', 'Sabic_C7210A', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_5PERCENT_TALC.SABIC_C7410', 'Sabic_C7410', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_5PERCENT_TALC.TEIJIN_TN-3713B', 'Teijin_TN-3713B', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_5PERCENT_TALC.TEIJIN_TN-3713BX', 'Teijin_TN-3713BX', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_5PERCENT_TALC.TEIJIN_TN-7100F', 'Teijin_TN-7100F', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_5PERCENT_TALC_WITH_35PERCENT_PCR.SABIC_RCM6134', 'Sabic_RCM6134', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.IMR.PC_ABS_8PERCENT_TALC.SABIC_CM6140', 'Sabic_CM6140', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC.SABIC_EXL1414', 'Sabic_EXL1414', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC.TEIJIN_L-1225L', 'Teijin_L-1225L', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC.TEIJIN_L-1225Y', 'Teijin_L-1225Y', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC.TEIJIN_L-1250Y', 'Teijin_L-1250Y', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC.TEIJIN_LN2520A', 'Teijin_LN2520A', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC.TEIJIN_MN-4800', 'Teijin_MN-4800', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_WITH_25PERCENT_PCR.TEIJIN_MN-3709EE', 'Teijin_MN-3709EE', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_WITH_30PERCENT_PCR.SABIC_RCX7243', 'Sabic_RCX7243', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_NONTRANSFER.MEP_FPR3500 ', 'MEP_FPR3500 ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_NONTRANSFER.MEP_FPL3500', 'MEP_FPL3500', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_25PERCENT_TALC.SABIC_BM5225Y ', 'Sabic_BM5225Y ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_25PERCENT_TALC.TEIJIN_DN-5325B', 'Teijin_DN-5325B', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_25PERCENT_TALC.TEIJIN_DN-5325S', 'Teijin_DN-5325S', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_25PERCENT_TALC_WITH_30PERCENT_PCR.TEIJIN_DN-5325SEF', 'Teijin_DN-5325SEF', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_25PERCENT_TALC_WITH_35PERCENT_PCR.SABIC_RCM6224 ', 'Sabic_RCM6224 ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS.COVESTRO_FR3002', 'Covestro_FR3002', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS.COVESTRO_FR3008', 'Covestro_FR3008', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS.COVESTRO_FR3040', 'Covestro_FR3040', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS.LG_LUPOY GN5001RFD', 'LG_LUPOY GN5001RFD', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS.MEP_MB1800', 'MEP_MB1800', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS.SABIC_CX2244ME', 'Sabic_CX2244ME', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS.SABIC_CX7240', 'Sabic_CX7240', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS.SABIC_CY6120', 'Sabic_CY6120', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS.TEIJIN_TN-7000A', 'Teijin_TN-7000A', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS.TEIJIN_TN-7690A', 'Teijin_TN-7690A', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS.LOTTE_NH-1021', 'LOTTE_NH-1021', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS.LOTTE_NH-1015V', 'LOTTE_NH-1015V', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_WITH_30PERCENT_PCR.COVESTRO_FR630GR', 'Covestro_FR630GR', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_WITH_30PERCENT_PCR.LG_LUPOY ER5001RFA', 'LG_LUPOY ER5001RFA', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_WITH_35PERCENT_PCR.SABIC_RCY6214', 'Sabic_RCY6214', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_HIGHLIGHT.TEIJIN_TN 7050', 'Teijin_TN 7050', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_HIGHLIGHT.TEIJIN_TN 7050Y', 'Teijin_TN 7050Y', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_12PERCENT_TALC.LG_LUPOY GN5121RF', 'LG_LUPOY GN5121RF', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_12PERCENT_TALC.MEP_TMB1412', 'MEP_TMB1412', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_15PERCENT_TALC.COVESTRO_FR3021', 'Covestro_FR3021', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_15PERCENT_TALC.LG_LUPOY GN5151RFA', 'LG_LUPOY GN5151RFA', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_15PERCENT_TALC.MEP_TMB1615', 'MEP_TMB1615', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_15PERCENT_TALC.SABIC_C7230P', 'Sabic_C7230P', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_15PERCENT_TALC.TEIJIN_TN-3715B', 'Teijin_TN-3715B', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_15PERCENT_TALC.TEIJIN_TN-3715BW', 'Teijin_TN-3715BW', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_15PERCENT_TALC.TEIJIN_TN-3715BX', 'Teijin_TN-3715BX', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_15PERCENT_TALC.TEIJIN_TN-3740B', 'Teijin_TN-3740B', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_15PERCENT_TALC.LOTTE_NH-1150HH', 'LOTTE_NH-1150HH', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_15PERCENT_TALC_UVS.COVESTRO_FR3021BBS910', 'Covestro_FR3021BBS910', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_15PERCENT_TALC_UVS.TEIJIN_TN-3715BZ', 'Teijin_TN-3715BZ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_15PERCENT_TALC_WITH_15PERCENT_PCR.TEIJIN_TN 3745BEC', 'Teijin_TN 3745BEC', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_15PERCENT_TALC_WITH_30PERCENT_PCR.COVESTRO_FR3021GR', 'Covestro_FR3021GR', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_15PERCENT_TALC_WITH_30PERCENT_PCR.LG_LUPOY ER5151RFL', 'LG_LUPOY ER5151RFL', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_15PERCENT_TALC_WITH_30PERCENT_PCR.SABIC_RCM6123', 'Sabic_RCM6123', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_15PERCENT_TALC_WITH_30PERCENT_PCR.TEIJIN_TN 3745BEF', 'Teijin_TN 3745BEF', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_23PERCENT_TALC.COVESTRO_FR3023', 'Covestro_FR3023', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_25PERCENT_TALC.COVESTRO_FR3025', 'Covestro_FR3025', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_25PERCENT_TALC.LG_LUPOY GN5254FD', 'LG_LUPOY GN5254FD', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_25PERCENT_TALC_WITH_30PERCENT_PCR.LG_LUPOY ER5254F', 'LG_LUPOY ER5254F', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_25PERCENT_TALC_WITH_35PERCENT_PCR.COVESTRO_FR3025R35', 'Covestro_FR3025R35', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_3PERCENT_TALC.MEP_MB1700', 'MEP_MB1700', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_5PERCENT_TALC.COVESTRO_FR3020', 'Covestro_FR3020', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_5PERCENT_TALC.LG_LUPOY GN5101RF', 'LG_LUPOY GN5101RF', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_5PERCENT_TALC.SABIC_C7210A', 'Sabic_C7210A', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_5PERCENT_TALC.SABIC_C7410', 'Sabic_C7410', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_5PERCENT_TALC.TEIJIN_TN-3713B', 'Teijin_TN-3713B', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_5PERCENT_TALC.TEIJIN_TN-3713BX', 'Teijin_TN-3713BX', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_5PERCENT_TALC.TEIJIN_TN-7100F', 'Teijin_TN-7100F', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_5PERCENT_TALC_UVS.TEIJIN_TN-7200B', 'Teijin_TN-7200B', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_5PERCENT_TALC_WITH_35PERCENT_PCR.SABIC_RCM6134', 'Sabic_RCM6134', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.DOUBL.PC_ABS_8PERCENT_TALC.SABIC_CM6140', 'Sabic_CM6140', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PA_50PERCENT_GF.DUPONT_HTNFR55G50NHLWSF', 'Dupont_HTNFR55G50NHLWSF', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PA1010_55PERCENT_GF.DUPONT_HTN59G55LWSF', 'Dupont_HTN59G55LWSF', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_10PERCENT_GF.SABIC_D151', 'Sabic_D151', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_10PERCENT_GF.TEIJIN_GV-3510R', 'Teijin_GV-3510R', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_10PERCENT_GF_WITH_30PERCENT_PCR.LG_LUPOY ER2102', 'LG_LUPOY ER2102', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_15PERCENT_CF.MEP_CP2015N2', 'MEP_CP2015N2', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_20PERCENT_CF.SABIC_DC0041PQ', 'Sabic_DC0041PQ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_20PERCENT_CF_WITH_30PERCENT_PCR.SABIC_DC0041PR', 'Sabic_DC0041PR', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_20ERCENT_GF.SABIC_D251', 'Sabic_D251', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_20ERCENT_GF.TEIJIN_GV-3520R', 'Teijin_GV-3520R', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_25PERCENT_GF.LG_LUPOY GN2253F', 'LG_LUPOY GN2253F', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_30PERCENT_GF.COVESTRO_GF9016', 'Covestro_GF9016', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_30PERCENT_GF.LG_LUPOY GN2303F', 'LG_LUPOY GN2303F', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_30PERCENT_GF.SABIC_D351  ', 'Sabic_D351  ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_30PERCENT_GF.TEIJIN_GXV-3530UH', 'Teijin_GXV-3530UH', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_35PERCENT_GF_WITH_5PERCENT_TALC.COVESTRO_GF9012MF', 'Covestro_GF9012MF', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_40PERCENT_GF.COVESTRO_GF9018', 'Covestro_GF9018', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_40PERCENT_GF.LG_LUPOY GN2403FT', 'LG_LUPOY GN2403FT', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_40PERCENT_GF.SABIC_D451  ', 'Sabic_D451  ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_40PERCENT_GF.SABIC_D452   ', 'Sabic_D452   ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_40PERCENT_GF.TEIJIN_GN-3540RI', 'Teijin_GN-3540RI', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_40PERCENT_GF_WITH_30PERCENT_PCR.LG_LUPOY ER2403F', 'LG_LUPOY ER2403F', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_45PERCENT_GF.TEIJIN_GXV-3545WI', 'Teijin_GXV-3545WI', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_50PERCENT_GF.COVESTRO_GF9020', 'Covestro_GF9020', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_50PERCENT_GF.LG_LUPOY GN2503F', 'LG_LUPOY GN2503F', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_50PERCENT_GF.SABIC_D551  ', 'Sabic_D551  ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_50PERCENT_GF.TEIJIN_GXV-3550WI', 'Teijin_GXV-3550WI', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_50PERCENT_GF_RECYCLE.COVESTRO_M4004GR', 'Covestro_M4004GR', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_50PERCENT_GF_WITH_20PERCENT_PCR.LG_LUPOY ER2503F', 'LG_LUPOY ER2503F', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_50PERCENT_GF_WITH_30PERCENT_PCR.SABIC_D551RC', 'Sabic_D551RC', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_ABS_HIGHLIGHT.TEIJIN_TN 7050', 'Teijin_TN 7050', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_ABS_HIGHLIGHT.TEIJIN_TN 7050Y', 'Teijin_TN 7050Y', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_ABS_15PERCENT_TALC_UVS.COVESTRO_FR3021BBS910', 'Covestro_FR3021BBS910', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_ABS_15PERCENT_TALC_UVS.TEIJIN_TN-3715BZ', 'Teijin_TN-3715BZ', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_ABS_5PERCENT_TALC_UVS.TEIJIN_TN-7200B', 'Teijin_TN-7200B', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_ABS_PMMA.LG_LUPOY SG-5009FA', 'LG_LUPOY SG-5009FA', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_GF_CF.MEP_BCB992', 'MEP_BCB992', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PC_REDLIGHT.MEP_7025A OAT223', 'MEP_7025A OAT223', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PPA_55PERCENT_GF.DUPONT_HTNFE170016', 'Dupont_HTNFE170016', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PPA_60PERCENT_GF.DUPONT_HTNFE170023', 'Dupont_HTNFE170023', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PPS_45PERCENT_GF.TORAY_A305M45B', 'Toray_A305M45B', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PPS_50PERCENT_GF.TORAY_A595H', 'Toray_A595H', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PPS_50PERCENT_GF.LG_EGP2500', 'LG_EGP2500', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.PPS_50PERCENT_GF_MD.TORAY_A695H', 'Toray_A695H', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.FIRE_PC.TEIJIN_MN-3600H', 'Teijin_MN-3600H', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.NIHO_PC.TEIJIN_L-1225Z100', 'Teijin_L-1225Z100', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.KOSAN_PC.MEP_EFD8000', 'MEP_EFD8000', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.KOSAN_PC.MEP_EFD3304U', 'MEP_EFD3304U', 'material', 'bom_item');
INSERT INTO wiprocurement.drop_down_item (path, item_name, field_name, layout_name) VALUES ('HOUSING.RHCM_.KOSAN_PC.TEIJIN_ML-1103', 'Teijin_ML-1103', 'material', 'bom_item');
