ALTER TABLE wiprocurement.pdmparts
	 ADD COLUMN CLASS character varying(40),
	 ADD COLUMN CURDBNAME character varying(40),
	 ADD COLUMN OBID character varying(48),
	 ADD COLUMN NOMENCLATURE character varying(80),
	 ADD COLUMN GENDESC character varying(120),
	 ADD COLUMN PRODUCTSTATUS character varying(30),
	 ADD COLUMN PROJECTNAME character varying(32),
	 ADD COLUMN MAKEBUYINDICATOR character varying(24),
	 ADD COLUMN PARTSITECODE character varying(1000),
	 ADD COLUMN BIGCLASS character varying(4),
	 ADD COLUMN SAPDIVISION character varying(4),
	 ADD COLUMN PROFITCENTERDISP character varying(200),
	 ADD COLUMN MIDDLECLASS character varying(4),
	 ADD COLUMN SMALLCLASS character varying(20),
	 ADD COLUMN MAJORCODE character varying(6),
	 ADD COLUMN MINORCODE character varying(6),
	 ADD COLUMN OWNERNAME character varying(60),
	 ADD COLUMN ENVSTANDARDSTRING character varying(120),
	 ADD COLUMN MATERIALTYPE character varying(8),
	 ADD COLUMN ECRNO character varying(24),
	 ADD COLUMN AMOUNT numeric,
	 ADD COLUMN CURRENCY character varying(6),
	 ADD COLUMN EQUIVALENTPN character varying(36),
	 ADD COLUMN LASTUPDATE   timestamp with time zone,
	 ADD COLUMN PROFITCENTER character varying(20),
	 ADD COLUMN CUSTOMCONTRACTINFO character varying(200),
	 ADD COLUMN CMS3BONDEDTYPE character varying(4),
	 ADD COLUMN UCCSITECODE character varying(1000),
	 ADD COLUMN PREVENDOR character varying(600),
	 ADD COLUMN VENDORPARTNUMBER character varying(6000),
	 ADD COLUMN RELEASEDATE character varying(60),
	 ADD COLUMN CREATOR character varying(60),
	 ADD COLUMN MOUNTFOREGPINDOC character varying(2),
	 ADD COLUMN STATUS character varying(2),
	 ADD COLUMN INSDATE timestamp with time zone,
   ADD COLUMN update_time timestamp with time zone,
	 ADD COLUMN update_by character varying(20);
