CREATE TABLE wiprocurement.eebom_projects(
	id character varying(150),
	project_code character varying(100),
	customer character varying(20),
	product_type character varying(20),
	project_name character varying(50),
	stage character varying(20),
	version numeric default 0,
	sku character varying(15),
	version_remark character varying(300),
	project_leader character varying(20),
	eedm_version character varying(200),
	edm_version_id uuid,
	is_eedm_version_edit boolean default false,
	plant character varying(50),
	purchasing_organization character varying(200),
	create_time timestamp with time zone default now(),
	caculation_date timestamp with time zone,
	update_time timestamp with time zone default now(),
	approve_time timestamp with time zone,
	is_approved boolean default false,
	approved_by character varying(100) references wiprocurement.user(emplid),
	CONSTRAINT eebom_projects_pkey PRIMARY KEY (id),
	CONSTRAINT project_unique_id UNIQUE (project_code, sku)
);

CREATE TABLE wiprocurement.edm_version(
	id uuid NOT NULL DEFAULT uuid_generate_v1(),
	version character varying(200),
	eebom_project_id character varying(150)  references wiprocurement.eebom_projects(id) ON DELETE CASCADE,
	upload_time character varying(100),
	CONSTRAINT edm_version_id_pkey PRIMARY KEY (id)
);

CREATE TABLE wiprocurement.eebom_detail(
	id uuid NOT NULL DEFAULT uuid_generate_v1(),
	edm_version_id uuid references wiprocurement.edm_version(id) ON DELETE CASCADE,
	type1 character varying(20),
	type2 character varying(20),
	part_number character varying(50),
	description character varying(300),
	manufacturer character varying(100),
	current_price numeric,
	spa numeric,
	lpp numeric,
	currrent_price_adj_percentage numeric,
	ce_cost numeric,
	suggestion_cost numeric,
	remark character varying(300),
	qty numeric,
	sub_total_suggestion_cost numeric,
	vendor character varying(100),
	vendor_part_no character varying(100),
	supply_type character varying(10),
	obs character varying(12),
	module character varying(100),
	is_personal_checked boolean default false,
	is_leader_checked boolean default false,
	is_personal_submitted boolean default false,
	is_leader_submitted boolean default false,
	create_time timestamp with time zone default now(),
	update_time timestamp with time zone default now(),
	CONSTRAINT eebom_detail_pkey PRIMARY KEY (id)
);
