INSERT INTO wiprocurement.ee_assignment (type1, type2, pic, pic_emplid) VALUES ('Packing', 'Others-Non-woven', null, null);
INSERT INTO wiprocurement.ee_assignment (type1, type2, pic, pic_emplid) VALUES ('Packing', 'Carton-Unfolded', null, null);
INSERT INTO wiprocurement.ee_assignment (type1, type2, pic, pic_emplid) VALUES ('Packing', 'Box-Unfolded', null, null);
INSERT INTO wiprocurement.ee_assignment (type1, type2, pic, pic_emplid) VALUES ('Packing', 'EPE', null, null);
INSERT INTO wiprocurement.ee_assignment (type1, type2, pic, pic_emplid) VALUES ('Packing', 'Others', null, null);
INSERT INTO wiprocurement.ee_assignment (type1, type2, pic, pic_emplid) VALUES ('Packing', 'Label', null, null);
INSERT INTO wiprocurement.ee_assignment (type1, type2, pic, pic_emplid) VALUES ('Packing', 'EPS', null, null);
INSERT INTO wiprocurement.ee_assignment (type1, type2, pic, pic_emplid) VALUES ('Packing', 'Bag', null, null);
INSERT INTO wiprocurement.ee_assignment (type1, type2, pic, pic_emplid) VALUES ('Packing', 'Others-Paper', null, null);
INSERT INTO wiprocurement.ee_assignment (type1, type2, pic, pic_emplid) VALUES ('Packing', 'Box', null, null);
INSERT INTO wiprocurement.ee_assignment (type1, type2, pic, pic_emplid) VALUES ('Packing', 'Others-Plastic', null, null);
INSERT INTO wiprocurement.ee_assignment (type1, type2, pic, pic_emplid) VALUES ('Packing', 'Others-Clean Clothes', null, null);
INSERT INTO wiprocurement.ee_assignment (type1, type2, pic, pic_emplid) VALUES ('Packing', 'Pallet', null, null);
INSERT INTO wiprocurement.ee_assignment (type1, type2, pic, pic_emplid) VALUES ('Packing', 'Manual', null, null);
INSERT INTO wiprocurement.ee_assignment (type1, type2, pic, pic_emplid) VALUES ('Packing', 'Carton', null, null);
