values:
  - cableSupportMaterial: 地片1
  - cableSupportMaterial: 地片2
  - cableSupportMaterial: KAPTON1
  - cableSupportMaterial: KAPTON2
  - cableSupportMaterial: 醋酸布
  - cableSupportMaterial: Teflon膠带
  - cableSupportMaterial: 導電布1
  - cableSupportMaterial: 導電布2
  - cableSupportMaterial: UV GLUE
  - cableSupportMaterial: LABEL