const hosuingMetalTemplate = require('../template/hosuingMetalTemplate')
const quotationSetting = require('../../cleanSheetQuotation/dt/housing-metal')

module.exports = {
  cleansheet: [
    hosuingMetalTemplate.cleansheet.material_cost,
    hosuingMetalTemplate.cleansheet.stamping_cost,
    hosuingMetalTemplate.cleansheet.stamping_single_cost,
    hosuingMetalTemplate.cleansheet.secondary_processing_cost,
    hosuingMetalTemplate.cleansheet.cmfProcessListFirstAnode,
    hosuingMetalTemplate.cleansheet.cmfProcessListSecondAnode,
    hosuingMetalTemplate.cleansheet.cmfProcessListSandBlast,
    hosuingMetalTemplate.cleansheet.cmfProcessListHairLine,
    // hosuingMetalTemplate.cleansheet.cmfProcessListPatinting,
    hosuingMetalTemplate.cleansheet.cmfProcessListThermalBonding,
    hosuingMetalTemplate.cleansheet.cmfProcessListSingleTappingDT,
    hosuingMetalTemplate.cleansheet.cmfProcessListSingleSpotWeldingDT,
    hosuingMetalTemplate.cleansheet.cmfProcessListSingleRivetDT,
    hosuingMetalTemplate.cleansheet.cmfProcessListRivet,
    hosuingMetalTemplate.cleansheet.cmfProcessListScreenPrinting,
    hosuingMetalTemplate.cleansheet.cmfProcessListPadPrinting,
    hosuingMetalTemplate.cleansheet.cmfProcessListSilkPrint,
    hosuingMetalTemplate.cleansheet.cmfProcessListCNCDT,
    hosuingMetalTemplate.cleansheet.cmfProcessListLaserPrintDT,
    hosuingMetalTemplate.cleansheet.cmfProcessListPolishingAutoDT,
    hosuingMetalTemplate.cleansheet.cmfProcessListLaserWelding,
    hosuingMetalTemplate.cleansheet.cmfProcessListNormalCleanDT,
    hosuingMetalTemplate.cleansheet.painting_cost,
    hosuingMetalTemplate.cleansheet.profit,
    hosuingMetalTemplate.cleansheet.totalPrices,
  ],
  partlist: [
    hosuingMetalTemplate.partlist.hmmaterial,
    hosuingMetalTemplate.partlist.materialRemark,
    hosuingMetalTemplate.partlist.hmthickness,
    hosuingMetalTemplate.partlist.hmpartssizelength,
    hosuingMetalTemplate.partlist.hmpartssizewidth,
    hosuingMetalTemplate.partlist.hmpartssizehigh,
    hosuingMetalTemplate.partlist.hmpartsexpandlength,
    hosuingMetalTemplate.partlist.hmpartsexpandwidth,
    hosuingMetalTemplate.partlist.hmToolingMaterialExpandLength,
    hosuingMetalTemplate.partlist.hmToolingMaterialExpandWidth,
    hosuingMetalTemplate.partlist.hmToolingMaterialWeight,
    hosuingMetalTemplate.partlist.stamping_single_layout,
    hosuingMetalTemplate.partlist.hmToolingTotalCount,
    hosuingMetalTemplate.partlist.hmToolingRemark,
    hosuingMetalTemplate.partlist.empty,
    hosuingMetalTemplate.partlist.cmfPPainting,
    hosuingMetalTemplate.partlist.cmfProcessListAnode,
    hosuingMetalTemplate.partlist.cmfProcessListSandBlastDT,
    hosuingMetalTemplate.partlist.cmfProcessListHairLine,
    // hosuingMetalTemplate.partlist.cmfProcessListPainting,
    hosuingMetalTemplate.partlist.cmfProcessListThermalBonding,
    hosuingMetalTemplate.partlist.cmfProcessListSingleTappingDT,
    hosuingMetalTemplate.partlist.cmfProcessListSingleSpotWeldingDT,
    hosuingMetalTemplate.partlist.cmfProcessListSingleRivetDT,
    hosuingMetalTemplate.partlist.cmfProcessListRivet,
    hosuingMetalTemplate.partlist.cmfProcessListScreenPrinting,
    hosuingMetalTemplate.partlist.cmfProcessListPadPrinting,
    hosuingMetalTemplate.partlist.cmfProcessListSilkPrint,
    hosuingMetalTemplate.partlist.cmfProcessListCNCDT,
    hosuingMetalTemplate.partlist.cmfProcessListLaserPrintDT,
    hosuingMetalTemplate.partlist.cmfProcessListPolishingDT,
    {
      ...hosuingMetalTemplate.partlist.cmfProcessListLaserWelding,
      style: {
        ...hosuingMetalTemplate.partlist.cmfProcessListLaserWelding.style,
        border: {
          topBorderStyle: 'thin',
          bottomBorderStyle: 'thin',
        },
      },
    },
    {
      ...hosuingMetalTemplate.partlist.cmfProcessListNormalCleanDT,
      style: {
        ...hosuingMetalTemplate.partlist.cmfProcessListNormalCleanDT.style,
        border: {
          topBorderStyle: 'thin',
          bottomBorderStyle: 'thick',
        },
      },
    },
  ],
  quotation: quotationSetting,
}

