const hosuingPlasticTemplate = require('../template/hosuingPlasticTemplate')
const quotationSetting = require('../../cleanSheetQuotation/dt/housing-plastic')

module.exports = {
  cleansheet: [
    hosuingPlasticTemplate.cleansheet.material_cost,
    hosuingPlasticTemplate.cleansheet.forming_cost,
    hosuingPlasticTemplate.cleansheet.painting_cost,
    hosuingPlasticTemplate.cleansheet.secondary_processing_cost,
    hosuingPlasticTemplate.cleansheet.cmfPEmbedNail_cost,
    hosuingPlasticTemplate.cleansheet.cmfPrinting_cost,
    hosuingPlasticTemplate.cleansheet.cmfPCNCProcessingArea_cost,
    hosuingPlasticTemplate.cleansheet.cmfPCNCFeeder_cost,
    hosuingPlasticTemplate.cleansheet.cmfPProductPolishingPL_cost,
    hosuingPlasticTemplate.cleansheet.cmfPHotMelt_cost,
    hosuingPlasticTemplate.cleansheet.cmfPBonding_cost,
    hosuingPlasticTemplate.cleansheet.cmfPEMISputtering_cost,
    hosuingPlasticTemplate.cleansheet.cmfPPolishStressMark_cost,
    hosuingPlasticTemplate.cleansheet.cmfPChipRemoval_cost,
    hosuingPlasticTemplate.cleansheet.cmfPRollingOrDeburring_cost,
    hosuingPlasticTemplate.cleansheet.cmfPLaserMarking_cost,
    hosuingPlasticTemplate.cleansheet.cmfPNCVM_cost,
    hosuingPlasticTemplate.cleansheet.profit,
    hosuingPlasticTemplate.cleansheet.totalPrices,
  ],
  partlist: [
    hosuingPlasticTemplate.partlist.type2,
    hosuingPlasticTemplate.partlist.hpProcess,
    hosuingPlasticTemplate.partlist.hpmaterialspec1,
    hosuingPlasticTemplate.partlist.materialspecRemark,
    hosuingPlasticTemplate.partlist.hpmaterial,
    hosuingPlasticTemplate.partlist.materialRemark,
    hosuingPlasticTemplate.partlist.hpmaterialspec2,
    hosuingPlasticTemplate.partlist.hpmaterial2,
    hosuingPlasticTemplate.partlist.material2Remark,
    hosuingPlasticTemplate.partlist.hpMaterialColor,
    hosuingPlasticTemplate.partlist.hppartssizewidth,
    hosuingPlasticTemplate.partlist.hppartssizelength,
    hosuingPlasticTemplate.partlist.hppartssizehigh,
    hosuingPlasticTemplate.partlist.hpthickness,
    hosuingPlasticTemplate.partlist.hppartweightone,
    hosuingPlasticTemplate.partlist.hppartweighttwo,
    hosuingPlasticTemplate.partlist.hpToolingPartsWeightSpec1,
    hosuingPlasticTemplate.partlist.hpToolingPartsWeightSpec2,
    hosuingPlasticTemplate.partlist.hpToolingMachineTon,
    hosuingPlasticTemplate.partlist.hpToolingHole,
    hosuingPlasticTemplate.partlist.hpToolingCT,
    hosuingPlasticTemplate.partlist.hpToolingRemark,
    hosuingPlasticTemplate.partlist.empty,
    hosuingPlasticTemplate.partlist.cmfPPaintingDT,
    hosuingPlasticTemplate.partlist.cmfPEmbedNail,
    hosuingPlasticTemplate.partlist.cmfPrinting,
    hosuingPlasticTemplate.partlist.cmfPCNCArea,
    hosuingPlasticTemplate.partlist.secondaryProcessing,
  ],
  quotation: quotationSetting,
}

