/* eslint-disable quote-props */
/* eslint-disable quotes */
const data = {
  "initialValue": {
    "hpItem": "P5",
    "hppartname": "Housing Plastic-190620(From PRD -> U-Case_Sideband_FF_Faroe14_SILIVER _YH))",
    "hppartnumber": "T003",
    "hpComponent": "NB-Side_Band",
    "hpProcess": "PAINTING (1C1B)",
    "hpModule": "module1",
    "ce": 0.1,
    "hpmaterial": "MEP_TMB1615",
    "hpPrice": 0,
    "hpmaterialspec1": "PC_ABS_15percent_Talc",
    "hpmaterial2": null,
    "hpMaterialColor": "GY1411 (Pika sliver 派克銀)",
    "hpthickness": "1.7",
    "hppartweightone": "31",
    "hppartweighttwo": 0,
    "hppartssizewidth": "223.85",
    "hppartssizelength": "324.2",
    "hppartssizehigh": "10.8",
    "hpToolingPartsWeightSpec1": 25.3,
    "hpToolingPartsWeightSpec2": 0,
    "hpToolingModuleMode": "熱膠道正灌開放式",
    "hpToolingSizeLength": 660,
    "hpToolingSizeWidth": 760,
    "hpToolingSizeHigh": 620,
    "hpToolingMachineTon": "450T",
    "hpToolingMachinePrice": 0.2118,
    "hpToolingHoleProduct1": 1,
    "hpToolingHoleProduct2": 0,
    "hpToolingCT": 40,
    "hpToolingShrinkRate": 2.5,
    "hpToolingModuleFactory": "重慶 有勝",
    "hpToolingMoldingManufacturer": "重慶 宇海",
    "hpToolingSource": "WCQ",
    "hpToolingBonded": "保稅",
    "hpToolingTSDate": "2018-08-16 ",
    "hpToolingT1Date": "2018-09-17 ",
    "hpToolingRemark": "外觀噴漆UV  \n正確價格為: 2.2859",
    "cmfPPaintingCheckBox": true,
    "cmfPPaintingType": "UV",
    "cmfPPaintingTypeYield": 0,
    "cmfPPaintingPrimerTypeYield": 0.9,
    "cmfPPaintingTopcoatTypeYield": 0.8,
    "cmfPPaintingTypeLoss": 0,
    "cmfPPaintingPrimerTypeLoss": 0.05,
    "cmfPPaintingTopcoatTypeLoss": 0.05,
    "cmfPPaintingColor": "常見顏色例如：黑色；灰色；銀色等 膜厚一般在15～20um",
    "cmfPPaintingVendor": null,
    "cmfPPaintingPrice": 0,
    "cmfPPaintingPrimerPrice": 0,
    "cmfPPaintingTopcoatPrice": 11.2,
    "cmfPPaintingPreprocessor": 0,
    "cmfPPaintingPrimerPreprocessor": 5,
    "cmfPPaintingTopcoatPreprocessor": 5,
    "cmfPPaintingGrinder": 0,
    "cmfPPaintingPrimerGrinder": 3,
    "cmfPPaintingTopcoatGrinder": 3,
    "cmfPPaintingPainter": 0,
    "cmfPPaintingPrimerPainter": 3,
    "cmfPPaintingTopcoatPainter": 3,
    "cmfPPaintingValidator": 0,
    "cmfPPaintingPrimerValidator": 3,
    "cmfPPaintingTopcoatValidator": 3,
    "cmfPPaintingLaborCost": 0,
    "cmfPPaintingPrimerLaborCost": 0.04,
    "cmfPPaintingTopcoatLaborCost": 0.04,
    "cmfPInch": 0,
    "cmfPLengthOutside": 325,
    "cmfPWidthOutside": 224,
    "cmfPLengthInside": 0,
    "cmfPWidthInside": 0,
    "cmfPPrimerQTY": 0,
    "cmfPPrimerThickness": 0,
    "cmfPTopcoatQTY": 1,
    "cmfPTopcoatThickness": 0.02,
    "cmfPHotMeltCheckBox": false,
    "cmfPHotMeltCount": 0,
    "cmfPEmbedNailCheckBox": false,
    "cmfPEmbedNailCount": 0,
    "cmfPEmbedNailAuto": null,
    "cmfPScreenPrintingCheckBox": false,
    "cmfPScreenPrintingCount": 0,
    "cmfPPadPrintingCheckBox": true,
    "cmfPPadPrintingCount": 4,
    "cmfPCNCFeederCheckBox": false,
    "cmfPCNCFeederCount": 0,
    "cmfPEMISputteringCheckBox": false,
    "cmfPEMISputteringCount": 0,
    "cmfPrice": 0.45
  },
  "Price": {
    "housingPlastic": {
      "hpItem": "P5",
      "hppartname": "Housing Plastic-190620(From PRD -> U-Case_Sideband_FF_Faroe14_SILIVER _YH))",
      "hppartnumber": "T003",
      "hpComponent": "NB-Side_Band",
      "hpProcess": "PAINTING (1C1B)",
      "hpModule": "module1",
      "ce": 0.1,
      "hpmaterial": "MEP_TMB1615",
      "hpPrice": 0,
      "hpmaterialspec1": "PC_ABS_15percent_Talc",
      "hpmaterial2": null,
      "hpMaterialColor": "GY1411 (Pika sliver 派克銀)",
      "hpthickness": "1.7",
      "hppartweightone": "31",
      "hppartweighttwo": 0,
      "hppartssizewidth": "223.85",
      "hppartssizelength": "324.2",
      "hppartssizehigh": "10.8",
      "hpToolingPartsWeightSpec1": 25.3,
      "hpToolingPartsWeightSpec2": 0,
      "hpToolingModuleMode": "熱膠道正灌開放式",
      "hpToolingSizeLength": 660,
      "hpToolingSizeWidth": 760,
      "hpToolingSizeHigh": 620,
      "hpToolingMachineTon": "450T",
      "hpToolingMachinePrice": 0.2118,
      "hpToolingHoleProduct1": 1,
      "hpToolingHoleProduct2": 0,
      "hpToolingCT": 40,
      "hpToolingShrinkRate": 2.5,
      "hpToolingModuleFactory": "重慶 有勝",
      "hpToolingMoldingManufacturer": "重慶 宇海",
      "hpToolingSource": "WCQ",
      "hpToolingBonded": "保稅",
      "hpToolingTSDate": "2018-08-16 ",
      "hpToolingT1Date": "2018-09-17 ",
      "hpToolingRemark": "外觀噴漆UV  \n正確價格為: 2.2859",
      "cmfPPaintingCheckBox": true,
      "cmfPPaintingType": "UV",
      "cmfPPaintingTypeYield": 0,
      "cmfPPaintingPrimerTypeYield": 0.9,
      "cmfPPaintingTopcoatTypeYield": 0.8,
      "cmfPPaintingTypeLoss": 0,
      "cmfPPaintingPrimerTypeLoss": 0.05,
      "cmfPPaintingTopcoatTypeLoss": 0.05,
      "cmfPPaintingColor": "常見顏色例如：黑色；灰色；銀色等 膜厚一般在15～20um",
      "cmfPPaintingVendor": null,
      "cmfPPaintingPrice": 0,
      "cmfPPaintingPrimerPrice": 0,
      "cmfPPaintingTopcoatPrice": 11.2,
      "cmfPPaintingPreprocessor": 0,
      "cmfPPaintingPrimerPreprocessor": 5,
      "cmfPPaintingTopcoatPreprocessor": 5,
      "cmfPPaintingGrinder": 0,
      "cmfPPaintingPrimerGrinder": 3,
      "cmfPPaintingTopcoatGrinder": 3,
      "cmfPPaintingPainter": 0,
      "cmfPPaintingPrimerPainter": 3,
      "cmfPPaintingTopcoatPainter": 3,
      "cmfPPaintingValidator": 0,
      "cmfPPaintingPrimerValidator": 3,
      "cmfPPaintingTopcoatValidator": 3,
      "cmfPPaintingLaborCost": 0,
      "cmfPPaintingPrimerLaborCost": 0.04,
      "cmfPPaintingTopcoatLaborCost": 0.04,
      "cmfPInch": 0,
      "cmfPLengthOutside": 325,
      "cmfPWidthOutside": 224,
      "cmfPLengthInside": 0,
      "cmfPWidthInside": 0,
      "cmfPPrimerQTY": 0,
      "cmfPPrimerThickness": 0,
      "cmfPTopcoatQTY": 1,
      "cmfPTopcoatThickness": 0.02,
      "cmfPHotMeltCheckBox": false,
      "cmfPHotMeltCount": 0,
      "cmfPEmbedNailCheckBox": false,
      "cmfPEmbedNailCount": 0,
      "cmfPEmbedNailAuto": null,
      "cmfPScreenPrintingCheckBox": false,
      "cmfPScreenPrintingCount": 0,
      "cmfPPadPrintingCheckBox": true,
      "cmfPPadPrintingCount": 4,
      "cmfPCNCFeederCheckBox": false,
      "cmfPCNCFeederCount": 0,
      "cmfPEMISputteringCheckBox": false,
      "cmfPEMISputteringCount": 0,
      "cmfPrice": 0.45
    }
  },
  "Images": []
};

export default data;
