module.exports = {
  adder: [
    {
      uuid: 1,
      spec: 'SPEC06',
      referencevalue: '<=15',
      percentage: 0.1,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 2,
      spec: 'SPEC06',
      referencevalue: '>15',
      percentage: 0.2,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 3,
      spec: 'SPEC09',
      referencevalue: 'Y',
      percentage: 0.1,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 3,
      spec: 'SPEC02',
      referencevalue: '=4',
      percentage: 0.1,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 4,
      spec: 'SPEC09',
      referencevalue: 'Y',
      percentage: 0.05,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 4,
      spec: 'SPEC02',
      referencevalue: '=6',
      percentage: 0.05,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 5,
      spec: 'SPEC09',
      referencevalue: 'Y',
      percentage: 0.05,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 5,
      spec: 'SPEC02',
      referencevalue: '=8',
      percentage: 0.05,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 6,
      spec: 'SPEC13',
      reference: 'Line_space',
      referencevalue: '<=3',
      percentage: 0.15,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 6,
      spec: 'SPEC13',
      reference: 'Line_width',
      referencevalue: '<=3.5',
      percentage: 0.15,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 7,
      spec: 'SPEC13',
      reference: 'Line_space',
      referencevalue: '<=3.5',
      percentage: 0.05,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 7,
      spec: 'SPEC13',
      reference: 'Line_width',
      referencevalue: '<=3.5',
      percentage: 0.05,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 8,
      spec: 'SPEC13',
      reference: 'Line_space',
      referencevalue: '<=3.5',
      percentage: 0.05,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 8,
      spec: 'SPEC13',
      reference: 'Line_width',
      referencevalue: '<=4',
      percentage: 0.05,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 9,
      spec: 'SPEC14',
      referencevalue: '<8',
      percentage: 0.05,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 10,
      spec: 'SPEC19',
      referencevalue: 'Intel CPU',
      percentage: 0.05,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 11,
      spec: 'SPEC19',
      referencevalue: '6L/T=1.6mm',
      percentage: 0.15,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 12,
      spec: 'SPEC19',
      referencevalue: 'V-CUT',
      percentage: 0.05,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 13,
      spec: 'SPEC19',
      referencevalue: 'PP Sheet*1',
      percentage: 0.02,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 14,
      spec: 'SPEC19',
      referencevalue: 'PP Sheet*2',
      percentage: 0.04,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 15,
      spec: 'SPEC15',
      referencevalue: 'Green',
      percentage: 0,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 16,
      spec: 'SPEC15',
      referencevalue: 'Red',
      percentage: 0.08,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 17,
      spec: 'SPEC15',
      referencevalue: 'Black',
      percentage: 0.10,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 18,
      spec: 'SPEC15',
      referencevalue: 'Blue',
      percentage: 0.03,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 19,
      spec: 'SPEC15',
      referencevalue: 'Brown',
      percentage: 0.10,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 20,
      spec: 'SPEC08',
      referencevalue: 'ENIG',
      percentage: 0.20,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 21,
      spec: 'SPEC08',
      referencevalue: 'OSP+ENIG',
      percentage: 0.25,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 22,
      spec: 'SPEC08',
      referencevalue: 'OSP+ENIG+Goldplating',
      percentage: 0.40,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 23,
      spec: 'SPEC08',
      referencevalue: 'OSP',
      percentage: 0,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 24,
      spec: 'SPEC20',
      referencevalue: '3mil_1oz/1oz',
      percentage: 0.10,
      manufacturer: 'HANNSTAR',
    },
    {
      uuid: 25,
      spec: 'SPEC20',
      referencevalue: 'Ink yellow',
      percentage: 0.05,
      manufacturer: 'HANNSTAR',
    },
  ],
  usd: [],
}
