/* eslint-disable quote-props */
/* eslint-disable quotes */
const data = {
  "initialValue": {
    "Fan_fanLabel": "Fan",
    "Fan_fanAmount": 1,
    "Fan_fanType": "Cross Flow Fan(橫流扇)",
    "Fan_fanSize": "60*60*5",
    "Fan_fanSizePrice": 2.5,
    "Fan_motorArchitecture": "3_phase_H>=5.0",
    "Fan_motorArchitecturePrice": 0.25,
    "Fan_bearingAndSleeve": "Sleeve+金屬_H<=7.5",
    "Fan_bearingAndSleevePrice": 0,
    "Fan_fanBladeMaterial": "LCP_H>=6",
    "Fan_fanBladeMaterialPrice": 0.15,
    "Fan_magnetMaterialAndSize": "MQ_H<= 5.5",
    "Fan_magnetMaterialAndSizePrice": 0.1,
    "Fan_hasHalogen": false,
    "Fan_fanAppearanceProcess1": "塗黑",
    "Fan_fanAppearanceProcess2_fanAppearanceProcess2": null,
    "Pipe_pipeLabel": "Pipe",
    "Pipe_pipeAmount": 1,
    "Pipe_pipeType": "Powder(結燒管)",
    "Pipe_outerDiameter": "PD6_",
    "Pipe_pipeLength": 255,
    "Pipe_pipiLenThickODiaToCost": 0,
    "Pipe_pipiLenODiaToCost": 0,
    "Pipe_pipeFlatteningThickness": 2.4,
    "Pipe_pipiFlThickODiaToCost": 0,
    "Pipe_pipeAppearanceProcess1": null,
    "Pipe_pipeAppearanceProcess2": null,
    "Fin_finLabel": "Fin",
    "Fin_finAmount": 1,
    "Fin_finMaterial": "CU1100",
    "Fin_finPitch": 1.5,
    "Fin_finProductionLength": 60,
    "Fin_finProductionWidth": 10,
    "Fin_finProductionHigh": 4.2,
    "Fin_finProductionExpandLength": 12.2,
    "Fin_finProductionExpandWidth": 20,
    "Fin_finMaterialCostPerKilogram": 8.6,
    "Fin_finDensity": 0,
    "Fin_finMaterialThickness": 0.1,
    "Fin_finNickelPlating": true,
    "Fin_finAppearanceProcess1": null,
    "Fin_finAppearanceProcess2": null,
    "ThermalPlate_thPlLabel": "CPU",
    "ThermalPlate_thPlAmount": 1,
    "ThermalPlate_thPlMaterial": "KU400",
    "ThermalPlate_thPlMaterialCostPerKilogram": 1.5,
    "ThermalPlate_thPlMaterialThickness": 0.5,
    "ThermalPlate_thPlProductionLength": 0,
    "ThermalPlate_thPlProductionWidth": 0,
    "ThermalPlate_thPlProductionHigh": 0,
    "ThermalPlate_thPlProductionExpandLength": 69,
    "ThermalPlate_thPlProductionExpandWidth": 35.9,
    "ThermalPlate_thPlNickelPlating": true,
    "ThermalPlate_thPlAppearanceProcess1": null,
    "ThermalPlate_thPlAppearanceProcess2": null,
    "ThermalPlate_thPlDensity": 0,
    "ThermalBlock_thBlLabel": "CPU",
    "ThermalBlock_thBlAmount": 1,
    "ThermalBlock_thBlMaterial": "CU1100",
    "ThermalBlock_thBlMaterialCostPerKilogram": 8.2,
    "ThermalBlock_thBlMaterialThickness": 0.5,
    "ThermalBlock_thBlProductionLength": 42,
    "ThermalBlock_thBlProductionWidth": 24,
    "ThermalBlock_thBlNickelPlating": false,
    "ThermalBlock_thBlDensity": 0,
    "Screw_screwLabel": "Screw",
    "Screw_screwAmount": 7,
    "Screw_screwToothpath": 2.5,
    "Screw_screwHeadDiameter": 5,
    "Screw_screwHeadThickness": 0.8,
    "Screw_screwLength": 6,
    "Screw_screwPolishedRod": true,
    "Screw_screwNeckDiameter": 0,
    "Screw_screwNeckLength": 0,
    "Screw_screwResistantFall": true,
    "Spring_springLabel": "Spring",
    "Spring_springAmount": 7,
    "Spring_springWireDiameter": 0.45,
    "Spring_springCoilCenterDiameter": 4.3,
    "Spring_springFreeLong": 3.3,
    "ORing_oRLabel": "O-Ring",
    "ORing_oRAmount": 7,
    "ORing_oROuterDiameter": 5.6,
    "ORing_oRInnerDiameter": 2.5,
    "ORing_oRThickness": 0.35,
    "Clip_clipLabel": "Clip",
    "Clip_clipAmount": 2,
    "Clip_clipMaterial": "KU400",
    "Clip_clipMaterialCostPerKilogram": 1.5,
    "Clip_clipWireDiameter": 0,
    "Clip_clipProductionLength": 0,
    "Clip_clipProductionWidth": 0,
    "PushPin_pupiLabel": "Push Pin",
    "PushPin_pupiAmount": 0,
    "PushPin_pupiLength": 0,
    "PushPin_pupiHeadDiameter": 0,
    "Label_labelLabel": "Label",
    "Label_labelAmount": 0,
    "Label_labelLength": 0,
    "Label_labelWidth": 0,
    "Label_labelThickness": 0,
    "Sponge_spongeLabel": "Sponge",
    "Sponge_spongeAmount": 1,
    "Sponge_spongeMaterial": "E4382",
    "Sponge_spongeLength": 13.5,
    "Sponge_spongeWidth": 4.2,
    "Sponge_spongeMaterialThickness": 0.5,
    "Sponge_spongeMaterialCostPerMM": 4.92,
    "Grease_greaseLabel": "Grease",
    "Grease_greaseAmount": 2,
    "Grease_greaseMaterial": 7783,
    "Grease_greaseMaterialCost": 490,
    "Grease_greaseLength": 37,
    "Grease_greaseWidth": 14,
    "Grease_greaseThickness": 0.2,
    "ThermalPad_thermalPadLabel": "Thermal Plad",
    "ThermalPad_thermalPadAmount": 1,
    "ThermalPad_thermalPadHeatTransferCoefficient": 3,
    "ThermalPad_thermalPadShore": 42,
    "ThermalPad_thermalPadThickness": 1,
    "ThermalPad_thermalPadLength": 9,
    "ThermalPad_thermalPadWidth": 6,
    "ThermalPad_thermalPadPrice": 121,
    "Sponge-63d07302-ebd7-4b8a-8175-0246a1def253_spongeLabel": "Sponge",
    "Sponge-63d07302-ebd7-4b8a-8175-0246a1def253_spongeAmount": 1,
    "Sponge-63d07302-ebd7-4b8a-8175-0246a1def253_spongeMaterial": "E4382",
    "Sponge-63d07302-ebd7-4b8a-8175-0246a1def253_spongeLength": 12.1,
    "Sponge-63d07302-ebd7-4b8a-8175-0246a1def253_spongeWidth": 3.8,
    "Sponge-63d07302-ebd7-4b8a-8175-0246a1def253_spongeMaterialThickness": 1.5,
    "Sponge-63d07302-ebd7-4b8a-8175-0246a1def253_spongeMaterialCostPerMM": 7.38,
    "Sponge-269e95c8-41fe-404f-a3e9-473a938b7986_spongeLabel": "Sponge",
    "Sponge-269e95c8-41fe-404f-a3e9-473a938b7986_spongeAmount": 4,
    "Sponge-269e95c8-41fe-404f-a3e9-473a938b7986_spongeMaterial": "E4382",
    "Sponge-269e95c8-41fe-404f-a3e9-473a938b7986_spongeLength": 13.5,
    "Sponge-269e95c8-41fe-404f-a3e9-473a938b7986_spongeWidth": 4,
    "Sponge-269e95c8-41fe-404f-a3e9-473a938b7986_spongeMaterialThickness": 1.5,
    "Sponge-269e95c8-41fe-404f-a3e9-473a938b7986_spongeMaterialCostPerMM": 7.38,
    "Sponge-c391f9b6-97df-4ce9-95fc-38f765d62bda_spongeLabel": "Sponge",
    "Sponge-c391f9b6-97df-4ce9-95fc-38f765d62bda_spongeAmount": 2,
    "Sponge-c391f9b6-97df-4ce9-95fc-38f765d62bda_spongeMaterial": "E4382",
    "Sponge-c391f9b6-97df-4ce9-95fc-38f765d62bda_spongeLength": 11,
    "Sponge-c391f9b6-97df-4ce9-95fc-38f765d62bda_spongeWidth": 4,
    "Sponge-c391f9b6-97df-4ce9-95fc-38f765d62bda_spongeMaterialThickness": 2.5,
    "Sponge-c391f9b6-97df-4ce9-95fc-38f765d62bda_spongeMaterialCostPerMM": 12.3,
    "Grease-52b8a4c2-2c3a-4340-9efc-832526cf3d53_greaseLabel": "Grease",
    "Grease-52b8a4c2-2c3a-4340-9efc-832526cf3d53_greaseAmount": 1,
    "Grease-52b8a4c2-2c3a-4340-9efc-832526cf3d53_greaseMaterial": 7783,
    "Grease-52b8a4c2-2c3a-4340-9efc-832526cf3d53_greaseMaterialCost": 490,
    "Grease-52b8a4c2-2c3a-4340-9efc-832526cf3d53_greaseLength": 12,
    "Grease-52b8a4c2-2c3a-4340-9efc-832526cf3d53_greaseWidth": 10,
    "Grease-52b8a4c2-2c3a-4340-9efc-832526cf3d53_greaseThickness": 0.2
  },
  "Price": {
    "thermalModule": {
      "Fan": {
        "fanLabel": "Fan",
        "fanAmount": 1,
        "fanType": "Cross Flow Fan(橫流扇)",
        "fanSize": "60*60*5",
        "fanSizePrice": 2.5,
        "motorArchitecture": "3_phase_H>=5.0",
        "motorArchitecturePrice": 0.25,
        "bearingAndSleeve": "Sleeve+金屬_H<=7.5",
        "bearingAndSleevePrice": 0,
        "fanBladeMaterial": "LCP_H>=6",
        "fanBladeMaterialPrice": 0.15,
        "magnetMaterialAndSize": "MQ_H<= 5.5",
        "magnetMaterialAndSizePrice": 0.1,
        "hasHalogen": false,
        "fanAppearanceProcess1": "塗黑",
        "fanAppearanceProcess2": null
      },
      "Pipe": {
        "pipeLabel": "Pipe",
        "pipeAmount": 1,
        "pipeType": "Powder(結燒管)",
        "outerDiameter": "PD6_",
        "pipeLength": 255,
        "pipiLenThickODiaToCost": 0,
        "pipiLenODiaToCost": 0,
        "pipeFlatteningThickness": 2.4,
        "pipiFlThickODiaToCost": 0,
        "pipeAppearanceProcess1": null,
        "pipeAppearanceProcess2": null
      },
      "Fin": {
        "finLabel": "Fin",
        "finAmount": 1,
        "finMaterial": "CU1100",
        "finPitch": 1.5,
        "finProductionLength": 60,
        "finProductionWidth": 10,
        "finProductionHigh": 4.2,
        "finProductionExpandLength": 12.2,
        "finProductionExpandWidth": 20,
        "finMaterialCostPerKilogram": 8.6,
        "finDensity": 0,
        "finMaterialThickness": 0.1,
        "finNickelPlating": true,
        "finAppearanceProcess1": null,
        "finAppearanceProcess2": null
      },
      "ThermalPlate": {
        "thPlLabel": "CPU",
        "thPlAmount": 1,
        "thPlMaterial": "KU400",
        "thPlMaterialCostPerKilogram": 1.5,
        "thPlMaterialThickness": 0.5,
        "thPlProductionLength": 0,
        "thPlProductionWidth": 0,
        "thPlProductionHigh": 0,
        "thPlProductionExpandLength": 69,
        "thPlProductionExpandWidth": 35.9,
        "thPlNickelPlating": true,
        "thPlAppearanceProcess1": null,
        "thPlAppearanceProcess2": null,
        "thPlDensity": 0
      },
      "ThermalBlock": {
        "thBlLabel": "CPU",
        "thBlAmount": 1,
        "thBlMaterial": "CU1100",
        "thBlMaterialCostPerKilogram": 8.2,
        "thBlMaterialThickness": 0.5,
        "thBlProductionLength": 42,
        "thBlProductionWidth": 24,
        "thBlNickelPlating": false,
        "thBlDensity": 0
      },
      "Screw": {
        "screwLabel": "Screw",
        "screwAmount": 7,
        "screwToothpath": 2.5,
        "screwHeadDiameter": 5,
        "screwHeadThickness": 0.8,
        "screwLength": 6,
        "screwPolishedRod": true,
        "screwNeckDiameter": 0,
        "screwNeckLength": 0,
        "screwResistantFall": true
      },
      "Spring": {
        "springLabel": "Spring",
        "springAmount": 7,
        "springWireDiameter": 0.45,
        "springCoilCenterDiameter": 4.3,
        "springFreeLong": 3.3
      },
      "ORing": {
        "oRLabel": "O-Ring",
        "oRAmount": 7,
        "oROuterDiameter": 5.6,
        "oRInnerDiameter": 2.5,
        "oRThickness": 0.35
      },
      "Clip": {
        "clipLabel": "Clip",
        "clipAmount": 2,
        "clipMaterial": "KU400",
        "clipMaterialCostPerKilogram": 1.5,
        "clipWireDiameter": 0,
        "clipProductionLength": 0,
        "clipProductionWidth": 0
      },
      "PushPin": {
        "pupiLabel": "Push Pin",
        "pupiAmount": 0,
        "pupiLength": 0,
        "pupiHeadDiameter": 0
      },
      "Label": {
        "labelLabel": "Label",
        "labelAmount": 0,
        "labelLength": 0,
        "labelWidth": 0,
        "labelThickness": 0
      },
      "Sponge": {
        "spongeLabel": "Sponge",
        "spongeAmount": 1,
        "spongeMaterial": "E4382",
        "spongeLength": 13.5,
        "spongeWidth": 4.2,
        "spongeMaterialThickness": 0.5,
        "spongeMaterialCostPerMM": 4.92
      },
      "Grease": {
        "greaseLabel": "Grease",
        "greaseAmount": 2,
        "greaseMaterial": 7783,
        "greaseMaterialCost": 490,
        "greaseLength": 37,
        "greaseWidth": 14,
        "greaseThickness": 0.2
      },
      "ThermalPad": {
        "thermalPadLabel": "Thermal Plad",
        "thermalPadAmount": 1,
        "thermalPadHeatTransferCoefficient": 3,
        "thermalPadShore": 42,
        "thermalPadThickness": 1,
        "thermalPadLength": 9,
        "thermalPadWidth": 6,
        "thermalPadPrice": 121
      },
      "ThermalPadMultiImage": {},
      "Sponge-63d07302-ebd7-4b8a-8175-0246a1def253": {
        "spongeLabel": "Sponge",
        "spongeAmount": 1,
        "spongeMaterial": "E4382",
        "spongeLength": 12.1,
        "spongeWidth": 3.8,
        "spongeMaterialThickness": 1.5,
        "spongeMaterialCostPerMM": 7.38
      },
      "Sponge-269e95c8-41fe-404f-a3e9-473a938b7986": {
        "spongeLabel": "Sponge",
        "spongeAmount": 4,
        "spongeMaterial": "E4382",
        "spongeLength": 13.5,
        "spongeWidth": 4,
        "spongeMaterialThickness": 1.5,
        "spongeMaterialCostPerMM": 7.38
      },
      "Sponge-c391f9b6-97df-4ce9-95fc-38f765d62bda": {
        "spongeLabel": "Sponge",
        "spongeAmount": 2,
        "spongeMaterial": "E4382",
        "spongeLength": 11,
        "spongeWidth": 4,
        "spongeMaterialThickness": 2.5,
        "spongeMaterialCostPerMM": 12.3
      },
      "Grease-52b8a4c2-2c3a-4340-9efc-832526cf3d53": {
        "greaseLabel": "Grease",
        "greaseAmount": 1,
        "greaseMaterial": 7783,
        "greaseMaterialCost": 490,
        "greaseLength": 12,
        "greaseWidth": 10,
        "greaseThickness": 0.2
      }
    }
  },
  "Images": []
};

export default data;
