const { expect } = require('chai')
const sinon = require('sinon')

const reportService = require('../../../../server/service/spending/report.js')
const reportModel = require('../../../../server/model/spending/report.js')
const spendingModel = require('../../../../server/model/spending/spending.js')

describe('report', () => {
  describe('gen raw data', () => {
    it('test raw data report', async () => {
      let requestData = { user: ['S87', 'S46', 'SH3', 'S20', 'S06', 'SA2', 'S56'],
        plant: ['F130', 'F131', 'F135', 'F132', 'F138', 'F136', 'F230'],
        dateFrom: '2017-01-01',
        dateTo: '2017-01-02',
        type1:
       ['Antenna',
         'Cable',
         'EMC',
         'Electro-Mechanical',
         'Housing',
         'ME-Others',
         'Memory',
         'Module',
         'NOR Flash',
         'Power IC',
         'Sensor',
         'Thermal'],
        type2:
       ['External Cable',
         'FFC',
         'FIO',
         'FPC',
         'Other',
         'Power Cord',
         'Mic',
         'Buzzer',
         'Aluminum',
         'Speaker'],
        supplyType: [1, 3, 11, 13, 14, 15],
        category: 'none',
        measure: 'amount',
        currency: 'USD' }
      sinon.stub(reportModel, 'getSpendingBase').withArgs(
        { user: ['S87', 'S46', 'SH3', 'S20', 'S06', 'SA2', 'S56'],
          plant: ['F130', 'F131', 'F135', 'F132', 'F138', 'F136', 'F230'],
          dateFrom: '2017-01-01',
          dateTo: '2017-01-10',
          type1:
       ['Antenna',
         'Cable',
         'EMC',
         'Electro-Mechanical',
         'Housing',
         'ME-Others',
         'Memory',
         'Module',
         'NOR Flash',
         'Power IC',
         'Sensor',
         'Thermal'],
          type2:
       ['External Cable',
         'FFC',
         'FIO',
         'FPC',
         'Other',
         'Power Cord',
         'Mic',
         'Buzzer',
         'Aluminum',
         'Speaker'],
          supplyType: [1, 3, 11, 13, 14, 15],
          category: 'none',
          measure: 'amount',
          currency: 'USD' }).returns([{ plant: 'F130',
        vendorcode: '0000619884',
        materialnumber: '27.01518.0J1',
        material_desc: 'POWER CORD 1800MM 250V EURO',
        currency: 'RMB',
        po_price: '4.5290000000000000',
        inforecord: '5302473867',
        quantity: '200.000',
        date: '2017-01-20T16:00:00.000Z',
        sourcer: 'S46',
        po_no: '0013460231',
        profit_center: 'PCP100',
        brand: 'ISHENG',
        usd_amount: 905.8,
        exchange_rate: '1.00000',
        supply_type: 'W',
        odmoem: 'ODM',
        type1: 'Cable',
        type2: 'Power Cord',
        vendor_base: 'ISHENG',
        vendor_group: 'ISHENG',
        short_name: 'ISHENG',
        vendor_name: '鎰勝電子(深圳)有限公司',
        site: 'WZS-3',
        product_name: 'CP-DT',
        bu2_description: 'BU I-DT-ANNIE',
        sourcername: 'Eve Wang',
        buyername: 'Yingzhen Ouyang',
        buyer: 'AC0' },
      { plant: 'F130',
        vendorcode: '0000619884',
        materialnumber: '27.01518.0J1',
        material_desc: 'POWER CORD 1800MM 250V EURO',
        currency: 'RMB',
        po_price: '4.5290000000000000',
        inforecord: '5302473867',
        quantity: '200.000',
        date: '2017-01-20T16:00:00.000Z',
        sourcer: 'S46',
        po_no: '0013460231',
        profit_center: 'PCP100',
        brand: 'ISHENG',
        usd_amount: 905.8,
        exchange_rate: '1.00000',
        supply_type: 'W',
        odmoem: 'ODM',
        type1: 'Cable',
        type2: 'Power Cord',
        vendor_base: 'ISHENG',
        vendor_group: 'ISHENG',
        short_name: 'ISHENG',
        vendor_name: '鎰勝電子(深圳)有限公司',
        site: 'WZS-3',
        product_name: 'CP-DT',
        bu2_description: 'BU I-DT-ANNIE',
        sourcername: 'Eve Wang',
        buyername: 'Yingzhen Ouyang',
        buyer: 'AC0' },
      ]).withArgs({ user: ['S87', 'S46', 'SH3', 'S20', 'S06', 'SA2', 'S56'],
        plant: ['F130', 'F131', 'F135', 'F132', 'F138', 'F136', 'F230'],
        dateFrom: '2017-01-11',
        dateTo: '2017-01-20',
        type1:
       ['Antenna',
         'Cable',
         'EMC',
         'Electro-Mechanical',
         'Housing',
         'ME-Others',
         'Memory',
         'Module',
         'NOR Flash',
         'Power IC',
         'Sensor',
         'Thermal'],
        type2:
       ['External Cable',
         'FFC',
         'FIO',
         'FPC',
         'Other',
         'Power Cord',
         'Mic',
         'Buzzer',
         'Aluminum',
         'Speaker'],
        supplyType: [1, 3, 11, 13, 14, 15],
        category: 'none',
        measure: 'amount',
        currency: 'USD' }).returns(
        [{ plant: 'F130',
          vendorcode: '0000619884',
          materialnumber: '27.01518.0J1',
          material_desc: 'POWER CORD 1800MM 250V EURO',
          currency: 'RMB',
          po_price: '4.5290000000000000',
          inforecord: '5302473867',
          quantity: '200.000',
          date: '2017-01-20T16:00:00.000Z',
          sourcer: 'S46',
          po_no: '0013460231',
          profit_center: 'PCP100',
          brand: 'ISHENG',
          usd_amount: 905.8,
          exchange_rate: '1.00000',
          supply_type: 'W',
          odmoem: 'ODM',
          type1: 'Cable',
          type2: 'Power Cord',
          vendor_base: 'ISHENG',
          vendor_group: 'ISHENG',
          short_name: 'ISHENG',
          vendor_name: '鎰勝電子(深圳)有限公司',
          site: 'WZS-3',
          product_name: 'CP-DT',
          bu2_description: 'BU I-DT-ANNIE',
          sourcername: 'Eve Wang',
          buyername: 'Yingzhen Ouyang',
          buyer: 'AC0' },
        { plant: 'F130',
          vendorcode: '0000619884',
          materialnumber: '27.01518.0J1',
          material_desc: 'POWER CORD 1800MM 250V EURO',
          currency: 'RMB',
          po_price: '4.5290000000000000',
          inforecord: '5302473867',
          quantity: '200.000',
          date: '2017-01-20T16:00:00.000Z',
          sourcer: 'S46',
          po_no: '0013460231',
          profit_center: 'PCP100',
          brand: 'ISHENG',
          usd_amount: 905.8,
          exchange_rate: '1.00000',
          supply_type: 'W',
          odmoem: 'ODM',
          type1: 'Cable',
          type2: 'Power Cord',
          vendor_base: 'ISHENG',
          vendor_group: 'ISHENG',
          short_name: 'ISHENG',
          vendor_name: '鎰勝電子(深圳)有限公司',
          site: 'WZS-3',
          product_name: 'CP-DT',
          bu2_description: 'BU I-DT-ANNIE',
          sourcername: 'Eve Wang',
          buyername: 'Yingzhen Ouyang',
          buyer: 'AC0' },
        ]
      ).withArgs({ user: ['S87', 'S46', 'SH3', 'S20', 'S06', 'SA2', 'S56'],
        plant: ['F130', 'F131', 'F135', 'F132', 'F138', 'F136', 'F230'],
        dateFrom: '2017-01-21',
        dateTo: '2017-01-31',
        type1:
       ['Antenna',
         'Cable',
         'EMC',
         'Electro-Mechanical',
         'Housing',
         'ME-Others',
         'Memory',
         'Module',
         'NOR Flash',
         'Power IC',
         'Sensor',
         'Thermal'],
        type2:
       ['External Cable',
         'FFC',
         'FIO',
         'FPC',
         'Other',
         'Power Cord',
         'Mic',
         'Buzzer',
         'Aluminum',
         'Speaker'],
        supplyType: [1, 3, 11, 13, 14, 15],
        category: 'none',
        measure: 'amount',
        currency: 'USD' }).returns(
        [{ plant: 'F130',
          vendorcode: '0000619884',
          materialnumber: '27.01518.0J1',
          material_desc: 'POWER CORD 1800MM 250V EURO',
          currency: 'RMB',
          po_price: '4.5290000000000000',
          inforecord: '5302473867',
          quantity: '200.000',
          date: '2017-01-20T16:00:00.000Z',
          sourcer: 'S46',
          po_no: '0013460231',
          profit_center: 'PCP100',
          brand: 'ISHENG',
          usd_amount: 905.8,
          exchange_rate: '1.00000',
          supply_type: 'W',
          odmoem: 'ODM',
          type1: 'Cable',
          type2: 'Power Cord',
          vendor_base: 'ISHENG',
          vendor_group: 'ISHENG',
          short_name: 'ISHENG',
          vendor_name: '鎰勝電子(深圳)有限公司',
          site: 'WZS-3',
          product_name: 'CP-DT',
          bu2_description: 'BU I-DT-ANNIE',
          sourcername: 'Eve Wang',
          buyername: 'Yingzhen Ouyang',
          buyer: 'AC0' },
        { plant: 'F130',
          vendorcode: '0000619884',
          materialnumber: '27.01518.0J1',
          material_desc: 'POWER CORD 1800MM 250V EURO',
          currency: 'RMB',
          po_price: '4.5290000000000000',
          inforecord: '5302473867',
          quantity: '200.000',
          date: '2017-01-20T16:00:00.000Z',
          sourcer: 'S46',
          po_no: '0013460231',
          profit_center: 'PCP100',
          brand: 'ISHENG',
          usd_amount: 905.8,
          exchange_rate: '1.00000',
          supply_type: 'W',
          odmoem: 'ODM',
          type1: 'Cable',
          type2: 'Power Cord',
          vendor_base: 'ISHENG',
          vendor_group: 'ISHENG',
          short_name: 'ISHENG',
          vendor_name: '鎰勝電子(深圳)有限公司',
          site: 'WZS-3',
          product_name: 'CP-DT',
          bu2_description: 'BU I-DT-ANNIE',
          sourcername: 'Eve Wang',
          buyername: 'Yingzhen Ouyang',
          buyer: 'AC0' },
        ]
      )
      sinon.stub(spendingModel, 'getCurrencys').withArgs('USD', 'NTD').returns([
        { exange_rate: '31.903', date: '20170101' },
        { exange_rate: '31.710', date: '20161201' },
      ]).withArgs('all', 'USD').returns([
        { from_currency: 'RMB', exange_rate: '0.145', date: '20170101' },
        { from_currency: 'RMB', exange_rate: '0.146', date: '20161201' },
      ])
      let result = await reportService.genRawDataExcel(requestData)
      expect(result).to.exist

    })
  })
  describe('gen summary report data', () => {
    it('gen summary report', async () => {
      let requestData = {
        plant:['F132', 'F135', 'F138', 'F136', 'F230', 'F232'],
        user:['S56', 'S06', 'S20', 'S46', 'SH3', 'S87', 'S08'],
        dateFrom:'2018-02-01', dateTo:'2018-02-02',
        type1:['Antenna', 'Cable', 'EMC', 'Electro-Mechanical'],
        type2:['External Cable', 'FFC', 'FIO'],
        supplyType:[1, 3, 11, 13, 14, 15], category:'none',
        measure:'amount', currency:'USD' }

      sinon.stub(reportModel, 'genSummary').returns([
        { currency: 'RMB',
          odmoem: 'OEM',
          usd_amount: 75049.0642,
          month: '2018-02',
          product_name: 'CP-MT',
          profit_center: 'PCF000',
          site: 'WZS-6 (MNT)',
          type1: 'Cable',
          vendor_base: 'ACON',
          short_name: 'ACON',
          brand: 'ACON',
          plant: 'F138',
          type2: 'External Cable' },
        { currency: 'RMB',
          odmoem: 'ODM',
          usd_amount: 311856,
          month: '2018-02',
          product_name: 'CP-MT',
          profit_center: 'PCF200',
          site: 'WZS-6 (MNT)',
          type1: 'Cable',
          vendor_base: 'COXOC',
          short_name: 'COXOC',
          brand: 'COXOC',
          plant: 'F138',
          type2: 'External Cable' },
        { currency: 'RMB',
          odmoem: 'OEM',
          usd_amount: 1675422.22194,
          month: '2018-02',
          product_name: 'CP-MT',
          profit_center: 'PCF500',
          site: 'WZS-6 (MNT)',
          type1: 'Cable',
          vendor_base: 'COXOC',
          short_name: 'COXOC',
          brand: 'COXOC',
          plant: 'F138',
          type2: 'External Cable' },
        { currency: 'RMB',
          odmoem: 'ODM',
          usd_amount: 24245.672,
          month: '2018-02',
          product_name: 'CP-TV',
          profit_center: 'PCJ100',
          site: 'WZS-6 (TV)',
          type1: 'Cable',
          vendor_base: 'HIGHTEK',
          short_name: 'HIGHTEK',
          brand: 'HIGHTEK',
          plant: 'F132',
          type2: 'FFC' },
        { currency: 'RMB',
          odmoem: 'ODM',
          usd_amount: 2680.8,
          month: '2018-02',
          product_name: 'CP-MT',
          profit_center: 'PCF000',
          site: 'WZS-6 (MNT)',
          type1: 'Cable',
          vendor_base: 'HIGHTEK',
          short_name: 'HIGHTEK',
          brand: 'HIGHTEK',
          plant: 'F138',
          type2: 'FFC' },
        { currency: 'RMB',
          odmoem: 'ODM',
          usd_amount: 22383.439,
          month: '2018-02',
          product_name: 'CP-MT',
          profit_center: 'PCF300',
          site: 'WZS-6 (MNT)',
          type1: 'Cable',
          vendor_base: 'HIGHTEK',
          short_name: 'HIGHTEK',
          brand: 'HIGHTEK',
          plant: 'F138',
          type2: 'FFC' },
        { currency: 'RMB',
          odmoem: 'ODM',
          usd_amount: 43449.1648,
          month: '2018-02',
          product_name: 'CP-MT',
          profit_center: 'PCF500',
          site: 'WZS-6 (MNT)',
          type1: 'Cable',
          vendor_base: 'HIGHTEK',
          short_name: 'HIGHTEK',
          brand: 'HIGHTEK',
          plant: 'F138',
          type2: 'FFC' },
        { currency: 'RMB',
          odmoem: 'ODM',
          usd_amount: 262018.95856,
          month: '2018-02',
          product_name: 'CP-MT',
          profit_center: 'PCF500',
          site: 'WZS-6 (MNT)',
          type1: 'Cable',
          vendor_base: 'HONGLIN',
          short_name: 'HONGLIN',
          brand: 'HONGLIN',
          plant: 'F138',
          type2: 'External Cable' },
        { currency: 'RMB',
          odmoem: 'OEM',
          usd_amount: 7652.24922,
          month: '2018-02',
          product_name: 'CP-MT',
          profit_center: 'PCF500',
          site: 'WZS-6 (MNT)',
          type1: 'Cable',
          vendor_base: 'HONGLIN',
          short_name: 'HONGLIN',
          brand: 'HONGLIN',
          plant: 'F138',
          type2: 'External Cable' },
        { currency: 'RMB',
          odmoem: 'ODM',
          usd_amount: 33449.76,
          month: '2018-02',
          product_name: 'CP-MT',
          profit_center: 'PCF300',
          site: 'WZS-6 (MNT)',
          type1: 'Cable',
          vendor_base: 'HOTRON',
          short_name: 'HOTRON',
          brand: 'HOTRON',
          plant: 'F138',
          type2: 'External Cable' },
        { currency: 'RMB',
          odmoem: 'ODM',
          usd_amount: 12207.36,
          month: '2018-02',
          product_name: 'CP-MT',
          profit_center: 'PCF500',
          site: 'WZS-6 (MNT)',
          type1: 'Cable',
          vendor_base: 'HOTRON',
          short_name: 'HOTRON',
          brand: 'HOTRON',
          plant: 'F138',
          type2: 'External Cable' },
        { currency: 'RMB',
          odmoem: 'OEM',
          usd_amount: 117844.38176,
          month: '2018-02',
          product_name: 'CP-MT',
          profit_center: 'PCF200',
          site: 'WZS-6 (MNT)',
          type1: 'Cable',
          vendor_base: 'HOTRON',
          short_name: 'HOTRON',
          brand: 'HOTRON',
          plant: 'F138',
          type2: 'External Cable' },
        { currency: 'RMB',
          odmoem: 'OEM',
          usd_amount: 19848489.77778,
          month: '2018-02',
          product_name: 'CP-MT',
          profit_center: 'PCF500',
          site: 'WZS-6 (MNT)',
          type1: 'Cable',
          vendor_base: 'HOTRON',
          short_name: 'HOTRON',
          brand: 'HOTRON',
          plant: 'F138',
          type2: 'External Cable' },
        { currency: 'RMB',
          odmoem: 'OEM',
          usd_amount: 39008.4291,
          month: '2018-02',
          product_name: 'CP-MT',
          profit_center: 'PCF200',
          site: 'WZS-6 (MNT)',
          type1: 'Cable',
          vendor_base: 'ICT',
          short_name: 'ICT',
          brand: 'ICT',
          plant: 'F138',
          type2: 'External Cable' },
        { currency: 'RMB',
          odmoem: 'ODM',
          usd_amount: 19569.312,
          month: '2018-02',
          product_name: 'CP-MT',
          profit_center: 'PCF200',
          site: 'WZS-6 (MNT)',
          type1: 'Cable',
          vendor_base: 'ICT',
          short_name: 'ICT',
          brand: 'ICT',
          plant: 'F138',
          type2: 'FFC' },
        { currency: 'RMB',
          odmoem: 'OEM',
          usd_amount: 1570671.15306,
          month: '2018-02',
          product_name: 'CP-MT',
          profit_center: 'PCF500',
          site: 'WZS-6 (MNT)',
          type1: 'Cable',
          vendor_base: 'JI-HAW',
          short_name: 'JI-HAW',
          brand: 'JIHAW',
          plant: 'F138',
          type2: 'External Cable' },
      ])
      sinon.stub(reportModel, 'getSummaryRawData').returns([{ currency: 'RMB',
        vendorcode: '0000618414',
        vendor_base: 'ACON',
        vendor_group: 'ACON',
        site: 'WZS-6 (MNT)',
        brand: 'ACON',
        plant: 'F138',
        type1: 'Cable',
        type2: 'External Cable',
        supply_type: 'A',
        odmoem: 'OEM',
        month: '2018-02',
        profit_center: 'PCF000',
        product_name: 'CP-MT',
        bu2_description: 'BU MT-OTHERS',
        gr_qty: 2585,
        usdamount: 75049.0642 },
      { currency: 'RMB',
        vendorcode: '0000618072',
        vendor_base: 'JVE',
        vendor_group: 'JVE',
        site: 'WZS-6 (MNT)',
        brand: 'JVE',
        plant: 'F138',
        type1: 'Cable',
        type2: 'External Cable',
        supply_type: 'A',
        odmoem: 'OEM',
        month: '2018-02',
        profit_center: 'PCF200',
        product_name: 'CP-MT',
        bu2_description: 'BU MT-ASTRO',
        gr_qty: 67872,
        usdamount: 265208.48256 },
      { currency: 'RMB',
        vendorcode: '0000019497',
        vendor_base: 'JI-HAW',
        vendor_group: 'JI-HAW',
        site: 'WZS-6 (MNT)',
        brand: 'JIHAW',
        plant: 'F138',
        type1: 'Cable',
        type2: 'External Cable',
        supply_type: 'A',
        odmoem: 'OEM',
        month: '2018-02',
        profit_center: 'PCF500',
        product_name: 'CP-MT',
        bu2_description: 'BU MT-ROSA',
        gr_qty: 224994,
        usdamount: 1570671.15306 },
      { currency: 'RMB',
        vendorcode: '0000601336',
        vendor_base: 'LONGWELL',
        vendor_group: 'LONGWELL',
        site: 'WZS-6 (MNT)',
        brand: 'LONGWELL',
        plant: 'F138',
        type1: 'Cable',
        type2: 'External Cable',
        supply_type: 'A',
        odmoem: 'OEM',
        month: '2018-02',
        profit_center: 'PCF500',
        product_name: 'CP-MT',
        bu2_description: 'BU MT-ROSA',
        gr_qty: 14544,
        usdamount: 143473.36032 },
      { currency: 'RMB',
        vendorcode: '0000612514',
        vendor_base: 'HONGLIN',
        vendor_group: 'HONGLIN',
        site: 'WZS-6 (MNT)',
        brand: 'HONGLIN',
        plant: 'F138',
        type1: 'Cable',
        type2: 'External Cable',
        supply_type: 'A',
        odmoem: 'OEM',
        month: '2018-02',
        profit_center: 'PCF500',
        product_name: 'CP-MT',
        bu2_description: 'BU MT-ROSA',
        gr_qty: 1086,
        usdamount: 7652.24922 },
      { currency: 'RMB',
        vendorcode: '0000613334',
        vendor_base: 'COXOC',
        vendor_group: 'COXOC',
        site: 'WZS-6 (MNT)',
        brand: 'COXOC',
        plant: 'F138',
        type1: 'Cable',
        type2: 'External Cable',
        supply_type: 'A',
        odmoem: 'OEM',
        month: '2018-02',
        profit_center: 'PCF500',
        product_name: 'CP-MT',
        bu2_description: 'BU MT-ROSA',
        gr_qty: 220524,
        usdamount: 1675422.22194 },
      { currency: 'RMB',
        vendorcode: '0000616359',
        vendor_base: 'HOTRON',
        vendor_group: 'HOTRON',
        site: 'WZS-6 (MNT)',
        brand: 'HOTRON',
        plant: 'F138',
        type1: 'Cable',
        type2: 'External Cable',
        supply_type: 'A',
        odmoem: 'OEM',
        month: '2018-02',
        profit_center: 'PCF500',
        product_name: 'CP-MT',
        bu2_description: 'BU MT-ROSA',
        gr_qty: 2029206,
        usdamount: 19848489.77778 },
      { currency: 'RMB',
        vendorcode: '0000618072',
        vendor_base: 'JVE',
        vendor_group: 'JVE',
        site: 'WZS-6 (MNT)',
        brand: 'JVE',
        plant: 'F138',
        type1: 'Cable',
        type2: 'External Cable',
        supply_type: 'A',
        odmoem: 'OEM',
        month: '2018-02',
        profit_center: 'PCF500',
        product_name: 'CP-MT',
        bu2_description: 'BU MT-ROSA',
        gr_qty: 20678,
        usdamount: 157756.39082 }])
      sinon.stub(reportModel, 'getProductName').returns('Monitor')
      let result = await reportService.genSummaryExcel(requestData)
      expect(result).to.undefined

    })
  })
})
