module.exports = {
  xraySummaryHeader: {
    opportunityHeaderKey: [
      { key: 'no',},
      { key: 'purGroup',}, 
      { key: 'oemODM', },
      { key: 'typeI', },
      { key: 'typeII', }, 
      { key: 'wistronPN', },
      { key: 'description',},
      { key: 'vendorName', }, 
      { key: 'manufacturer',},
      { key: 'vendorPN', },
      { key: 'supplyType', }, 
      { key: 'mrp', style: { numFmt : '#,##0' }},
      { key: 'currency',},
      { key: 'price', style: { numFmt : '#,##0.00000' }}, 
      { key: 'originalCurrency', },
      { key: 'originalPrice',style: { numFmt : '#,##0.00000' }},
      { key: 'validFrom', }, 
      { key: 'cmp', },
      { key: 'suggCmp',},
      { key: 'suggObs',}, 
      { key: 'suggExp', },
      { key: 'suggPartNumber', },
      { key: 'suggDescription', }, 
      { key: 'suggLastPrice', style: { numFmt : '#,##0.00000' }},
      { key: 'opportunity', },
      { key: 'opportunityPercent',}, 
      { key: 'suggInAltGroup', },
      { key: 'suggFrom', },
      { key: 'spaPartNumber',}, 
      { key: 'spaDescription', },
      { key: 'spaVendor', },
      { key: 'spaManufacturer', }, 
      { key: 'spaVendorPN', },
      { key: 'spaSupplyType', },
      { key: 'spaMrp', style: { numFmt : '#,##0' }}, 
      { key: 'spaCurrency', },
      { key: 'spaLastPrice', style: { numFmt : '#,##0.00000' }},
      { key: 'spaOriginalCurrency'}, 
      { key: 'spaOriginalPrice', style: { numFmt : '#,##0.00000' }},
      { key: 'spaValidFrom',},
      { key: 'spaCmp'}, 
      { key: 'spaObs',},
      { key: 'spaExp',},
      { key: 'altPartNumber',}, 
      { key: 'altDescription',},
      { key: 'altVendor', },
      { key: 'altManufacturer',}, 
      { key: 'altVendorPN',},
      { key: 'altSupplyType',},
      { key: 'altMrp',style: { numFmt : '#,##0' }}, 
      { key: 'altCurrency', },
      { key: 'altLastPrice',style: { numFmt : '#,##0.00000' }},
      { key: 'altOriginalCurrency',}, 
      { key: 'altOriginalPrice',style: { numFmt : '#,##0.00000' }},
      { key: 'altValidFrom',},
      { key: 'altCmp', }, 
      { key: 'altObs', },
      { key: 'altExp',},
    ],
    opportunityHeader: [
      'No.','Pur.Group', 'OEM/ODM', 'Type I', 'Type II',
      'Wistron P/N', 'Description', 'Vendor Name',
      'Manufacturer', 'Vendor P/N', 'Supply Type', 'Last MRP',
      'Curr.', 'Last Price', 'Org. Curr.', 'Org. Last Price',
      'ValidFrom', 'Org. P/N CMP', 'Sugg. P/N CMP', 'Sugg. P/N OBS',
      'Sugg. P/N EXP/EOL', 'Sugg. P/N', 'Sugg. Description', 'Sugg. Last Price (USD)',
      'Opportunity(USD)', 'Opportunity(%)', 'Sugg. in ALT Group', 'Sugg. From', 'SPA P/N',
      'SPA Description', 'SPA Vendor Name', 'SPA Manufacturer', 'SPA Vendor P/N',
      'SPA Supply Type', 'SPA Last MRP', 'SPA Curr.', 'SPA Last Price',
      'SPA Org. Curr.', 'SPA Org. Last Price', 'SPA ValidFrom', 'SPA CMP', 'SPA OBS',
      'SPA EXP/EOL', 'ALT P/N', 'ALT Description', 'ALT Vendor Name', 'ALT Manufacturer',
      'ALT Vendor P/N', 'ALT Supply Type', 'ALT Last MRP',
      'ALT Curr.', 'ALT Last Price', 'ALT Org. Curr.', 'ALT Org. Last Price',
      'ALT ValidFrom', 'ALT CMP',
      'ALT OBS', 'ALT EXP/EOL'
    ],
    spaHeaderKey: [
      { key: 'wistronPN'},
      { key: 'spaPartNumber'},
      { key: 'spaDescription'},
      { key: 'spaManufacturer'},
      { key: 'spaVendor'},
      { key: 'spaVendorPN'},
      { key: 'spaSupplyType'},
      { key: 'spaMrp', style: { numFmt : '#,##0' }},
      { key: 'spaCurrency'},
      { key: 'spaLastPrice', style: { numFmt : '#,##0.00000' }},
      { key: 'spaOriginalCurrency'},
      { key: 'spaOriginalPrice', style: { numFmt : '#,##0.00000' }},
      { key: 'spaValidFrom'},
      { key: 'spaPriceDiff', style: { numFmt : '#,##0.00%' }},
      { key: 'spaCmp'},
      { key: 'spaObs'},
      { key: 'spaExp'},
      { key: 'spec01'},
      { key: 'spec02'},
      { key: 'spec03'},
      { key: 'spec04'},
      { key: 'spec05'},
      { key: 'spec06'},
      { key: 'spec07'},
      { key: 'spec08'},
      { key: 'spec09'},
      { key: 'spec10'},
      { key: 'spec11'},
      { key: 'spec12'},
      { key: 'spec13'},
      { key: 'spec14'},
      { key: 'spec15'},
      { key: 'spec16'},
      { key: 'spec17'},
      { key: 'spec18'},
      { key: 'spec19'},
      { key: 'spec20'},
      { key: 'spec21'},
      { key: 'spec22'},
      { key: 'spec23'},
      { key: 'spec24'},
      { key: 'spec25'},
      { key: 'spec26'},
      { key: 'spec27'},
      { key: 'spec28'},
      { key: 'spec29'},
      { key: 'spec30'},
    ],
    spaHeader: [
      'Ref. P/N', 'Part Number', 'Description', 'Manufacturer', 'Vendor Name', 'Vendor Part No.',
      'Supply Type', 'Last MRP', 'Curr.', 'Last Price', 'Org. Curr.', 'Org. Last Price',
      'ValidFrom', 'Price Diff. %', 'CMP', 'OBS', 'EXP/EOL', 'Spec01', 'Spec02', 'Spec03',
      'Spec04', 'Spec05', 'Spec06', 'Spec07', 'Spec08', 'Spec09',
      'Spec10', 'Spec11', 'Spec12', 'Spec13', 'Spec14', 'Spec15', 'Spec16',
      'Spec17','Spec18', 'Spec19', 'Spec20',
      'Spec21', 'Spec22', 'Spec23', 'Spec24', 'Spec25',
      'Spec26', 'Spec27', 'Spec28', 'Spec29', 'Spec30'
    ],
    summaryBasicHeaderKey: [
      { header: 'Import File', key: 'importFile', width: 15, style: { font: true}},
      { header: 'Import Date', key: 'importDate', width: 15, style: { font: true}},
    ],
    summaryTypeHeaderKey: [
      { key: 'vendor', width: 15, },
      { key: 'type1', width: 15},
      { key: 'type2', width: 15},
      { key: 'lastPrice', width: 15, style: { numFmt : '#,##0.00000' }},
      { key: 'suggestionCost', width: 15, style: { numFmt : '#,##0.00000' }},
      { key: 'opportunity', width: 15, style: { numFmt : '#,##0.00000' }},
      { key: 'opportunityPercent', width: 15}
    ],
    summaryTypeHeader: [ '', 'TYPE I', 'TYPE II', 'Last Price', 'Suggestion Cost', 'Opportunity', 'Opportunity %'],
    summaryVendorHeaderKey: [
      { key: 'vendor', width: 15, },
      { key: 'type1', width: 15},
      { key: 'manufacturer', width: 15},
      { key: 'vendorName', width: 15},
      { key: 'lastPrice', width: 15, style: { numFmt : '#,##0.00000' }},
      { key: 'suggestionCost', width: 15, style: { numFmt : '#,##0.00000' }},
      { key: 'opportunity', width: 15, style: { numFmt : '#,##0.00000' }},
      { key: 'opportunityPercent', width: 15},
    ],
    summaryVendorHeader: ['', 'TYPE I', 'Manufacturer', 'Vendor Name', 'Last Price', 'Suggestion Cost', 'Opportunity', 'Opportunity %'],
    exchangeRateHeaderKey: [
      { header: 'From', key: 'from', width: 10, style: { font: true}},
      { header: 'To', key: 'to', width: 10, style: { font: true}},
      { header: 'SAP Exchange Rate', key: 'sap_exchange_rate', width: 20, style: { font: true}},
      { header: 'Data', key: 'date', width: 10, style: { font: true}},
    ],
    partNumberColor: ['FFCDD3', 'FFDFB3', 'FFF8C4', 'C8E6C9', 'BBDEFB', 'E1BEE7', 'C5CAE9', 'D7CCC8', 'CFD8DC', 'E0E0E0'],
    eRateDefaultFirstHeader: ['Exchange Rate', 'Exchange Rate', 'Exchange Rate'],
    eRateDefaultSecondHeader: ['RMB-USD', 'NTD-USD', 'JPY-USD']


  }
}